/**
 * Ordence — What a Workflow May Touch
 * Version: v0.23.0-alpha
 *
 * Pure. A frozen catalogue, no database access.
 *
 * ══════════════════════════════════════════════════════════════════════
 * ⭐ THIS FILE IS THE SECURITY BOUNDARY OF THE RECORD ACTIONS
 * ══════════════════════════════════════════════════════════════════════
 * `create_record`, `update_record`, `delete_record` and `find_records`
 * take a table name and a column list from a definition a TENANT WROTE.
 * Passed through to SQL, that is not an automation feature — it is an
 * arbitrary-statement primitive with a JSON front end:
 *
 *     recordType: "users"        → grant yourself a role
 *     values: { tenant_id: … }   → move a record into another workspace
 *     values: { deleted_at: … }  → empty a table one row at a time
 *     recordType: "audit_logs"   → write history that never happened
 *
 * None of those needs a database exploit. They need the executor to
 * believe the definition, which is why the executor never does.
 *
 * The rule this file exists to enforce is:
 *
 *   ⚠️ EVERY TABLE NAME AND EVERY COLUMN NAME THAT REACHES SQL COMES FROM
 *   THIS FROZEN OBJECT. Nothing from a workflow definition is ever
 *   interpolated into a statement — the definition only ever SELECTS from
 *   this catalogue, and an entry that is not here does not exist.
 *
 * Values are still parameterised, always. That protects against
 * injection. It does nothing about a workflow updating a column it was
 * never meant to reach, which is what an allow-list is for.
 */

/* ------------------------------------------------------------------ */
/* THE CATALOGUE                                                       */
/* ------------------------------------------------------------------ */

export type RecordTypeDefinition = {
  /** The real table. Never taken from a definition. */
  table: string;
  label: string;
  /**
   * Columns a workflow may WRITE.
   *
   * ⚠️ NOTE WHAT IS ABSENT FROM EVERY LIST: `id`, `tenant_id`,
   * `created_at`, `deleted_at`, `deleted_by`, and every column another
   * phase's trigger depends on. `units.status` is missing for exactly
   * that reason — Phase 22 spent a whole file making unit status
   * coherent, and an automation that sets it directly walks around
   * `enforce_unit_bookable` and `bookings_sync_unit` in one line.
   * A workflow books a unit by creating a booking, like everybody else.
   */
  writableColumns: readonly string[];
  /** Columns a workflow may READ or filter on. */
  readableColumns: readonly string[];
  /** Columns that must be present on a create. */
  requiredOnCreate: readonly string[];
  permissions: {
    read: string;
    create: string | null;
    update: string | null;
    /** `null` means this record type cannot be deleted by an automation. */
    delete: string | null;
  };
  /**
   * True when "delete" means `deleted_at = now()`.
   *
   * ⚠️ Every deletable type here is soft-deleted, and that is not a
   * coincidence: the application role holds no DELETE grant on any of
   * them (Phase 22, Section 9). A hard DELETE from a workflow step would
   * fail with 42501 halfway through a run, leaving the earlier steps
   * committed and the author staring at "permission denied" for an
   * action the builder offered them.
   */
  softDelete: boolean;
};

export const RECORD_TYPES = {
  lead: {
    table: "leads",
    label: "Lead",
    writableColumns: [
      "name", "email", "phone", "preferred_lang", "source", "status",
      "temperature", "score", "requirement", "project_id", "owner_id",
      "is_nri", "country", "timezone", "next_follow_up_at", "lost_reason",
      "locality", "budget_min_minor", "budget_max_minor",
    ],
    readableColumns: [
      "id", "reference", "name", "email", "phone", "source", "status",
      "temperature", "score", "project_id", "owner_id", "is_nri", "country",
      "next_follow_up_at", "lost_reason", "locality", "budget_min_minor",
      "budget_max_minor", "channel_partner_id", "cp_locked_until",
      "consent_at", "created_at", "updated_at",
    ],
    // ⚠️ `reference` is NOT required and NOT writable. It is generated by
    // `server/sales/references.ts` under a lock; letting a workflow pick
    // one is how two leads end up as LEAD-2044.
    requiredOnCreate: ["name"],
    permissions: {
      read: "leads:read",
      create: "leads:create",
      update: "leads:update",
      delete: "leads:delete",
    },
    softDelete: true,
  },

  unit: {
    table: "units",
    label: "Unit",
    // ⚠️ NO `status`, NO `hold_until`, NO `held_for_lead_id`. See the note
    // on `writableColumns` above — the hold and booking machinery is a
    // set of database guarantees, not a set of columns.
    writableColumns: [
      "tower", "floor", "typology", "carpet_area_sqft", "built_up_area_sqft",
      "facing", "price_minor",
    ],
    readableColumns: [
      "id", "project_id", "code", "tower", "floor", "typology",
      "carpet_area_sqft", "built_up_area_sqft", "facing", "price_minor",
      "status", "hold_until", "held_for_lead_id", "created_at", "updated_at",
    ],
    requiredOnCreate: [],
    permissions: {
      read: "units:read",
      create: null,
      update: "units:update",
      // Inventory is never removed by an automation. A unit that stops
      // existing takes its bookings' history with it.
      delete: null,
    },
    softDelete: true,
  },

  booking: {
    table: "bookings",
    label: "Booking",
    // ⚠️ NOT `status`. Advancing a booking runs `advanceBooking`, which
    // enforces forward-only movement and moves the lead with it. And NOT
    // `cancelled` by any route — cancellation frees a unit and moves
    // money, and it is a `bookings:cancel` decision a person makes.
    writableColumns: ["payment_status", "sales_rep_id", "channel_partner_id"],
    readableColumns: [
      "id", "reference", "lead_id", "unit_id", "sales_rep_id",
      "channel_partner_id", "status", "payment_status",
      "agreement_value_minor", "booked_at", "cancelled_at", "created_at",
    ],
    requiredOnCreate: [],
    permissions: {
      read: "bookings:read",
      // ⚠️ Deliberately not creatable from a workflow. `createBooking` is
      // three layers of double-sale protection and a lead status change
      // in one transaction; an INSERT that skipped it would be the exact
      // "one flat, two buyers" outcome Phase 22 exists to prevent.
      create: null,
      update: "bookings:update",
      delete: null,
    },
    softDelete: false,
  },

  project: {
    table: "projects",
    label: "Project",
    writableColumns: [
      "name", "description", "address_line", "city", "state", "rera_number",
      "is_active", "expected_completion_at",
    ],
    readableColumns: [
      "id", "code", "name", "city", "state", "rera_number", "is_active",
      "started_at", "expected_completion_at", "created_at",
    ],
    requiredOnCreate: [],
    permissions: {
      read: "projects:read",
      create: null,
      update: "projects:manage",
      delete: null,
    },
    softDelete: true,
  },

  contact: {
    table: "contacts",
    label: "Contact",
    writableColumns: [
      "first_name", "last_name", "email", "phone", "mobile", "job_title",
      "department", "company_id", "owner_id", "notes", "last_contacted_at",
    ],
    readableColumns: [
      "id", "first_name", "last_name", "email", "phone", "mobile",
      "job_title", "company_id", "owner_id", "last_contacted_at",
      "created_at", "updated_at",
    ],
    requiredOnCreate: ["first_name"],
    permissions: {
      read: "contacts:read",
      create: "contacts:create",
      update: "contacts:update",
      delete: "contacts:delete",
    },
    softDelete: true,
  },

  company: {
    table: "companies",
    label: "Company",
    writableColumns: [
      "name", "domain", "industry", "employee_count", "website", "phone",
      "city", "state", "country", "owner_id", "notes",
    ],
    readableColumns: [
      "id", "name", "domain", "industry", "employee_count", "website",
      "city", "state", "country", "owner_id", "created_at", "updated_at",
    ],
    requiredOnCreate: ["name"],
    permissions: {
      read: "companies:read",
      create: "companies:create",
      update: "companies:update",
      delete: "companies:delete",
    },
    softDelete: true,
  },

  deal: {
    table: "deals",
    label: "Deal",
    writableColumns: [
      "title", "description", "amount", "currency", "stage", "probability",
      "expected_close_date", "lost_reason", "source", "owner_id",
      "contact_id", "company_id",
    ],
    readableColumns: [
      "id", "title", "amount", "currency", "stage", "probability",
      "expected_close_date", "actual_close_date", "lost_reason", "owner_id",
      "contact_id", "company_id", "created_at", "updated_at",
    ],
    requiredOnCreate: ["title"],
    permissions: {
      read: "deals:read",
      create: "deals:create",
      update: "deals:update",
      delete: "deals:delete",
    },
    softDelete: true,
  },
} as const satisfies Record<string, RecordTypeDefinition>;

export type RecordTypeKey = keyof typeof RECORD_TYPES;

export const RECORD_TYPE_KEYS = Object.keys(RECORD_TYPES) as RecordTypeKey[];

/**
 * ⚠️ `Object.hasOwn`, never `in`. `"constructor"` passes an `in` test on
 * any object literal, and a record type of "constructor" resolving to a
 * function is the start of a much worse afternoon.
 */
export function isRecordType(value: unknown): value is RecordTypeKey {
  return typeof value === "string" && Object.hasOwn(RECORD_TYPES, value);
}

export function recordTypeFor(value: unknown): RecordTypeDefinition | null {
  return isRecordType(value) ? RECORD_TYPES[value] : null;
}

/* ------------------------------------------------------------------ */
/* THE QUESTIONS THE PLANNER AND EXECUTOR ASK                          */
/* ------------------------------------------------------------------ */

export type RecordOperation = "read" | "create" | "update" | "delete";

/**
 * The permission a step needs, or null when the operation is not offered
 * on that record type at all.
 *
 * ⚠️ RETURNS null FOR BOTH "unknown record type" AND "operation not
 * supported", and the caller must treat both as a refusal. An engine that
 * distinguished them by running the step would be deciding policy from
 * the shape of an error.
 */
export function permissionForRecordAction(
  recordType: unknown,
  operation: RecordOperation,
): string | null {
  const definition = recordTypeFor(recordType);
  if (!definition) return null;
  return definition.permissions[operation];
}

/**
 * Split a set of proposed column writes into the ones that are allowed
 * and the ones that are not.
 *
 * Returns both halves rather than throwing, because the run history needs
 * to say WHICH column was refused. "That workflow does not work" is the
 * support ticket; "step 3 tried to write `tenant_id` on a lead" is the
 * answer.
 */
export function partitionWritableColumns(
  recordType: unknown,
  columns: readonly string[],
): { allowed: string[]; refused: string[] } {
  const definition = recordTypeFor(recordType);
  if (!definition) return { allowed: [], refused: [...columns] };

  const allowed: string[] = [];
  const refused: string[] = [];
  for (const column of columns) {
    if (definition.writableColumns.includes(column)) allowed.push(column);
    else refused.push(column);
  }
  return { allowed, refused };
}

export function isReadableColumn(recordType: unknown, column: string): boolean {
  const definition = recordTypeFor(recordType);
  return definition ? definition.readableColumns.includes(column) : false;
}
