/**
 * Ordence — Server error instrumentation
 * Version: v0.32.0-alpha
 *
 * ══════════════════════════════════════════════════════════════════════════
 * WHY THIS FILE EXISTS
 * ══════════════════════════════════════════════════════════════════════════
 * A server exception in a Cloudflare Worker reached the log looking like this:
 *
 *     "message": "    at worker.js:142989:19\n    at p2 (worker.js:139337:147)"
 *
 * Two minified frames and NOTHING ELSE. No message, no error type, no route,
 * no cause. The bundle those line numbers refer to is regenerated by every
 * build, so they cannot even be mapped after the fact unless you still have
 * the exact artefact that produced them — which nobody does.
 *
 * Next.js hands the real error object to `onRequestError` before it reduces
 * it to a digest for the browser. Reading it here is the difference between
 * "something failed on /dashboard" and "TenantAccessError: user not
 * provisioned, thrown from server/tenant-context.ts".
 *
 * ══════════════════════════════════════════════════════════════════════════
 * ⚠️ THIS RUNS ON A SERVER THAT HOLDS EVERY TENANT'S DATA
 * ══════════════════════════════════════════════════════════════════════════
 * The log is operator-visible, so what goes in it matters:
 *
 *   • The error's own message and stack — yes. That is the point.
 *   • The route and method — yes. An error with no route is a riddle.
 *   • Request headers, cookies, query strings, bodies — NEVER. A Clerk
 *     session cookie in a log line is a stealable session, and a query
 *     string routinely carries a customer's search terms.
 *
 * Nothing below reads anything from the request except its path and method.
 */

/**
 * ⭐ v0.95.0 — SENTRY INITIALISES HERE, and the console logging below
 *    STAYS. Two destinations, on purpose:
 *
 *   Railway logs — always on, no vendor, no quota, and the only thing
 *     that still works when Sentry itself is the outage.
 *   Sentry — searchable, grouped, alerting, and it names the commit.
 *
 * ⚠️ REMOVING THE `console.error` CALLS WHEN ADDING SENTRY IS THE
 *    OBVIOUS TIDY-UP AND IT IS WRONG. The 12 August outage was diagnosed
 *    from Railway logs. A monitoring vendor is one more dependency that
 *    can be down, misconfigured, or out of quota on the day you need it.
 */
export async function register() {
  /**
   * ══════════════════════════════════════════════════════════════════
   * 🔴 CONFIG VALIDITY IS A BOOT QUESTION, NOT A RUNTIME DISCOVERY
   * ══════════════════════════════════════════════════════════════════
   * Until v1.32.0 nothing here validated anything, `getServerEnv()` was
   * lazy by design, and `/api/health` returned a hard-coded body — so a
   * deployment with no webhook secret, no admin allowlist and no vault
   * keys served 200s indefinitely while being unable to create a single
   * workspace. See `lib/env-boot.ts` for what it checks and, more
   * importantly, what it deliberately does not.
   *
   * ⚠️ BEFORE SENTRY, AND NOT GATED ON IT. `SENTRY_ENABLED` is false in
   * plenty of correct deployments, and the early return below would
   * have skipped this entirely.
   *
   * ⚠️ NODE RUNTIME ONLY. `register()` runs once per runtime; asserting
   * on the edge runtime as well would print the same block twice and
   * add a second way for a deploy to fail for the same reason.
   */
  if (process.env.NEXT_RUNTIME === "nodejs") {
    const { assertBootEnv } = await import("@/lib/env-boot");
    assertBootEnv();

    /**
     * ══════════════════════════════════════════════════════════════════
     * ⭐⭐⭐ WAVE 8 — THE RATE LIMITER GETS A COUNTER THAT COUNTS
     * ══════════════════════════════════════════════════════════════════
     * `lib/security/rate-limit.ts` has said this since Phase 20:
     *
     *     "Per-instance memory counters are a speed bump, not a control:
     *      on a serverless deployment the effective limit is
     *      (limit × instances)."
     *
     * That was this deployment. `UPSTASH_REDIS_REST_*` is not set, so the
     * auth limit of 10/minute was 10 × however many instances Railway was
     * running — a number nobody controls and nobody knows.
     *
     * ⚠️ REGISTERED HERE AND NOT AT A MODULE TOP LEVEL. An import-time
     * side effect runs in whatever bundle pulls the module in, including
     * the edge one, where `node:crypto` and the database client do not
     * exist. `register()` runs once per Node process, which is exactly
     * the scope a process-wide registration wants.
     *
     * 🔴 IT ALSO WIRES `onRateLimitDegraded`, WHICH HAD NO CALLER
     * ANYWHERE. The `rate_limit.degraded` security event has existed
     * since Phase 20 with a severity, a label and a SIEM mapping, and had
     * never fired once.
     */
    const { installDurableRateLimiter } = await import(
      "@/server/security/rate-limit-durable"
    );
    installDurableRateLimiter();

    /**
     * ══════════════════════════════════════════════════════════════════
     * ⭐⭐⭐ WAVE 9 — AND THE SECOND HOOK THAT NOTHING HAD EVER WIRED
     * ══════════════════════════════════════════════════════════════════
     * `server/security/record.ts` exports `onSecurityRecordFailure` and
     * says why:
     *
     *     "the failure mode this module must not have is 'the database is
     *      unreachable during an intrusion, so nothing is recorded and
     *      nothing is alerted either'."
     *
     * 🔴 NOTHING CALLED IT. A failed write of a CRITICAL security event
     * produced one `console.error` and no alert. Found the same way the
     * rate limiter's hook was — by grepping registration functions for
     * their callers.
     */
    const { installSecurityAlerting } = await import("@/server/security/alerting");
    installSecurityAlerting();

    /**
     * ══════════════════════════════════════════════════════════════════
     * ⭐⭐⭐ WAVE 14 — AND THE THIRD ONE, WHICH IS THE PROCESS ITSELF
     * ══════════════════════════════════════════════════════════════════
     * `installObservability()` attaches `uncaughtExceptionMonitor` and
     * `unhandledRejection` listeners and writes one boot line.
     *
     * ⚠️ IT IS `uncaughtExceptionMonitor` AND NOT `uncaughtException`,
     * and the difference is that the second one would SUPPRESS Node's
     * default crash and leave this process serving traffic from a state
     * nobody has reasoned about. `server/observability/runtime.ts`
     * argues it at length; it is repeated here because this is the line
     * somebody would "tidy up".
     *
     * ⚠️ IT OPENS NO DATABASE CONNECTION. `register()` runs before the
     * first request; a database call here turns a Neon cold start into a
     * failed deploy, with an error naming the observability layer rather
     * than the database.
     */
    const { installObservability } = await import("@/server/observability/runtime");
    installObservability();
  }

  if (!SENTRY_ENABLED) return;

  /**
   * ⚠️ DYNAMIC IMPORT, GATED ON THE RUNTIME. `@sentry/nextjs`'s Node
   * integrations pull in `async_hooks` and friends, which do not exist on
   * the edge runtime — a static top-level import breaks the edge bundle
   * at build time, not at run time, and the error names neither Sentry
   * nor the runtime.
   */
  if (process.env.NEXT_RUNTIME === "nodejs") {
    const Sentry = await import("@sentry/nextjs");
    Sentry.init(baseOptions());
  }

  if (process.env.NEXT_RUNTIME === "edge") {
    const Sentry = await import("@sentry/nextjs");
    Sentry.init(baseOptions());
  }
}

import { baseOptions, SENTRY_ENABLED } from "@/lib/observability/sentry-options";

type ErrorRequest = {
  path?: string;
  method?: string;
};

type ErrorContext = {
  routerKind?: string;
  routePath?: string;
  routeType?: string;
  renderSource?: string;
};

/**
 * Called by Next.js for every uncaught server-side error, BEFORE the digest
 * replaces it. One line, greppable, with the parts that identify the fault.
 */
export function onRequestError(
  error: unknown,
  request: ErrorRequest,
  context: ErrorContext,
): void {
  const err = error as { name?: string; message?: string; stack?: string; digest?: string; cause?: unknown };

  /*
   * ⚠️ `err.message` can be an empty string — that is exactly how the
   * original report arrived, and why it was undiagnosable. Say so explicitly
   * rather than logging an empty field that reads as "no error here".
   */
  const message =
    typeof err?.message === "string" && err.message.length > 0
      ? err.message
      : "(the thrown value carried no message)";

  const parts = [
    `[ordence:error] ${err?.name ?? "Error"}: ${message}`,
    `route=${context?.routePath ?? request?.path ?? "unknown"}`,
    `method=${request?.method ?? "?"}`,
    `type=${context?.routeType ?? "?"}`,
    `source=${context?.renderSource ?? "?"}`,
  ];

  if (err?.digest) parts.push(`digest=${err.digest}`);

  // The digest is what the BROWSER shows the user. Logging it beside the
  // real message is what lets somebody holding a screenshot of
  // "Digest: 817564861" find this line instead of guessing.
  console.error(parts.join(" | "));

  if (err?.stack) console.error(`[ordence:error] stack: ${err.stack}`);

  // A wrapped error hides the interesting half in `cause`. Postgres and
  // fetch failures both arrive this way.
  if (err?.cause) {
    const cause = err.cause as { name?: string; message?: string };
    console.error(
      `[ordence:error] cause: ${cause?.name ?? typeof err.cause}: ${cause?.message ?? String(err.cause)}`,
    );
  }

  /**
   * ══════════════════════════════════════════════════════════════════════
   * ⭐⭐⭐ WAVE 14 — AND THEN TO `captureError()`, WHICH HAD NO CALLERS
   * ══════════════════════════════════════════════════════════════════════
   * `lib/telemetry/report.ts` has existed since v0.12.0-alpha. It has a
   * scrubber with a positive allow-list, a fingerprint scheme for
   * grouping, a no-throw contract argued over forty lines, a table with
   * five CHECK constraints and an RLS policy, and — verified by grep
   * across the whole tree at v1.81.0-alpha — NOT ONE CALLER. Every
   * server-side exception in this product's history reached `console.error`
   * and Sentry, and `error_events` has only ever held rows posted by
   * browsers to `/api/telemetry`.
   *
   * 🔴 SO THE ONE TABLE BUILT TO ANSWER "IS THIS TENANT BROKEN OR IS THE
   * PRODUCT BROKEN" HAS NEVER SEEN A SERVER ERROR. That is why this line
   * is here and why it is here rather than anywhere else: `onRequestError`
   * is the only place Next.js hands over the real error object before it
   * becomes a digest, and it is called for every uncaught server error in
   * the application.
   *
   * ⚠️ `captureErrorSync`, NOT `await captureError`. This function is
   * declared `void` and is called by Next.js on the error path; awaiting
   * is not available and floating the promise without a `.catch()` is a
   * process crash since Node 15. `captureErrorSync` exists for exactly
   * this call shape and attaches the catch itself.
   *
   * ⚠️ THE TENANT IS NULL, AND THAT IS NOT AN OVERSIGHT. `onRequestError`
   * receives no session and cannot read headers — `headers()` is not
   * available outside a request scope here. So these rows land as
   * null-tenant rows: still grouped, still fingerprinted, still
   * searchable by route, but NOT attributable to a workspace. Attribution
   * needs one line inside `requireTenantContext()`; it is in
   * PATCH-REQUEST-B.md and it is the single highest-value line in that
   * document.
   */
  try {
    void import("@/lib/telemetry/report")
      .then(({ captureErrorSync }) => {
        captureErrorSync({
          error,
          severity: "error",
          source: "server",
          route: context?.routePath ?? request?.path ?? null,
          tenantId: null,
          userId: null,
          metadata: {
            component: "next",
            boundary: context?.routeType ?? "unknown",
            ...(err?.digest ? { digest: err.digest } : {}),
          },
        });
      })
      .catch(() => {
        /* Telemetry being unavailable must never mask the original error. */
      });
  } catch {
    /* Same, for a synchronous failure of the import itself. */
  }

  /**
   * ⭐ AND THEN TO SENTRY.
   *
   * ⚠️ AFTER the console lines, never instead of them, and never in a
   * way that can throw. If reporting an error itself throws, Next.js
   * loses the original — the one fault nobody could afford to lose is
   * the one this whole file exists to preserve.
   */
  if (SENTRY_ENABLED) {
    void import("@sentry/nextjs")
      .then((Sentry) =>
        /**
         * ⚠️ HEADERS ARE PASSED AS EMPTY, DELIBERATELY.
         *
         * `captureRequestError` wants a `RequestInfo` carrying headers.
         * This file's own policy — stated at the top since v0.32.0 — is
         * that request headers never leave the process: a Clerk session
         * cookie in a report is a stealable session. `scrubEvent` would
         * strip them anyway; handing over an empty object means they are
         * never in the event to begin with, which is one fewer thing
         * depending on the scrubber being correct.
         */
        Sentry.captureRequestError(
          error,
          { path: request?.path ?? "", method: request?.method ?? "", headers: {} },
          context as Parameters<typeof Sentry.captureRequestError>[2],
        ),
      )
      .catch(() => {
        /* Sentry being unavailable must never mask the original error. */
      });
  }
}
