/**
 * Ordence — Server error instrumentation
 * Version: v0.32.0-alpha
 *
 * ══════════════════════════════════════════════════════════════════════════
 * WHY THIS FILE EXISTS
 * ══════════════════════════════════════════════════════════════════════════
 * A server exception in a Cloudflare Worker reached the log looking like this:
 *
 *     "message": "    at worker.js:142989:19\n    at p2 (worker.js:139337:147)"
 *
 * Two minified frames and NOTHING ELSE. No message, no error type, no route,
 * no cause. The bundle those line numbers refer to is regenerated by every
 * build, so they cannot even be mapped after the fact unless you still have
 * the exact artefact that produced them — which nobody does.
 *
 * Next.js hands the real error object to `onRequestError` before it reduces
 * it to a digest for the browser. Reading it here is the difference between
 * "something failed on /dashboard" and "TenantAccessError: user not
 * provisioned, thrown from server/tenant-context.ts".
 *
 * ══════════════════════════════════════════════════════════════════════════
 * ⚠️ THIS RUNS ON A SERVER THAT HOLDS EVERY TENANT'S DATA
 * ══════════════════════════════════════════════════════════════════════════
 * The log is operator-visible, so what goes in it matters:
 *
 *   • The error's own message and stack — yes. That is the point.
 *   • The route and method — yes. An error with no route is a riddle.
 *   • Request headers, cookies, query strings, bodies — NEVER. A Clerk
 *     session cookie in a log line is a stealable session, and a query
 *     string routinely carries a customer's search terms.
 *
 * Nothing below reads anything from the request except its path and method.
 */

export async function register() {
  // Deliberately empty. This module exists for `onRequestError` alone;
  // Next.js requires `register` to be exported for the file to load at all.
}

type ErrorRequest = {
  path?: string;
  method?: string;
};

type ErrorContext = {
  routerKind?: string;
  routePath?: string;
  routeType?: string;
  renderSource?: string;
};

/**
 * Called by Next.js for every uncaught server-side error, BEFORE the digest
 * replaces it. One line, greppable, with the parts that identify the fault.
 */
export function onRequestError(
  error: unknown,
  request: ErrorRequest,
  context: ErrorContext,
): void {
  const err = error as { name?: string; message?: string; stack?: string; digest?: string; cause?: unknown };

  /*
   * ⚠️ `err.message` can be an empty string — that is exactly how the
   * original report arrived, and why it was undiagnosable. Say so explicitly
   * rather than logging an empty field that reads as "no error here".
   */
  const message =
    typeof err?.message === "string" && err.message.length > 0
      ? err.message
      : "(the thrown value carried no message)";

  const parts = [
    `[ordence:error] ${err?.name ?? "Error"}: ${message}`,
    `route=${context?.routePath ?? request?.path ?? "unknown"}`,
    `method=${request?.method ?? "?"}`,
    `type=${context?.routeType ?? "?"}`,
    `source=${context?.renderSource ?? "?"}`,
  ];

  if (err?.digest) parts.push(`digest=${err.digest}`);

  // The digest is what the BROWSER shows the user. Logging it beside the
  // real message is what lets somebody holding a screenshot of
  // "Digest: 817564861" find this line instead of guessing.
  console.error(parts.join(" | "));

  if (err?.stack) console.error(`[ordence:error] stack: ${err.stack}`);

  // A wrapped error hides the interesting half in `cause`. Postgres and
  // fetch failures both arrive this way.
  if (err?.cause) {
    const cause = err.cause as { name?: string; message?: string };
    console.error(
      `[ordence:error] cause: ${cause?.name ?? typeof err.cause}: ${cause?.message ?? String(err.cause)}`,
    );
  }
}
