/**
 * Ordence — Server error instrumentation
 * Version: v0.32.0-alpha
 *
 * ══════════════════════════════════════════════════════════════════════════
 * WHY THIS FILE EXISTS
 * ══════════════════════════════════════════════════════════════════════════
 * A server exception in a Cloudflare Worker reached the log looking like this:
 *
 *     "message": "    at worker.js:142989:19\n    at p2 (worker.js:139337:147)"
 *
 * Two minified frames and NOTHING ELSE. No message, no error type, no route,
 * no cause. The bundle those line numbers refer to is regenerated by every
 * build, so they cannot even be mapped after the fact unless you still have
 * the exact artefact that produced them — which nobody does.
 *
 * Next.js hands the real error object to `onRequestError` before it reduces
 * it to a digest for the browser. Reading it here is the difference between
 * "something failed on /dashboard" and "TenantAccessError: user not
 * provisioned, thrown from server/tenant-context.ts".
 *
 * ══════════════════════════════════════════════════════════════════════════
 * ⚠️ THIS RUNS ON A SERVER THAT HOLDS EVERY TENANT'S DATA
 * ══════════════════════════════════════════════════════════════════════════
 * The log is operator-visible, so what goes in it matters:
 *
 *   • The error's own message and stack — yes. That is the point.
 *   • The route and method — yes. An error with no route is a riddle.
 *   • Request headers, cookies, query strings, bodies — NEVER. A Clerk
 *     session cookie in a log line is a stealable session, and a query
 *     string routinely carries a customer's search terms.
 *
 * Nothing below reads anything from the request except its path and method.
 */

/**
 * ⭐ v0.95.0 — SENTRY INITIALISES HERE, and the console logging below
 *    STAYS. Two destinations, on purpose:
 *
 *   Railway logs — always on, no vendor, no quota, and the only thing
 *     that still works when Sentry itself is the outage.
 *   Sentry — searchable, grouped, alerting, and it names the commit.
 *
 * ⚠️ REMOVING THE `console.error` CALLS WHEN ADDING SENTRY IS THE
 *    OBVIOUS TIDY-UP AND IT IS WRONG. The 12 August outage was diagnosed
 *    from Railway logs. A monitoring vendor is one more dependency that
 *    can be down, misconfigured, or out of quota on the day you need it.
 */
export async function register() {
  if (!SENTRY_ENABLED) return;

  /**
   * ⚠️ DYNAMIC IMPORT, GATED ON THE RUNTIME. `@sentry/nextjs`'s Node
   * integrations pull in `async_hooks` and friends, which do not exist on
   * the edge runtime — a static top-level import breaks the edge bundle
   * at build time, not at run time, and the error names neither Sentry
   * nor the runtime.
   */
  if (process.env.NEXT_RUNTIME === "nodejs") {
    const Sentry = await import("@sentry/nextjs");
    Sentry.init(baseOptions());
  }

  if (process.env.NEXT_RUNTIME === "edge") {
    const Sentry = await import("@sentry/nextjs");
    Sentry.init(baseOptions());
  }
}

import { baseOptions, SENTRY_ENABLED } from "@/lib/observability/sentry-options";

type ErrorRequest = {
  path?: string;
  method?: string;
};

type ErrorContext = {
  routerKind?: string;
  routePath?: string;
  routeType?: string;
  renderSource?: string;
};

/**
 * Called by Next.js for every uncaught server-side error, BEFORE the digest
 * replaces it. One line, greppable, with the parts that identify the fault.
 */
export function onRequestError(
  error: unknown,
  request: ErrorRequest,
  context: ErrorContext,
): void {
  const err = error as { name?: string; message?: string; stack?: string; digest?: string; cause?: unknown };

  /*
   * ⚠️ `err.message` can be an empty string — that is exactly how the
   * original report arrived, and why it was undiagnosable. Say so explicitly
   * rather than logging an empty field that reads as "no error here".
   */
  const message =
    typeof err?.message === "string" && err.message.length > 0
      ? err.message
      : "(the thrown value carried no message)";

  const parts = [
    `[ordence:error] ${err?.name ?? "Error"}: ${message}`,
    `route=${context?.routePath ?? request?.path ?? "unknown"}`,
    `method=${request?.method ?? "?"}`,
    `type=${context?.routeType ?? "?"}`,
    `source=${context?.renderSource ?? "?"}`,
  ];

  if (err?.digest) parts.push(`digest=${err.digest}`);

  // The digest is what the BROWSER shows the user. Logging it beside the
  // real message is what lets somebody holding a screenshot of
  // "Digest: 817564861" find this line instead of guessing.
  console.error(parts.join(" | "));

  if (err?.stack) console.error(`[ordence:error] stack: ${err.stack}`);

  // A wrapped error hides the interesting half in `cause`. Postgres and
  // fetch failures both arrive this way.
  if (err?.cause) {
    const cause = err.cause as { name?: string; message?: string };
    console.error(
      `[ordence:error] cause: ${cause?.name ?? typeof err.cause}: ${cause?.message ?? String(err.cause)}`,
    );
  }

  /**
   * ⭐ AND THEN TO SENTRY.
   *
   * ⚠️ AFTER the console lines, never instead of them, and never in a
   * way that can throw. If reporting an error itself throws, Next.js
   * loses the original — the one fault nobody could afford to lose is
   * the one this whole file exists to preserve.
   */
  if (SENTRY_ENABLED) {
    void import("@sentry/nextjs")
      .then((Sentry) =>
        /**
         * ⚠️ HEADERS ARE PASSED AS EMPTY, DELIBERATELY.
         *
         * `captureRequestError` wants a `RequestInfo` carrying headers.
         * This file's own policy — stated at the top since v0.32.0 — is
         * that request headers never leave the process: a Clerk session
         * cookie in a report is a stealable session. `scrubEvent` would
         * strip them anyway; handing over an empty object means they are
         * never in the event to begin with, which is one fewer thing
         * depending on the scrubber being correct.
         */
        Sentry.captureRequestError(
          error,
          { path: request?.path ?? "", method: request?.method ?? "", headers: {} },
          context as Parameters<typeof Sentry.captureRequestError>[2],
        ),
      )
      .catch(() => {
        /* Sentry being unavailable must never mask the original error. */
      });
  }
}
