/**
 * Ordence — Cloudflare Worker entrypoint
 * Version: v0.21.0-alpha
 *
 * ══════════════════════════════════════════════════════════════════════════
 * WHY THIS FILE EXISTS AT ALL
 * ══════════════════════════════════════════════════════════════════════════
 * `opennextjs-cloudflare build` generates `.open-next/worker.js`, which
 * exports a `fetch` handler and nothing else. That is all Next.js needs.
 *
 * Ordence needs two more things a web request cannot provide:
 *
 *   scheduled()  the nightly sweep — the job BullMQ's `contract_expiry_scan`
 *                used to get from a QStash cron on Vercel.
 *   queue()      background jobs — what BullMQ's worker loop used to do.
 *
 * A Worker may export exactly one default object, so those handlers cannot be
 * bolted onto the generated file. This module re-exports the generated
 * `fetch` untouched and adds the other two beside it.
 *
 * ══════════════════════════════════════════════════════════════════════════
 * WHY THE HANDLERS CALL A ROUTE INSTEAD OF IMPORTING THE PROCESSORS
 * ══════════════════════════════════════════════════════════════════════════
 * The obvious implementation is `import { processJob } from "@/lib/queue/..."`
 * and call it here. It is the wrong one, twice over:
 *
 *   1. This file is bundled by Wrangler/esbuild, NOT by Next.js. It does not
 *      get the `@/*` path alias, the `server-only` resolution, the RSC
 *      conditions, or the environment inlining. Pulling half the application
 *      into a second, differently-configured bundle is how you end up with
 *      two versions of the same module and a bug nobody can reproduce.
 *
 *   2. `/api/workers` already contains the authentication, the tenant guard
 *      and the error reporting for exactly this work, and it is already
 *      tested. Re-implementing that here would mean two code paths into the
 *      same processors, one of them untested.
 *
 * So both handlers build a Request and hand it to the SAME fetch handler that
 * serves real traffic. One code path, one bundle, one set of tests.
 *
 * ⚠️ The call is authenticated with WORKER_API_SECRET. If that secret is not
 * set, `/api/workers` answers 503 and refuses to run — visible in
 * `npx wrangler tail`. It never silently succeeds.
 */

// @ts-ignore — generated by `opennextjs-cloudflare build`; absent before the
// first build, which is why this import is not type-checked.
import { default as openNextHandler } from "./.open-next/worker.js";

/** Milliseconds a single internal invocation may take before we give up. */
const INTERNAL_TIMEOUT_MS = 60_000;

/**
 * Build the URL the internal request is addressed to.
 *
 * The host matters: `middleware.ts` resolves a tenant from it. Using the root
 * domain makes `resolveTenantFromHost()` return `{kind:"root"}`, which is
 * correct — a queue message is not addressed to any one tenant's hostname,
 * and the tenant is carried inside the job payload where the processors
 * re-establish it under RLS.
 */
function internalUrl(env: CloudflareEnv, path: string): string {
  const host = env.NEXT_PUBLIC_ROOT_DOMAIN || "app.ordence.com";
  return `https://${host}${path}`;
}

async function callWorkersRoute(
  env: CloudflareEnv,
  ctx: ExecutionContext,
  payload: Record<string, unknown>,
): Promise<{ ok: boolean; status: number; body: string }> {
  const secret = env.WORKER_API_SECRET;

  if (!secret) {
    // Fail loud. A background system that quietly does nothing is worse than
    // one that is obviously broken.
    console.error(
      "[worker] WORKER_API_SECRET is not set — background work cannot be " +
        "authenticated and will not run. Set it with: wrangler secret put WORKER_API_SECRET",
    );
    return { ok: false, status: 503, body: "WORKER_API_SECRET not set" };
  }

  const request = new Request(internalUrl(env, "/api/workers"), {
    method: "POST",
    headers: {
      "content-type": "application/json",
      authorization: `Bearer ${secret}`,
      // Marks the call as machine-originated for log filtering. Carries no
      // authority of its own — the bearer secret above is the credential.
      "x-ordence-invoker": "cloudflare-worker",
    },
    body: JSON.stringify(payload),
  });

  const timeout = new Promise<Response>((_, reject) =>
    setTimeout(() => reject(new Error("internal request timed out")), INTERNAL_TIMEOUT_MS),
  );

  try {
    const response = (await Promise.race([
      openNextHandler.fetch(request, env, ctx),
      timeout,
    ])) as Response;
    const body = await response.text();
    return { ok: response.ok, status: response.status, body };
  } catch (err) {
    const message = err instanceof Error ? err.message : "unknown error";
    console.error("[worker] internal call failed:", message);
    return { ok: false, status: 500, body: message };
  }
}

export default {
  /** Ordinary HTTP traffic — untouched, straight to Next.js. */
  fetch: openNextHandler.fetch,

  /**
   * CRON — configured in wrangler.jsonc under `triggers.crons`.
   *
   * Runs the maintenance sweep: enqueue a contract-expiry scan for every
   * active tenant. `event.cron` is passed through so `/api/workers` can log
   * which schedule fired when more than one exists.
   */
  async scheduled(event: ScheduledController, env: CloudflareEnv, ctx: ExecutionContext) {
    const result = await callWorkersRoute(env, ctx, { mode: "cron", cron: event.cron });
    if (!result.ok) {
      console.error(`[worker] cron sweep failed (${result.status}):`, result.body.slice(0, 500));
      // Throwing marks the cron invocation as failed in the Cloudflare
      // dashboard. Swallowing it would show a green tick for work that
      // did not happen.
      throw new Error(`Cron sweep failed with ${result.status}`);
    }
    console.log("[worker] cron sweep ok:", result.body.slice(0, 500));
  },

  /**
   * QUEUE CONSUMER — bound in wrangler.jsonc under `queues.consumers`.
   *
   * ⚠️ ack/retry IS THE WHOLE POINT OF THIS FUNCTION.
   *
   * A message is `ack()`ed only when the processor reported success. Anything
   * else is `retry()`ed, so Cloudflare re-delivers it with backoff and
   * eventually parks it on the dead-letter queue. An unconditional ack would
   * turn every transient database blip into permanent, silent data loss —
   * precisely the failure mode BullMQ's retry policy existed to prevent.
   */
  async queue(batch: MessageBatch<unknown>, env: CloudflareEnv, ctx: ExecutionContext) {
    for (const message of batch.messages) {
      const result = await callWorkersRoute(env, ctx, { job: message.body });

      if (!result.ok) {
        console.error(
          `[worker] job ${message.id} failed (${result.status}):`,
          result.body.slice(0, 500),
        );
        message.retry();
        continue;
      }

      // A 200 does not by itself mean the job succeeded — the route reports
      // per-job outcome in the body. Check it before acking.
      let processedOk = false;
      try {
        processedOk = (JSON.parse(result.body) as { ok?: boolean }).ok === true;
      } catch {
        processedOk = false;
      }

      if (processedOk) {
        message.ack();
      } else {
        console.error(`[worker] job ${message.id} reported failure:`, result.body.slice(0, 500));
        message.retry();
      }
    }
  },
} satisfies ExportedHandler<CloudflareEnv>;
