/**
 * Ordence — Cloudflare binding and secret declarations
 *
 * ══════════════════════════════════════════════════════════════════════════
 * WHY THIS FILE IS SEPARATE FROM worker-configuration.d.ts
 * ══════════════════════════════════════════════════════════════════════════
 * `worker-configuration.d.ts` is GENERATED by `npm run cf:typegen` and is
 * overwritten every time wrangler.jsonc changes. Anything hand-written there
 * is lost. Two kinds of declaration therefore live here instead:
 *
 *   1. SECRETS. `wrangler secret put` values never appear in wrangler.jsonc,
 *      so the generator cannot know about them. Every secret the app reads
 *      is declared below — this list doubles as the checklist in
 *      docs/CLOUDFLARE-DEPLOY.md.
 *
 *   2. OPTIONAL BINDINGS. `JOB_QUEUE` is commented out in wrangler.jsonc for
 *      the first deploy, so the generator emits nothing for it. It is
 *      declared optional here, which is also the truth at runtime: the code
 *      must cope with its absence, and the `?` makes TypeScript insist.
 *
 * Global `interface` declarations merge, so these are additive to whatever
 * the generator produced.
 */

interface CloudflareEnv {
  /* ---------------- OPTIONAL BINDINGS ---------------- */

  /**
   * Cloudflare Queues producer. Absent until the queue is created and
   * `queues.producers` is uncommented in wrangler.jsonc.
   *
   * ⚠️ Optional on purpose. `lib/queue/jobs.ts` branches on its presence and
   * either runs the job inline or refuses — it never pretends to enqueue.
   */
  JOB_QUEUE?: Queue<unknown>;

  /* ---------------- SECRETS (wrangler secret put) ---------------- */

  /** Neon pooled connection string. Missing → every page 500s. REQUIRED. */
  DATABASE_URL: string;

  /** Clerk backend key (sk_live_…). Missing → nobody can sign in. REQUIRED. */
  CLERK_SECRET_KEY: string;

  /** Clerk webhook signing secret. Missing → tenants are not auto-provisioned. */
  CLERK_WEBHOOK_SIGNING_SECRET?: string;

  /**
   * HMAC key for upload tickets — see lib/storage/upload-ticket.ts.
   * Missing → /api/upload answers 503 and file uploads are refused with a
   * message saying exactly that. Nothing else degrades.
   */
  UPLOAD_TICKET_SECRET?: string;

  /**
   * Shared secret the cron/queue handlers present to /api/workers.
   * Missing → background work is refused with 503 and logged. REQUIRED if
   * you want the nightly sweep or the queue to do anything.
   */
  WORKER_API_SECRET?: string;

  /** Legacy Vercel-cron secret. Unused on Cloudflare; kept for parity. */
  CRON_SECRET?: string;

  /** Upstash REST cache + rate limiting. Missing → rate limits fail open. */
  UPSTASH_REDIS_REST_URL?: string;
  UPSTASH_REDIS_REST_TOKEN?: string;

  /** Upstash QStash — only used if something outside Cloudflare pokes /api/workers. */
  QSTASH_CURRENT_SIGNING_KEY?: string;
  QSTASH_NEXT_SIGNING_KEY?: string;

  /** Resend transactional email. Missing → emails are skipped, not queued. */
  RESEND_API_KEY?: string;
  RESEND_FROM_EMAIL?: string;
  FINANCE_ALERT_EMAILS?: string;

  /** Payment rails. Missing → checkout refuses cleanly; the app still runs. */
  RAZORPAY_KEY_ID?: string;
  RAZORPAY_KEY_SECRET?: string;
  RAZORPAY_WEBHOOK_SECRET?: string;
  STRIPE_SECRET_KEY?: string;
  STRIPE_WEBHOOK_SECRET?: string;

  /** Platform staff allowlist, comma-separated emails. */
  PLATFORM_ADMIN_EMAILS?: string;

  /** Tax identity printed on invoices we issue. */
  PLATFORM_GST_STATE_CODE?: string;
  PLATFORM_GSTIN?: string;
  PLATFORM_INVOICE_PREFIX?: string;

  /** Deploy identity stamped on telemetry rows. */
  TELEMETRY_RELEASE?: string;
  TELEMETRY_DISABLED?: string;
}
