-- ============================================================================
-- Ordence — Phase 34: ⭐ GSTR-2B RECONCILIATION
-- Version: v0.34.0-alpha
--
-- Run AFTER `ALL-IN-ONE-SETUP.sql`, `0017_change_log.sql`,
-- `0021_phase32_gst.sql` and `0023_phase33_purchases.sql`. It depends on
-- `set_updated_at()`, `app_current_tenant_id()`, `record_change()`, and on the
-- Phase 32/33 tables `gst_registrations`, `vendors` and `purchase_invoices`.
--
-- Safe to run before `drizzle-kit push`: Section 1 creates its own types and
-- tables idempotently. Safe to re-run: every statement is guarded.
--
-- Contents:
--   1.  Enums and tables
--   2.  ⭐ ONE MATCH PER DOCUMENT — the index that makes the summary add up
--   3.  Row-level security
--   4.  ⭐ Composite foreign keys — the hole RLS does NOT close
--   5.  ⭐ THE RAW STATEMENT IS IMMUTABLE — a parse bug must not destroy it
--   6.  ⭐⭐ A FILED PERIOD FREEZES
--   7.  ⭐ THE SUMMARY MUST AGREE WITH ITS OWN MATCHES — deferred, at commit
--   8.  ⭐ A MATCH MAY NOT CROSS A STATEMENT OR A REGISTRATION
--   9.  Support sessions may not delete tax evidence
--   9b. updated_at, and the change log
--   10. Grants
--   11. Verification
--
-- ============================================================================
-- ⚠️  READ THIS BEFORE THE SQL
-- ============================================================================
-- Section 16(2)(aa) of the CGST Act, in force from 1 January 2022, makes the
-- SUPPLIER'S FILING a precondition of our input tax credit. Rule 36(4) removed
-- the last provisional cushion in the same year. So:
--
--     A bill we hold, have paid, and have a perfect tax invoice for carries NO
--     input tax credit if the supplier did not file their GSTR-1.
--
-- Nothing in our own records shows this. The bill looks identical to one that
-- is fine. The only way to know is to compare our purchase register against a
-- document generated by somebody else, every month, invoice by invoice.
--
-- Three failure modes are worth enforcing in the database, because all three
-- are silent and all three are profitable in the short run:
--
--   • Section 5 — THE RAW FILE IS DESTROYED. A parse bug is discovered by
--     definition after the parse, often a year later at a notice, and by then
--     the portal may no longer serve that month. An import that overwrote the
--     raw document with its own interpretation would leave nothing to re-read.
--
--   • Section 6 — A FILED PERIOD IS SILENTLY REWRITTEN. The portal REGENERATES
--     GSTR-2B whenever a supplier files late, so re-importing July in November
--     is ordinary work. If July's reconciliation moved, the working paper for
--     a GSTR-3B the Government holds a copy of would no longer describe what
--     was filed, and nothing anywhere would say it had changed.
--
--   • Sections 1, 2 and 7 — THE SUMMARY STOPS ADDING UP. If one invoice is
--     matched twice, or dropped, the totals still look like totals. Every row
--     on every screen is correct. The only symptom is that "in books, not in
--     2B" is SMALLER than it should be — which reads as good news, fewer
--     suppliers to chase, more credit available. The credit is then claimed on
--     an invoice the supplier never filed.
--
-- And one rule about people rather than data:
--
--   • Section 1 — NOTHING BELOW AN EXACT MATCH MAY BE ACCEPTED WITHOUT A NAMED
--     HUMAN. "Auto-accept everything above 90%" is the most requested feature
--     in every reconciliation product ever built, and it produces a year of
--     matches nobody looked at, discovered at the one assessment where the
--     answer to "who decided this" has to be a person.
--
-- Money is bigint paise. Rates are integer basis points.
-- ============================================================================


-- ############################################################################
-- SECTION 1 — ENUMS AND TABLES
-- ############################################################################
--
-- `drizzle-kit push` creates these from `db/schema/gstr2b.ts`. They are
-- restated here because a file that can only run second is a file that fails on
-- a fresh database.

DO $$
BEGIN
  -- The portal's own section names. ⚠️ NOT interchangeable: a `b2ba` row
  -- SUPERSEDES an earlier invoice rather than adding to it, and an `impg` row
  -- is a bill of entry with no supplier GSTIN at all.
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'gstr2b_section') THEN
    CREATE TYPE gstr2b_section AS ENUM
      ('b2b','b2ba','cdnr','cdnra','isd','isda','impg','impgsez');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'gstr2b_source_format') THEN
    CREATE TYPE gstr2b_source_format AS ENUM ('portal_json','portal_excel','csv');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'gstr2b_parse_status') THEN
    CREATE TYPE gstr2b_parse_status AS ENUM ('pending','parsed','failed');
  END IF;

  -- ⚠️ The PORTAL'S opinion, which is not the same question as Section 17(5).
  -- A row can be available here and still be BLOCKED by our own determination.
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'gstr2b_itc_availability') THEN
    CREATE TYPE gstr2b_itc_availability AS ENUM ('available','not_available');
  END IF;

  -- ⭐ THE SEVEN OUTCOMES. See db/schema/gstr2b.ts for why there are seven
  -- rather than "matched / unmatched": the four unmatched kinds need four
  -- different people to do four different things.
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'gstr2b_match_category') THEN
    CREATE TYPE gstr2b_match_category AS ENUM
      ('exact','probable','number_mismatch','in_2b_not_in_books',
       'in_books_not_in_2b','amended','cancelled');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'gstr2b_match_confidence') THEN
    CREATE TYPE gstr2b_match_confidence AS ENUM ('exact','high','medium','low','none');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'gstr2b_match_action') THEN
    CREATE TYPE gstr2b_match_action AS ENUM ('pending','accepted','rejected','deferred');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'gstr2b_reconciliation_status') THEN
    CREATE TYPE gstr2b_reconciliation_status AS ENUM
      ('draft','in_progress','reconciled','filed');
  END IF;
END
$$;


-- ⭐ THE EVIDENCE. One row per downloaded statement, stored whole.
CREATE TABLE IF NOT EXISTS gstr2b_documents (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id         uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  registration_id   uuid,
  gstin             varchar(15) NOT NULL,
  return_period     varchar(7)  NOT NULL,
  source_format     gstr2b_source_format NOT NULL,
  file_name         varchar(255),
  file_hash         varchar(64) NOT NULL,
  file_byte_size    bigint,
  generated_on      date,
  portal_version    varchar(16),
  raw_document      jsonb NOT NULL,
  parse_status      gstr2b_parse_status NOT NULL DEFAULT 'pending',
  parse_error       text,
  parse_issues      jsonb NOT NULL DEFAULT '[]'::jsonb,
  row_count         integer NOT NULL DEFAULT 0,
  parsed_at         timestamptz,
  imported_by       uuid,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT gstr2b_documents_period_shape
    CHECK (return_period ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'),
  -- ⚠️ A failed parse must say why, and a successful one must not carry a
  -- stale reason — that is how a fixed import gets re-investigated.
  CONSTRAINT gstr2b_documents_failure_explained
    CHECK ((parse_status = 'failed') = (parse_error IS NOT NULL)),
  -- ⭐ The evidence may not be blank.
  CONSTRAINT gstr2b_documents_raw_present
    CHECK (jsonb_typeof(raw_document) IS NOT NULL AND raw_document <> 'null'::jsonb),
  CONSTRAINT gstr2b_documents_hash_shape
    CHECK (file_hash ~ '^[0-9a-f]{64}$'),
  CONSTRAINT gstr2b_documents_count_sane CHECK (row_count >= 0)
);


-- The parsed rows. ⚠️ DERIVED AND REBUILDABLE — the raw document is not.
CREATE TABLE IF NOT EXISTS gstr2b_rows (
  id                       uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id                uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  document_id              uuid NOT NULL,
  section                  gstr2b_section NOT NULL,
  supplier_gstin           varchar(15),
  supplier_legal_name      varchar(255),
  supplier_trade_name      varchar(255),
  invoice_number           varchar(64) NOT NULL,
  normalised_number        varchar(64) NOT NULL,
  invoice_date             date NOT NULL,
  document_type            varchar(12),
  document_value_minor     bigint NOT NULL DEFAULT 0,
  taxable_value_minor      bigint NOT NULL DEFAULT 0,
  cgst_minor               bigint NOT NULL DEFAULT 0,
  sgst_minor               bigint NOT NULL DEFAULT 0,
  igst_minor               bigint NOT NULL DEFAULT 0,
  cess_minor               bigint NOT NULL DEFAULT 0,
  place_of_supply_code     varchar(2),
  is_reverse_charge        boolean NOT NULL DEFAULT false,
  itc_available            gstr2b_itc_availability NOT NULL DEFAULT 'available',
  itc_unavailable_reason   varchar(120),
  supplier_filing_period   varchar(7),
  supplier_filing_date     date,
  is_amendment             boolean NOT NULL DEFAULT false,
  original_invoice_number  varchar(64),
  original_invoice_date    date,
  is_cancelled             boolean NOT NULL DEFAULT false,
  rate_breakup             jsonb NOT NULL DEFAULT '[]'::jsonb,
  source_ref               varchar(160),
  created_at               timestamptz NOT NULL DEFAULT now(),
  updated_at               timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT gstr2b_rows_non_negative
    CHECK (document_value_minor >= 0 AND taxable_value_minor >= 0
           AND cgst_minor >= 0 AND sgst_minor >= 0
           AND igst_minor >= 0 AND cess_minor >= 0),
  -- ⚠️ A row carrying IGST *and* the CGST/SGST pair means the columns were
  -- mapped wrongly out of a spreadsheet. That is the single most common CSV
  -- import failure and it silently doubles the credit for a whole month.
  CONSTRAINT gstr2b_rows_heads_exclusive
    CHECK (NOT (igst_minor > 0 AND (cgst_minor > 0 OR sgst_minor > 0))),
  -- ⭐ An amendment SUPERSEDES the original; without the original's number the
  -- credit would be counted twice.
  CONSTRAINT gstr2b_rows_amendment_names_original
    CHECK (NOT is_amendment OR original_invoice_number IS NOT NULL),
  -- ⚠️ Only an import of goods legitimately has no supplier GSTIN — the
  -- counterparty is Customs. Anything else without one would sit in the
  -- worklist forever as an unmatched supplier who does not exist.
  CONSTRAINT gstr2b_rows_gstin_presence
    CHECK (supplier_gstin IS NOT NULL OR section = 'impg'),
  CONSTRAINT gstr2b_rows_filing_period_shape
    CHECK (supplier_filing_period IS NULL
           OR supplier_filing_period ~ '^[0-9]{4}-(0[1-9]|1[0-2])$')
);


-- ⭐ THE PERIOD'S RECONCILIATION, ITS TOTALS, AND ITS FREEZE.
CREATE TABLE IF NOT EXISTS gstr2b_reconciliations (
  id                          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id                   uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  registration_id             uuid,
  gstin                       varchar(15) NOT NULL,
  tax_period                  varchar(7)  NOT NULL,
  document_id                 uuid,
  status                      gstr2b_reconciliation_status NOT NULL DEFAULT 'draft',

  books_invoice_count         integer NOT NULL DEFAULT 0,
  books_taxable_minor         bigint  NOT NULL DEFAULT 0,
  books_tax_minor             bigint  NOT NULL DEFAULT 0,
  books_itc_eligible_minor    bigint  NOT NULL DEFAULT 0,

  twob_row_count              integer NOT NULL DEFAULT 0,
  twob_taxable_minor          bigint  NOT NULL DEFAULT 0,
  twob_tax_minor              bigint  NOT NULL DEFAULT 0,
  twob_itc_available_minor    bigint  NOT NULL DEFAULT 0,

  matched_count               integer NOT NULL DEFAULT 0,
  matched_books_tax_minor     bigint  NOT NULL DEFAULT 0,
  matched_twob_tax_minor      bigint  NOT NULL DEFAULT 0,

  in_books_not_in_2b_count    integer NOT NULL DEFAULT 0,
  in_books_not_in_2b_tax_minor bigint NOT NULL DEFAULT 0,
  itc_at_risk_minor           bigint  NOT NULL DEFAULT 0,

  in_2b_not_in_books_count    integer NOT NULL DEFAULT 0,
  in_2b_not_in_books_tax_minor bigint NOT NULL DEFAULT 0,

  itc_claimed_minor           bigint  NOT NULL DEFAULT 0,

  engine_version              varchar(16) NOT NULL DEFAULT '1',
  last_run_at                 timestamptz,

  filed_at                    timestamptz,
  filed_by                    uuid,
  filed_reference             varchar(64),

  notes                       text,
  created_by                  uuid,
  created_at                  timestamptz NOT NULL DEFAULT now(),
  updated_at                  timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT gstr2b_reconciliations_period_shape
    CHECK (tax_period ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'),
  CONSTRAINT gstr2b_reconciliations_non_negative
    CHECK (books_invoice_count >= 0 AND books_taxable_minor >= 0
           AND books_tax_minor >= 0 AND books_itc_eligible_minor >= 0
           AND twob_row_count >= 0 AND twob_taxable_minor >= 0
           AND twob_tax_minor >= 0 AND twob_itc_available_minor >= 0
           AND matched_count >= 0 AND matched_books_tax_minor >= 0
           AND matched_twob_tax_minor >= 0
           AND in_books_not_in_2b_count >= 0 AND in_books_not_in_2b_tax_minor >= 0
           AND in_2b_not_in_books_count >= 0 AND in_2b_not_in_books_tax_minor >= 0
           AND itc_at_risk_minor >= 0 AND itc_claimed_minor >= 0),

  -- ⭐⭐ THE TWO IDENTITIES THE WHOLE SUMMARY RESTS ON.
  --
  --     books tax = matched (books side) + in books, not in 2B
  --     2B tax    = matched (2B side)    + in 2B, not in books
  --
  -- ⚠️ IF EITHER FAILS, AN INVOICE IS NOT IN EXACTLY ONE BUCKET — counted
  -- twice, or dropped. A dropped invoice makes "in books, not in 2B" SMALLER
  -- than it should be, which reads as good news: fewer suppliers to chase.
  -- The credit is then claimed under Section 16(2)(aa) with nothing behind it.
  CONSTRAINT gstr2b_reconciliations_books_reconcile
    CHECK (books_tax_minor = matched_books_tax_minor + in_books_not_in_2b_tax_minor),
  CONSTRAINT gstr2b_reconciliations_twob_reconcile
    CHECK (twob_tax_minor = matched_twob_tax_minor + in_2b_not_in_books_tax_minor),

  -- ⭐ A filed reconciliation names when it was filed, and vice versa.
  CONSTRAINT gstr2b_reconciliations_filed_consistent
    CHECK ((status = 'filed') = (filed_at IS NOT NULL))
);


-- ⭐⭐ THE MATCH. What matched, why, and who said so.
CREATE TABLE IF NOT EXISTS gstr2b_matches (
  id                    uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id             uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  reconciliation_id     uuid NOT NULL,
  gstr2b_row_id         uuid,
  purchase_invoice_id   uuid,
  vendor_id             uuid,
  supplier_gstin        varchar(15),

  match_category        gstr2b_match_category NOT NULL,
  confidence            gstr2b_match_confidence NOT NULL,
  match_score           integer NOT NULL DEFAULT 0,

  matched_on            jsonb NOT NULL DEFAULT '[]'::jsonb,
  differences           jsonb NOT NULL DEFAULT '[]'::jsonb,

  taxable_delta_minor   bigint NOT NULL DEFAULT 0,
  tax_delta_minor       bigint NOT NULL DEFAULT 0,
  itc_at_risk_minor     bigint NOT NULL DEFAULT 0,
  ambiguous_candidates  integer NOT NULL DEFAULT 0,

  explanation           text NOT NULL,
  engine_version        varchar(16) NOT NULL DEFAULT '1',

  action                gstr2b_match_action NOT NULL DEFAULT 'pending',
  action_reason         text,
  action_by             uuid,
  action_at             timestamptz,

  created_at            timestamptz NOT NULL DEFAULT now(),
  updated_at            timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT gstr2b_matches_has_a_side
    CHECK (gstr2b_row_id IS NOT NULL OR purchase_invoice_id IS NOT NULL),

  -- ⚠️ The category and the pointers must agree. An `exact` match with no
  -- purchase invoice is a contradiction, and it is the shape a
  -- partially-written re-run leaves behind.
  CONSTRAINT gstr2b_matches_category_matches_sides
    CHECK (CASE match_category
             WHEN 'in_2b_not_in_books'
               THEN gstr2b_row_id IS NOT NULL AND purchase_invoice_id IS NULL
             WHEN 'in_books_not_in_2b'
               THEN purchase_invoice_id IS NOT NULL AND gstr2b_row_id IS NULL
             ELSE gstr2b_row_id IS NOT NULL AND purchase_invoice_id IS NOT NULL
           END),

  -- ⭐⭐ NOTHING BELOW AN EXACT MATCH MAY BE ACCEPTED WITHOUT A NAMED HUMAN.
  --
  -- ⚠️ IN THE DATABASE BECAUSE THE ENGINE IS ONE WRITE PATH OF SEVERAL. A
  -- bulk-accept button, an import script and a future API route are the
  -- others, and "accept everything above 90%" is the most requested feature in
  -- every reconciliation product ever built. It is also the one that produces
  -- a year of matches nobody looked at, discovered at the one assessment where
  -- the answer to "who decided this" has to be a person.
  CONSTRAINT gstr2b_matches_no_silent_auto_accept
    CHECK (NOT (action = 'accepted'
                AND match_category <> 'exact'
                AND action_by IS NULL)),

  -- ⚠️ A rejection or a deferral with no reason explains nothing. Three months
  -- later "why is this still open" has no answer, and the exception is
  -- re-investigated from scratch every month until somebody accepts it to make
  -- it go away.
  CONSTRAINT gstr2b_matches_refusal_has_reason
    CHECK (action NOT IN ('rejected','deferred')
           OR (action_by IS NOT NULL AND action_reason IS NOT NULL)),

  CONSTRAINT gstr2b_matches_action_timed
    CHECK ((action = 'pending') = (action_at IS NULL)),
  CONSTRAINT gstr2b_matches_score_range
    CHECK (match_score >= 0 AND match_score <= 100),
  CONSTRAINT gstr2b_matches_non_negative
    CHECK (itc_at_risk_minor >= 0 AND ambiguous_candidates >= 0),

  -- ⚠️ An `exact` match with a delta is not an exact match. The LABEL is what
  -- a reviewer trusts and the DELTA is what an officer finds.
  CONSTRAINT gstr2b_matches_exact_has_no_delta
    CHECK (match_category <> 'exact'
           OR (taxable_delta_minor = 0 AND tax_delta_minor = 0
               AND confidence = 'exact'))
);


-- ---------------------------------------------------------------------------
-- 1b. Indexes
-- ---------------------------------------------------------------------------

-- ⭐ The same bytes imported twice are ONE document, not two. The file hash is
-- part of the key because 2B for a period is REGENERATED when a supplier files
-- late: July downloaded in August and July downloaded in November are
-- different documents describing the same month, and both are evidence.
CREATE UNIQUE INDEX IF NOT EXISTS gstr2b_documents_identity_unique
  ON gstr2b_documents (tenant_id, gstin, return_period, file_hash);
CREATE INDEX IF NOT EXISTS gstr2b_documents_period_idx
  ON gstr2b_documents (tenant_id, gstin, return_period);
CREATE INDEX IF NOT EXISTS gstr2b_documents_status_idx
  ON gstr2b_documents (tenant_id, parse_status);

CREATE INDEX IF NOT EXISTS gstr2b_rows_document_idx
  ON gstr2b_rows (tenant_id, document_id);
CREATE INDEX IF NOT EXISTS gstr2b_rows_section_idx
  ON gstr2b_rows (tenant_id, document_id, section);
-- ⭐ The candidate lookup the workbench searches on.
CREATE INDEX IF NOT EXISTS gstr2b_rows_match_idx
  ON gstr2b_rows (tenant_id, supplier_gstin, normalised_number);
CREATE INDEX IF NOT EXISTS gstr2b_rows_supplier_idx
  ON gstr2b_rows (tenant_id, supplier_gstin, invoice_date);

-- ⭐ ONE RECONCILIATION PER GSTIN PER PERIOD. This is the freeze key: the
-- trigger in Section 6 looks a period up by exactly these three columns.
CREATE UNIQUE INDEX IF NOT EXISTS gstr2b_reconciliations_period_unique
  ON gstr2b_reconciliations (tenant_id, gstin, tax_period);
CREATE INDEX IF NOT EXISTS gstr2b_reconciliations_status_idx
  ON gstr2b_reconciliations (tenant_id, status);
CREATE INDEX IF NOT EXISTS gstr2b_reconciliations_registration_idx
  ON gstr2b_reconciliations (tenant_id, registration_id, tax_period);

CREATE INDEX IF NOT EXISTS gstr2b_matches_worklist_idx
  ON gstr2b_matches (tenant_id, reconciliation_id, match_category, action);
CREATE INDEX IF NOT EXISTS gstr2b_matches_supplier_idx
  ON gstr2b_matches (tenant_id, supplier_gstin, match_category);
CREATE INDEX IF NOT EXISTS gstr2b_matches_vendor_idx
  ON gstr2b_matches (tenant_id, vendor_id);
CREATE INDEX IF NOT EXISTS gstr2b_matches_invoice_idx
  ON gstr2b_matches (tenant_id, purchase_invoice_id);


-- ############################################################################
-- SECTION 2 — ⭐ ONE MATCH PER DOCUMENT
-- ############################################################################
--
-- THE TWO INDEXES THAT MAKE THE SUMMARY ADD UP.
--
--     A re-run of the engine appends instead of replacing. One 2B row is now
--     matched to two purchase invoices. Both match rows look perfectly
--     ordinary — same supplier, same number, sensible confidence. The
--     "matched" total exceeds the books total by one invoice, "in books, not
--     in 2B" shrinks by one, and the reconciliation reports one fewer supplier
--     to chase.
--
-- Nothing on any screen looks wrong. The identity CHECKs on
-- `gstr2b_reconciliations` would catch the totals at COMMIT — which is the
-- right failure — but these catch it at the row that caused it, which is the
-- one a person can act on.
--
-- ⚠️ PARTIAL, ON `IS NOT NULL`. A one-sided exception has a NULL on the other
-- side, and PostgreSQL treats NULLs as distinct in a unique index — so without
-- the WHERE clause the index would be built over rows it cannot constrain and
-- would say nothing about the ones it can.

CREATE UNIQUE INDEX IF NOT EXISTS gstr2b_matches_one_per_2b_row
  ON gstr2b_matches (tenant_id, reconciliation_id, gstr2b_row_id)
  WHERE gstr2b_row_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS gstr2b_matches_one_per_invoice
  ON gstr2b_matches (tenant_id, reconciliation_id, purchase_invoice_id)
  WHERE purchase_invoice_id IS NOT NULL;


-- ############################################################################
-- SECTION 3 — ROW-LEVEL SECURITY
-- ############################################################################
--
-- ENABLE turns policies on. FORCE applies them to the table OWNER too, which
-- is the half everybody forgets: without it the role that created the table
-- reads everything and the policies look like they are working.
--
-- ⚠️ NO `app_is_platform_scope()` ON ANY POLICY HERE, AND THE ARGUMENT IS
-- STRONGER THAN FOR PHASE 33. A tenant's GSTR-2B is a list, issued by the
-- Government, of every supplier who invoiced them in a month, with amounts. It
-- is a more complete and more reliable supplier list than their own purchase
-- ledger, because it was compiled by somebody with no incentive to leave
-- anything out. Platform staff have no business reading it.

ALTER TABLE gstr2b_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE gstr2b_documents FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS gstr2b_documents_tenant_isolation ON gstr2b_documents;
CREATE POLICY gstr2b_documents_tenant_isolation ON gstr2b_documents
  USING (tenant_id = app_current_tenant_id())
  WITH CHECK (tenant_id = app_current_tenant_id());

ALTER TABLE gstr2b_rows ENABLE ROW LEVEL SECURITY;
ALTER TABLE gstr2b_rows FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS gstr2b_rows_tenant_isolation ON gstr2b_rows;
CREATE POLICY gstr2b_rows_tenant_isolation ON gstr2b_rows
  USING (tenant_id = app_current_tenant_id())
  WITH CHECK (tenant_id = app_current_tenant_id());

ALTER TABLE gstr2b_reconciliations ENABLE ROW LEVEL SECURITY;
ALTER TABLE gstr2b_reconciliations FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS gstr2b_reconciliations_tenant_isolation ON gstr2b_reconciliations;
CREATE POLICY gstr2b_reconciliations_tenant_isolation ON gstr2b_reconciliations
  USING (tenant_id = app_current_tenant_id())
  WITH CHECK (tenant_id = app_current_tenant_id());

ALTER TABLE gstr2b_matches ENABLE ROW LEVEL SECURITY;
ALTER TABLE gstr2b_matches FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS gstr2b_matches_tenant_isolation ON gstr2b_matches;
CREATE POLICY gstr2b_matches_tenant_isolation ON gstr2b_matches
  USING (tenant_id = app_current_tenant_id())
  WITH CHECK (tenant_id = app_current_tenant_id());


-- ############################################################################
-- SECTION 4 — ⭐ COMPOSITE FOREIGN KEYS
-- ############################################################################
--
-- ⚠️ FOREIGN-KEY CHECKS RUN AS THE SYSTEM AND IGNORE ROW-LEVEL SECURITY. That
-- is documented PostgreSQL behaviour and it is why every pointer in this phase
-- is a COMPOSITE key on (col, tenant_id).
--
-- The shape of the hole, concretely for this phase:
--
--     Tenant A inserts a match with
--         tenant_id           = A                            ← passes WITH CHECK
--         purchase_invoice_id = <an invoice owned by B>       ← passes a single FK
--
--     A's reconciliation now claims that B's purchase invoice was matched to a
--     supplier declaration. Worse, it is an EXISTENCE ORACLE for the most
--     commercially sensitive identifier in the product: guessing invoice ids
--     until one is accepted enumerates another developer's purchase ledger,
--     and the "matched" flag confirms each hit.

CREATE UNIQUE INDEX IF NOT EXISTS gstr2b_documents_id_tenant_key
  ON gstr2b_documents (id, tenant_id);
CREATE UNIQUE INDEX IF NOT EXISTS gstr2b_rows_id_tenant_key
  ON gstr2b_rows (id, tenant_id);
CREATE UNIQUE INDEX IF NOT EXISTS gstr2b_reconciliations_id_tenant_key
  ON gstr2b_reconciliations (id, tenant_id);

-- Parents in earlier phases. Created idempotently so this file does not depend
-- on the order the SQL directory is applied in.
CREATE UNIQUE INDEX IF NOT EXISTS users_id_tenant_key
  ON users (id, tenant_id);
CREATE UNIQUE INDEX IF NOT EXISTS gst_registrations_id_tenant_key
  ON gst_registrations (id, tenant_id);
CREATE UNIQUE INDEX IF NOT EXISTS vendors_id_tenant_key
  ON vendors (id, tenant_id);
CREATE UNIQUE INDEX IF NOT EXISTS purchase_invoices_id_tenant_key
  ON purchase_invoices (id, tenant_id);

DO $$
BEGIN
  /* --- gstr2b_documents ------------------------------------------ */
  IF NOT EXISTS (SELECT 1 FROM pg_constraint
                  WHERE conname = 'gstr2b_documents_registration_same_tenant') THEN
    ALTER TABLE gstr2b_documents
      ADD CONSTRAINT gstr2b_documents_registration_same_tenant
      FOREIGN KEY (registration_id, tenant_id)
      REFERENCES gst_registrations (id, tenant_id)
      -- ⚠️ RESTRICT. The statement was generated for THAT GSTIN and the credit
      -- in it belongs to THAT electronic credit ledger. Losing the pointer
      -- loses which state the credit is in.
      ON DELETE RESTRICT;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint
                  WHERE conname = 'gstr2b_documents_imported_by_same_tenant') THEN
    ALTER TABLE gstr2b_documents
      ADD CONSTRAINT gstr2b_documents_imported_by_same_tenant
      FOREIGN KEY (imported_by, tenant_id) REFERENCES users (id, tenant_id)
      ON DELETE SET NULL (imported_by);
  END IF;

  /* --- gstr2b_rows ----------------------------------------------- */
  IF NOT EXISTS (SELECT 1 FROM pg_constraint
                  WHERE conname = 'gstr2b_rows_document_same_tenant') THEN
    ALTER TABLE gstr2b_rows ADD CONSTRAINT gstr2b_rows_document_same_tenant
      FOREIGN KEY (document_id, tenant_id)
      -- CASCADE: the rows are DERIVED. Dropping the statement drops its
      -- interpretation, which is correct — the raw document is the evidence
      -- and it cannot be dropped by the application at all (Section 10).
      REFERENCES gstr2b_documents (id, tenant_id) ON DELETE CASCADE;
  END IF;

  /* --- gstr2b_reconciliations ------------------------------------ */
  IF NOT EXISTS (SELECT 1 FROM pg_constraint
                  WHERE conname = 'gstr2b_reconciliations_registration_same_tenant') THEN
    ALTER TABLE gstr2b_reconciliations
      ADD CONSTRAINT gstr2b_reconciliations_registration_same_tenant
      FOREIGN KEY (registration_id, tenant_id)
      REFERENCES gst_registrations (id, tenant_id) ON DELETE RESTRICT;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint
                  WHERE conname = 'gstr2b_reconciliations_document_same_tenant') THEN
    ALTER TABLE gstr2b_reconciliations
      ADD CONSTRAINT gstr2b_reconciliations_document_same_tenant
      FOREIGN KEY (document_id, tenant_id)
      -- ⚠️ RESTRICT. A reconciliation names the statement it was built from,
      -- and a filed one is a working paper for a return the Government holds.
      REFERENCES gstr2b_documents (id, tenant_id) ON DELETE RESTRICT;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint
                  WHERE conname = 'gstr2b_reconciliations_filed_by_same_tenant') THEN
    ALTER TABLE gstr2b_reconciliations
      ADD CONSTRAINT gstr2b_reconciliations_filed_by_same_tenant
      FOREIGN KEY (filed_by, tenant_id) REFERENCES users (id, tenant_id)
      ON DELETE SET NULL (filed_by);
  END IF;

  /* --- gstr2b_matches -------------------------------------------- */
  IF NOT EXISTS (SELECT 1 FROM pg_constraint
                  WHERE conname = 'gstr2b_matches_reconciliation_same_tenant') THEN
    ALTER TABLE gstr2b_matches
      ADD CONSTRAINT gstr2b_matches_reconciliation_same_tenant
      FOREIGN KEY (reconciliation_id, tenant_id)
      REFERENCES gstr2b_reconciliations (id, tenant_id) ON DELETE CASCADE;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint
                  WHERE conname = 'gstr2b_matches_row_same_tenant') THEN
    ALTER TABLE gstr2b_matches ADD CONSTRAINT gstr2b_matches_row_same_tenant
      FOREIGN KEY (gstr2b_row_id, tenant_id)
      REFERENCES gstr2b_rows (id, tenant_id) ON DELETE CASCADE;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint
                  WHERE conname = 'gstr2b_matches_invoice_same_tenant') THEN
    ALTER TABLE gstr2b_matches ADD CONSTRAINT gstr2b_matches_invoice_same_tenant
      FOREIGN KEY (purchase_invoice_id, tenant_id)
      REFERENCES purchase_invoices (id, tenant_id)
      -- ⭐ RESTRICT. A purchase invoice that has been reconciled against a
      -- filed return cannot be deleted; the match is the evidence for the
      -- credit that was — or was not — claimed on it.
      ON DELETE RESTRICT;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint
                  WHERE conname = 'gstr2b_matches_vendor_same_tenant') THEN
    ALTER TABLE gstr2b_matches ADD CONSTRAINT gstr2b_matches_vendor_same_tenant
      FOREIGN KEY (vendor_id, tenant_id) REFERENCES vendors (id, tenant_id)
      ON DELETE SET NULL (vendor_id);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint
                  WHERE conname = 'gstr2b_matches_action_by_same_tenant') THEN
    ALTER TABLE gstr2b_matches ADD CONSTRAINT gstr2b_matches_action_by_same_tenant
      FOREIGN KEY (action_by, tenant_id) REFERENCES users (id, tenant_id)
      -- ⚠️ SET NULL, and it is the WRONG shape for evidence — but the
      -- alternative is worse. RESTRICT here would mean a person who accepted
      -- one match can never be removed from the workspace, and the answer to
      -- an offboarding request would be "no". The audit trail for WHO decided
      -- lives in `change_log` and `audit_logs`, which do not lose it.
      ON DELETE SET NULL (action_by);
  END IF;
END
$$;


-- ############################################################################
-- SECTION 5 — ⭐ THE RAW STATEMENT IS IMMUTABLE
-- ############################################################################
--
-- THE MOST IMPORTANT TRIGGER IN THE PHASE, AND THE ONE WITH THE LEAST
-- IMPRESSIVE MECHANISM.
--
--     `gstr2b_documents.raw_document` is the file the portal served. Every
--     parsed row is an INTERPRETATION of it. A parse bug is discovered, by
--     definition, after the parse — usually a year later, at a notice — and by
--     then the portal may no longer serve that month.
--
--     If a re-import, a "cleanup", or a well-meaning correction overwrote the
--     raw document with our own interpretation of it, there is nothing left to
--     re-read. The only remaining copy of what the Government said about us
--     would be our opinion of what the Government said about us.
--
-- So the file, its hash, its GSTIN and its period are frozen at insert.
-- `parse_status`, `parse_error`, `parse_issues`, `row_count` and `parsed_at`
-- stay editable, because re-parsing the SAME bytes with a FIXED parser is
-- exactly the operation this design exists to make possible.
--
-- ⚠️ A TRIGGER RATHER THAN A REVOKED UPDATE, because the row must remain
-- updatable for the parse columns. Column-level GRANTs could express it and
-- would be silent about WHY the update failed — and the "why" is the whole
-- content of this section.

CREATE OR REPLACE FUNCTION enforce_gstr2b_raw_immutable()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.raw_document IS DISTINCT FROM OLD.raw_document THEN
    RAISE EXCEPTION
      'The raw GSTR-2B statement for % (%) cannot be changed. It is the file the '
      'portal served, and every parsed row is an interpretation of it. A parse '
      'bug is found after the parse — often a year later at a notice — and by '
      'then the portal may no longer serve that month. Re-parse the stored '
      'document instead: rebuild the rows and update parse_status.',
      OLD.gstin, OLD.return_period
      USING ERRCODE = '42501';
  END IF;

  IF NEW.file_hash IS DISTINCT FROM OLD.file_hash
     OR NEW.gstin IS DISTINCT FROM OLD.gstin
     OR NEW.return_period IS DISTINCT FROM OLD.return_period
     OR NEW.source_format IS DISTINCT FROM OLD.source_format THEN
    RAISE EXCEPTION
      'The identity of an imported GSTR-2B statement — its hash, its GSTIN, its '
      'period and its format — cannot be changed. Those four are what let a '
      'later reader say THIS is the file the portal gave us; a mutable identity '
      'says nothing at all. Import the other file as a new document.'
      USING ERRCODE = '42501';
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS gstr2b_documents_raw_immutable ON gstr2b_documents;
CREATE TRIGGER gstr2b_documents_raw_immutable
  BEFORE UPDATE ON gstr2b_documents
  FOR EACH ROW EXECUTE FUNCTION enforce_gstr2b_raw_immutable();


-- ############################################################################
-- SECTION 6 — ⭐⭐ A FILED PERIOD FREEZES
-- ############################################################################
--
-- THE RULE:
--
--     Once a GSTR-3B has been filed for a period, the reconciliation that
--     supported it is a working paper for a document the Government holds a
--     copy of. Nothing about it may change — not the totals, not the matches,
--     and NOT BY RE-IMPORTING THE PERIOD.
--
-- ⚠️ THE RE-IMPORT IS THE CASE THAT MATTERS, AND IT IS ORDINARY WORK. The
-- portal REGENERATES GSTR-2B for a period whenever a supplier files their
-- GSTR-1 late. July's statement downloaded in August and July's statement
-- downloaded in November are different documents describing the same month.
-- Importing the November one is exactly the right thing to do — the late
-- filing means credit is now available — but the credit is available IN
-- NOVEMBER, in November's return, and July's filed figures must not move.
--
-- Without this trigger the second import would rewrite July: the totals would
-- change, the "in books, not in 2B" list would shrink, and the working paper
-- for a return already submitted would no longer describe what was submitted.
-- Nothing would error and nothing would say it had changed.
--
-- ⚠️ AND THE REFUSAL IS A SENTENCE THAT SAYS WHAT TO DO INSTEAD, because the
-- person hitting it is doing something reasonable and needs to be redirected
-- rather than blocked.

CREATE OR REPLACE FUNCTION enforce_gstr2b_period_not_filed()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  v_filed_at    timestamptz;
  v_reference   varchar(64);
BEGIN
  SELECT r.filed_at, r.filed_reference
    INTO v_filed_at, v_reference
    FROM gstr2b_reconciliations r
   WHERE r.tenant_id  = NEW.tenant_id
     AND r.gstin      = NEW.gstin
     AND r.tax_period = NEW.return_period
     AND r.status     = 'filed';

  IF FOUND AND v_filed_at IS NOT NULL THEN
    RAISE EXCEPTION
      'GSTR-2B for % % has already been reconciled and FILED (% , %). A filed '
      'period cannot be re-imported. The portal regenerates 2B whenever a '
      'supplier files late, so this file is almost certainly newer than the one '
      'the return was built from — and the credit it unlocks belongs to the '
      'CURRENT period''s return, not to a return already submitted. Import it '
      'against the period you are filing now.',
      NEW.gstin, NEW.return_period, COALESCE(v_reference, 'no ARN recorded'),
      to_char(v_filed_at, 'YYYY-MM-DD')
      USING ERRCODE = '42501';
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS gstr2b_documents_period_not_filed ON gstr2b_documents;
CREATE TRIGGER gstr2b_documents_period_not_filed
  BEFORE INSERT ON gstr2b_documents
  FOR EACH ROW EXECUTE FUNCTION enforce_gstr2b_period_not_filed();


-- The reconciliation itself. ⚠️ `notes` STAYS EDITABLE, DELIBERATELY: a note
-- added after filing ("supplier confirmed they filed on 14 Dec, credit taken in
-- December") is a fact about the past, not a change to it, and forbidding it
-- would push the same sentence into a spreadsheet nobody else can see.
CREATE OR REPLACE FUNCTION enforce_gstr2b_reconciliation_frozen()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF OLD.status <> 'filed' THEN
    RETURN NEW;
  END IF;

  IF NEW.status              IS DISTINCT FROM OLD.status
     OR NEW.gstin            IS DISTINCT FROM OLD.gstin
     OR NEW.tax_period       IS DISTINCT FROM OLD.tax_period
     OR NEW.document_id      IS DISTINCT FROM OLD.document_id
     OR NEW.filed_at         IS DISTINCT FROM OLD.filed_at
     OR NEW.filed_by         IS DISTINCT FROM OLD.filed_by
     OR NEW.filed_reference  IS DISTINCT FROM OLD.filed_reference
     OR NEW.books_invoice_count          IS DISTINCT FROM OLD.books_invoice_count
     OR NEW.books_taxable_minor          IS DISTINCT FROM OLD.books_taxable_minor
     OR NEW.books_tax_minor              IS DISTINCT FROM OLD.books_tax_minor
     OR NEW.books_itc_eligible_minor     IS DISTINCT FROM OLD.books_itc_eligible_minor
     OR NEW.twob_row_count               IS DISTINCT FROM OLD.twob_row_count
     OR NEW.twob_taxable_minor           IS DISTINCT FROM OLD.twob_taxable_minor
     OR NEW.twob_tax_minor               IS DISTINCT FROM OLD.twob_tax_minor
     OR NEW.twob_itc_available_minor     IS DISTINCT FROM OLD.twob_itc_available_minor
     OR NEW.matched_count                IS DISTINCT FROM OLD.matched_count
     OR NEW.matched_books_tax_minor      IS DISTINCT FROM OLD.matched_books_tax_minor
     OR NEW.matched_twob_tax_minor       IS DISTINCT FROM OLD.matched_twob_tax_minor
     OR NEW.in_books_not_in_2b_count     IS DISTINCT FROM OLD.in_books_not_in_2b_count
     OR NEW.in_books_not_in_2b_tax_minor IS DISTINCT FROM OLD.in_books_not_in_2b_tax_minor
     OR NEW.in_2b_not_in_books_count     IS DISTINCT FROM OLD.in_2b_not_in_books_count
     OR NEW.in_2b_not_in_books_tax_minor IS DISTINCT FROM OLD.in_2b_not_in_books_tax_minor
     OR NEW.itc_at_risk_minor            IS DISTINCT FROM OLD.itc_at_risk_minor
     OR NEW.itc_claimed_minor            IS DISTINCT FROM OLD.itc_claimed_minor THEN
    RAISE EXCEPTION
      'The GSTR-2B reconciliation for % % was FILED on % and cannot be changed. '
      'It is the working paper for a GSTR-3B the Government holds a copy of. A '
      'return that has been filed cannot be unfiled — a period that turns out to '
      'be wrong is corrected in a LATER period, which is how the electronic '
      'credit ledger itself behaves and the only way the books can go on '
      'agreeing with the returns already submitted.',
      OLD.gstin, OLD.tax_period, to_char(OLD.filed_at, 'YYYY-MM-DD')
      USING ERRCODE = '42501';
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS gstr2b_reconciliations_frozen ON gstr2b_reconciliations;
CREATE TRIGGER gstr2b_reconciliations_frozen
  BEFORE UPDATE ON gstr2b_reconciliations
  FOR EACH ROW EXECUTE FUNCTION enforce_gstr2b_reconciliation_frozen();


-- And the matches under a filed reconciliation. ⚠️ INSERT, UPDATE **AND**
-- DELETE: a re-run that deleted the old matches and wrote new ones would leave
-- the totals intact and every explanation replaced, which is the worst of both
-- — a filed working paper whose reasoning is no longer the reasoning that was
-- used.
CREATE OR REPLACE FUNCTION enforce_gstr2b_match_not_filed()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  v_row       gstr2b_matches%ROWTYPE;
  v_gstin     varchar(15);
  v_period    varchar(7);
  v_filed_at  timestamptz;
BEGIN
  v_row := COALESCE(NEW, OLD);

  SELECT r.gstin, r.tax_period, r.filed_at
    INTO v_gstin, v_period, v_filed_at
    FROM gstr2b_reconciliations r
   WHERE r.id = v_row.reconciliation_id
     AND r.status = 'filed';

  IF FOUND AND v_filed_at IS NOT NULL THEN
    RAISE EXCEPTION
      'The GSTR-2B reconciliation for % % was FILED on %. Its matches are the '
      'evidence for every credit taken and every credit withheld in that return, '
      'and they cannot be added to, changed or removed. Reconcile the current '
      'period instead.',
      v_gstin, v_period, to_char(v_filed_at, 'YYYY-MM-DD')
      USING ERRCODE = '42501';
  END IF;

  RETURN v_row;
END;
$$;

DROP TRIGGER IF EXISTS gstr2b_matches_not_filed ON gstr2b_matches;
CREATE TRIGGER gstr2b_matches_not_filed
  BEFORE INSERT OR UPDATE OR DELETE ON gstr2b_matches
  FOR EACH ROW EXECUTE FUNCTION enforce_gstr2b_match_not_filed();


-- ############################################################################
-- SECTION 7 — ⭐ THE SUMMARY MUST AGREE WITH ITS OWN MATCHES
-- ############################################################################
--
-- The two CHECK constraints in Section 1 prove the summary is INTERNALLY
-- consistent: books = matched + unmatched, on both sides. They say nothing
-- about whether those figures describe the matches actually stored, and that
-- is where the drift happens — the header is written by one statement and the
-- matches by another, and a partially-written re-run balances perfectly while
-- describing a reconciliation that does not exist.
--
-- ⚠️ A CONSTRAINT TRIGGER, DEFERRABLE INITIALLY DEFERRED, AND IT HAS TO BE. An
-- immediate trigger on `gstr2b_reconciliations` fires before any match exists
-- and would refuse every reconciliation ever created. COMMIT is the only point
-- at which the header and its matches are both present and both final.
--
-- ⚠️ AND IT ONLY FIRES WHERE MATCHES EXIST, exactly as the Phase 33 invoice
-- reconciliation only fires on `gst_computed` documents. A reconciliation row
-- created ahead of its run, or imported from a legacy system with totals only,
-- is not refused; one that CLAIMS to describe stored matches must describe
-- them.

CREATE OR REPLACE FUNCTION enforce_gstr2b_summary_agrees()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  v_rec           gstr2b_reconciliations%ROWTYPE;
  v_match_count   integer;
  v_matched_cnt   integer;
  v_matched_books bigint;
  v_matched_twob  bigint;
  v_books_only    bigint;
  v_twob_only     bigint;
BEGIN
  IF TG_TABLE_NAME = 'gstr2b_reconciliations' THEN
    v_rec := NEW;
  ELSE
    SELECT * INTO v_rec FROM gstr2b_reconciliations
     WHERE id = COALESCE(NEW.reconciliation_id, OLD.reconciliation_id);
    IF NOT FOUND THEN RETURN NULL; END IF;
  END IF;

  SELECT count(*) INTO v_match_count
    FROM gstr2b_matches m WHERE m.reconciliation_id = v_rec.id;

  -- Not run yet. Nothing to disagree with.
  IF v_match_count = 0 THEN RETURN NULL; END IF;

  SELECT
    count(*) FILTER (WHERE m.gstr2b_row_id IS NOT NULL
                       AND m.purchase_invoice_id IS NOT NULL),
    COALESCE(sum(i.cgst_minor + i.sgst_minor + i.igst_minor + i.cess_minor)
               FILTER (WHERE m.gstr2b_row_id IS NOT NULL
                         AND m.purchase_invoice_id IS NOT NULL), 0),
    COALESCE(sum(b.cgst_minor + b.sgst_minor + b.igst_minor + b.cess_minor)
               FILTER (WHERE m.gstr2b_row_id IS NOT NULL
                         AND m.purchase_invoice_id IS NOT NULL), 0),
    COALESCE(sum(i.cgst_minor + i.sgst_minor + i.igst_minor + i.cess_minor)
               FILTER (WHERE m.gstr2b_row_id IS NULL), 0),
    COALESCE(sum(b.cgst_minor + b.sgst_minor + b.igst_minor + b.cess_minor)
               FILTER (WHERE m.purchase_invoice_id IS NULL), 0)
    INTO v_matched_cnt, v_matched_books, v_matched_twob, v_books_only, v_twob_only
    FROM gstr2b_matches m
    LEFT JOIN purchase_invoices i ON i.id = m.purchase_invoice_id
    LEFT JOIN gstr2b_rows      b ON b.id = m.gstr2b_row_id
   WHERE m.reconciliation_id = v_rec.id;

  IF v_matched_cnt <> v_rec.matched_count THEN
    RAISE EXCEPTION
      'The GSTR-2B reconciliation for % % says % documents matched; % match rows '
      'carry both a supplier declaration and a purchase invoice. A count that '
      'disagrees with its own rows is a count nobody can check.',
      v_rec.gstin, v_rec.tax_period, v_rec.matched_count, v_matched_cnt
      USING ERRCODE = '23514';
  END IF;

  IF v_matched_books <> v_rec.matched_books_tax_minor
     OR v_matched_twob <> v_rec.matched_twob_tax_minor THEN
    RAISE EXCEPTION
      'The GSTR-2B reconciliation for % % does not agree with its own matches: '
      'the matched rows carry % paise of tax on the books side and % on the 2B '
      'side, and the summary says % and %.',
      v_rec.gstin, v_rec.tax_period, v_matched_books, v_matched_twob,
      v_rec.matched_books_tax_minor, v_rec.matched_twob_tax_minor
      USING ERRCODE = '23514';
  END IF;

  IF v_books_only <> v_rec.in_books_not_in_2b_tax_minor THEN
    RAISE EXCEPTION
      '⭐ The GSTR-2B reconciliation for % % says % paise of tax is in the books '
      'and not in 2B; the match rows carry %. That figure is the input tax '
      'credit Section 16(2)(aa) does NOT allow until the supplier files, and a '
      'summary that understates it reports suppliers as having filed when they '
      'have not.',
      v_rec.gstin, v_rec.tax_period, v_rec.in_books_not_in_2b_tax_minor, v_books_only
      USING ERRCODE = '23514';
  END IF;

  IF v_twob_only <> v_rec.in_2b_not_in_books_tax_minor THEN
    RAISE EXCEPTION
      'The GSTR-2B reconciliation for % % says % paise of tax is in 2B and not in '
      'the books; the match rows carry %.',
      v_rec.gstin, v_rec.tax_period, v_rec.in_2b_not_in_books_tax_minor, v_twob_only
      USING ERRCODE = '23514';
  END IF;

  RETURN NULL;
END;
$$;

DROP TRIGGER IF EXISTS gstr2b_reconciliations_summary_agrees ON gstr2b_reconciliations;
CREATE CONSTRAINT TRIGGER gstr2b_reconciliations_summary_agrees
  AFTER INSERT OR UPDATE ON gstr2b_reconciliations
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION enforce_gstr2b_summary_agrees();

DROP TRIGGER IF EXISTS gstr2b_matches_summary_agrees ON gstr2b_matches;
CREATE CONSTRAINT TRIGGER gstr2b_matches_summary_agrees
  AFTER INSERT OR UPDATE OR DELETE ON gstr2b_matches
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION enforce_gstr2b_summary_agrees();


-- ############################################################################
-- SECTION 8 — ⭐ A MATCH MAY NOT CROSS A STATEMENT OR A PERIOD
-- ############################################################################
--
-- The composite foreign keys in Section 4 stop a match pointing at ANOTHER
-- TENANT'S rows. This stops something narrower and entirely within one tenant:
--
--     A match under July's reconciliation for GSTIN 27… that points at a 2B
--     row belonging to AUGUST's statement, or to the statement of the
--     Karnataka registration.
--
-- ⚠️ WHY IT MATTERS. A developer registered in two states has two 2B
-- statements a month and two electronic credit ledgers that never mix — Section
-- 16(1) gives the credit to the registered person who received the supply. A
-- match that reaches across them reconciles Maharashtra's books against
-- Karnataka's statement, and the credit it appears to justify is in a ledger
-- with nothing to set it against.
--
-- ⚠️ AND ACROSS PERIODS IT IS SUBTLER AND WORSE: July's reconciliation matching
-- an August 2B row would report the supplier as having filed IN JULY, which is
-- the whole question Section 16(2)(aa) turns on.

CREATE OR REPLACE FUNCTION enforce_gstr2b_match_within_statement()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  v_rec_gstin   varchar(15);
  v_rec_period  varchar(7);
  v_row_gstin   varchar(15);
  v_row_period  varchar(7);
BEGIN
  IF NEW.gstr2b_row_id IS NULL THEN RETURN NEW; END IF;

  SELECT r.gstin, r.tax_period INTO v_rec_gstin, v_rec_period
    FROM gstr2b_reconciliations r WHERE r.id = NEW.reconciliation_id;
  IF NOT FOUND THEN RETURN NEW; END IF;

  SELECT d.gstin, d.return_period INTO v_row_gstin, v_row_period
    FROM gstr2b_rows w
    JOIN gstr2b_documents d ON d.id = w.document_id
   WHERE w.id = NEW.gstr2b_row_id;
  IF NOT FOUND THEN RETURN NEW; END IF;

  IF v_row_gstin <> v_rec_gstin THEN
    RAISE EXCEPTION
      'This match is under the reconciliation for GSTIN % but the supplier '
      'declaration comes from the GSTR-2B of GSTIN %. Input tax credit belongs '
      'to the electronic credit ledger of the registration that received the '
      'supply (Section 16(1)) — matching across two registrations justifies a '
      'credit in a ledger with nothing to set it against.',
      v_rec_gstin, v_row_gstin
      USING ERRCODE = '23514';
  END IF;

  IF v_row_period <> v_rec_period THEN
    RAISE EXCEPTION
      'This match is under the % reconciliation but the supplier declaration '
      'comes from the % statement. Whether the supplier filed IN THIS PERIOD is '
      'the entire question Section 16(2)(aa) turns on, and a match across '
      'periods answers it wrongly in the direction that claims the credit.',
      v_rec_period, v_row_period
      USING ERRCODE = '23514';
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS gstr2b_matches_within_statement ON gstr2b_matches;
CREATE TRIGGER gstr2b_matches_within_statement
  BEFORE INSERT OR UPDATE ON gstr2b_matches
  FOR EACH ROW EXECUTE FUNCTION enforce_gstr2b_match_within_statement();


-- ############################################################################
-- SECTION 9 — ⭐ SUPPORT SESSIONS MAY NOT DELETE TAX EVIDENCE
-- ############################################################################
--
-- Phase 17 installed `refuse_delete_under_impersonation()`. These four tables
-- join the list, and the argument for `gstr2b_documents` is the strongest in
-- the product:
--
-- ⚠️ IT IS THE ONE TABLE WHOSE CONTENTS CANNOT BE RECONSTRUCTED FROM ANYTHING
-- THE CUSTOMER HOLDS. A deleted purchase invoice can be re-entered from the
-- paper in the file. A deleted 2B statement can only be re-downloaded from a
-- portal that keeps two years of history — and the statement that mattered is
-- the one generated on the day the return was filed, which the portal will
-- never serve again because it has since been regenerated.
--
-- Written with a `to_regclass` check so the file stays runnable against a
-- database where Phase 17 has not been applied.

DO $$
DECLARE
  guarded text;
BEGIN
  IF EXISTS (SELECT 1 FROM pg_proc WHERE proname = 'refuse_delete_under_impersonation') THEN
    FOREACH guarded IN ARRAY ARRAY[
      'gstr2b_documents', 'gstr2b_rows', 'gstr2b_reconciliations', 'gstr2b_matches'
    ]
    LOOP
      IF to_regclass('public.' || guarded) IS NOT NULL THEN
        EXECUTE format(
          'DROP TRIGGER IF EXISTS %I ON %I', 'no_delete_under_impersonation', guarded
        );
        EXECUTE format(
          'CREATE TRIGGER %I BEFORE DELETE ON %I FOR EACH ROW '
          'EXECUTE FUNCTION refuse_delete_under_impersonation()',
          'no_delete_under_impersonation', guarded
        );
      END IF;
    END LOOP;
  END IF;
END
$$;


-- ############################################################################
-- SECTION 9b — updated_at, AND THE CHANGE LOG
-- ############################################################################

DO $$
DECLARE
  t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['gstr2b_documents','gstr2b_rows',
                           'gstr2b_reconciliations','gstr2b_matches']
  LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS %I ON %I', t || '_set_updated_at', t);
    EXECUTE format(
      'CREATE TRIGGER %I BEFORE UPDATE ON %I
         FOR EACH ROW EXECUTE FUNCTION set_updated_at()',
      t || '_set_updated_at', t);
  END LOOP;

  -- ⚠️ ALL FOUR, INCLUDING `gstr2b_rows`, AND THE ARGUMENT FOR LEAVING IT OUT
  -- WAS CONSIDERED AND REJECTED.
  --
  -- The case against: a large developer's monthly statement runs to tens of
  -- thousands of rows, rebuilt whenever the statement is re-parsed, and the
  -- rows are DERIVED — the thing that has to be provable is the raw document
  -- they came from, and that is logged, immutable and hashed. Logging the rows
  -- makes the change log the largest table in the database.
  --
  -- The case for, which wins: the change log is not only evidence, it is how a
  -- table SYNCS. A tenant-scoped table with no trigger simply never
  -- replicates, and the omission is silent — nobody finds out until data is
  -- missing on one machine and present on another, with no error and nothing
  -- to point at. `tests/security/change-log.test.ts` DISCOVERS the gap rather
  -- than reading a list, for exactly that reason, and an exemption argued from
  -- storage cost is the shape every such gap has when it is introduced.
  IF EXISTS (SELECT 1 FROM pg_proc WHERE proname = 'record_change') THEN
    FOREACH t IN ARRAY ARRAY['gstr2b_documents','gstr2b_rows',
                             'gstr2b_reconciliations','gstr2b_matches']
    LOOP
      EXECUTE format('DROP TRIGGER IF EXISTS %I ON %I', t || '_change_log', t);
      EXECUTE format(
        'CREATE TRIGGER %I AFTER INSERT OR UPDATE OR DELETE ON %I
           FOR EACH ROW EXECUTE FUNCTION record_change()',
        t || '_change_log', t);
    END LOOP;
  END IF;
END
$$;


-- ############################################################################
-- SECTION 10 — GRANTS
-- ############################################################################
--
-- REVOKE before GRANT. An additive-only block is defeated by any prior
-- `GRANT ALL ON ALL TABLES`, which is the first thing most people run when a
-- query fails with "permission denied". Found the hard way in Phase 11.
--
-- ⚠️ NO DELETE ON `gstr2b_documents`, AND THAT IS THE POINT OF THE TABLE.
-- The statement is the evidence. It is the only artefact in the product that
-- the customer cannot reconstruct from their own paper, and the portal will
-- not serve the same generation of it twice.
--
-- ⚠️ NO DELETE ON `gstr2b_reconciliations` EITHER. A filed reconciliation is a
-- working paper for a return the Government holds; an unfiled one is the audit
-- trail of what was looked at before it was filed. A wrong reconciliation is
-- superseded by re-running it, not removed.
--
-- `gstr2b_rows` and `gstr2b_matches` DO get DELETE, and the asymmetry is the
-- design: both are DERIVED from the raw document by a deterministic engine, and
-- re-running the engine has to be able to replace them. What protects them once
-- they matter is the FREEZE (Section 6), not the grant — because a match under
-- a filed reconciliation must be immovable while a match under a draft one must
-- be replaceable, and a GRANT cannot tell those apart.

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'ordence_app') THEN
    REVOKE ALL ON gstr2b_documents       FROM ordence_app;
    REVOKE ALL ON gstr2b_rows            FROM ordence_app;
    REVOKE ALL ON gstr2b_reconciliations FROM ordence_app;
    REVOKE ALL ON gstr2b_matches         FROM ordence_app;

    GRANT SELECT, INSERT, UPDATE         ON gstr2b_documents       TO ordence_app;
    GRANT SELECT, INSERT, UPDATE, DELETE ON gstr2b_rows            TO ordence_app;
    GRANT SELECT, INSERT, UPDATE         ON gstr2b_reconciliations TO ordence_app;
    GRANT SELECT, INSERT, UPDATE, DELETE ON gstr2b_matches         TO ordence_app;
  END IF;
END
$$;


-- ############################################################################
-- SECTION 11 — VERIFICATION
-- ############################################################################
--
-- Every check names what breaks if it fails, because "FAIL" on its own tells
-- you nothing about whether to panic.

-- Check 1 — RLS is ENABLED **and FORCED** on all four new tables.
-- ⚠️ `relforcerowsecurity` is the column that matters. ENABLE without FORCE
-- looks protected in every UI and is not protected against the owner.
SELECT
  c.relname AS table_name,
  CASE WHEN c.relrowsecurity AND c.relforcerowsecurity
       THEN 'PASS (enabled + forced)'
       WHEN c.relrowsecurity
       THEN '*** FAIL — enabled but NOT FORCED: the owner bypasses it ***'
       ELSE '*** FAIL — ROW LEVEL SECURITY IS OFF: every tenant can read every '
            'other tenant''s GSTR-2B, which is a Government-compiled list of who '
            'they buy from and for how much ***'
  END AS verdict
FROM pg_class c
JOIN pg_namespace n ON n.oid = c.relnamespace
WHERE n.nspname = 'public'
  AND c.relname IN ('gstr2b_documents','gstr2b_rows',
                    'gstr2b_reconciliations','gstr2b_matches')
ORDER BY c.relname;


-- Check 2 — every policy has BOTH a read and a write clause.
SELECT
  tablename, policyname,
  CASE WHEN qual IS NOT NULL AND with_check IS NOT NULL
       THEN 'PASS (read + write)'
       WHEN with_check IS NULL
       THEN '*** FAIL — no WITH CHECK: a tenant can plant a match in another '
            'tenant''s reconciliation ***'
       ELSE '*** FAIL — no USING clause ***'
  END AS verdict
FROM pg_policies
WHERE schemaname = 'public'
  AND tablename IN ('gstr2b_documents','gstr2b_rows',
                    'gstr2b_reconciliations','gstr2b_matches')
ORDER BY tablename;


-- Check 3 — ⭐ the composite foreign keys exist (Section 4).
SELECT
  expected.conname,
  CASE WHEN pc.conname IS NOT NULL THEN 'PASS'
       ELSE '*** FAIL — MISSING: a row can point at another tenant''s record, and '
            'for purchase_invoice_id that is an existence oracle over another '
            'developer''s purchase ledger ***'
  END AS verdict
FROM (VALUES
  ('gstr2b_documents_registration_same_tenant'),
  ('gstr2b_documents_imported_by_same_tenant'),
  ('gstr2b_rows_document_same_tenant'),
  ('gstr2b_reconciliations_registration_same_tenant'),
  ('gstr2b_reconciliations_document_same_tenant'),
  ('gstr2b_reconciliations_filed_by_same_tenant'),
  ('gstr2b_matches_reconciliation_same_tenant'),
  ('gstr2b_matches_row_same_tenant'),
  ('gstr2b_matches_invoice_same_tenant'),
  ('gstr2b_matches_vendor_same_tenant'),
  ('gstr2b_matches_action_by_same_tenant')
) AS expected(conname)
LEFT JOIN pg_constraint pc ON pc.conname = expected.conname
ORDER BY expected.conname;


-- Check 4 — the guards are installed AND enabled.
-- ⚠️ `tgenabled` needs the ::text cast; without it the comparison silently
-- misbehaves. Found in Phase 11 against a real PostgreSQL.
SELECT
  expected.tgname,
  CASE WHEN t.tgname IS NULL THEN '*** FAIL — TRIGGER MISSING ***'
       WHEN t.tgenabled::text = 'O' THEN 'PASS (enabled)'
       ELSE '*** FAIL — trigger DISABLED: ' || t.tgenabled::text || ' ***'
  END AS verdict
FROM (VALUES
  ('gstr2b_documents_raw_immutable',          'gstr2b_documents'),
  ('gstr2b_documents_period_not_filed',       'gstr2b_documents'),
  ('gstr2b_reconciliations_frozen',           'gstr2b_reconciliations'),
  ('gstr2b_matches_not_filed',                'gstr2b_matches'),
  ('gstr2b_matches_within_statement',         'gstr2b_matches'),
  ('gstr2b_reconciliations_summary_agrees',   'gstr2b_reconciliations'),
  ('gstr2b_matches_summary_agrees',           'gstr2b_matches')
) AS expected(tgname, tbl)
LEFT JOIN pg_trigger t
       ON t.tgname = expected.tgname
      AND t.tgrelid = expected.tbl::regclass
      AND NOT t.tgisinternal
ORDER BY expected.tgname;


-- Check 5 — ⭐⭐ THE RAW STATEMENT CANNOT BE DESTROYED, AND A FAILED PARSE
-- STILL LEAVES IT INTACT.
--
-- Proved rather than inspected: a trigger whose condition is subtly inverted
-- passes every "does it exist" check. This stores a document, marks the parse
-- FAILED (which is the ordinary path when a file will not parse), reads the raw
-- back, and then tries to blank it.
DO $$
DECLARE
  v_tenant   uuid := gen_random_uuid();
  v_doc      uuid := gen_random_uuid();
  v_raw      jsonb;
  v_marked   boolean := false;
  v_intact   boolean := false;
  v_refused  boolean := false;
BEGIN
  INSERT INTO tenants (id, clerk_org_id, slug, name, status)
    VALUES (v_tenant, 'org_2braw_' || v_tenant, 'raw-' || left(v_tenant::text, 8),
            'GSTR-2B raw verification', 'active');

  INSERT INTO gstr2b_documents
    (id, tenant_id, gstin, return_period, source_format, file_hash, raw_document)
    VALUES (v_doc, v_tenant, '27AAACR5055K1ZQ', '2024-07', 'portal_json',
            repeat('a', 64),
            '{"data":{"gstin":"27AAACR5055K1ZQ","rtnprd":"072024","docdata":{"b2b":[]}}}'::jsonb);

  -- The ordinary failed-parse path. MUST be accepted: refusing it is how the
  -- raw file gets thrown away, because the caller then rolls the whole
  -- transaction back.
  BEGIN
    UPDATE gstr2b_documents
       SET parse_status = 'failed',
           parse_error  = 'Unexpected token at data.docdata.b2b[0]',
           row_count    = 0
     WHERE id = v_doc;
    v_marked := true;
  EXCEPTION WHEN OTHERS THEN
    v_marked := false;
    RAISE NOTICE 'marking a parse failed was refused: %', SQLERRM;
  END;

  SELECT raw_document INTO v_raw FROM gstr2b_documents WHERE id = v_doc;
  v_intact := v_raw IS NOT NULL AND v_raw <> 'null'::jsonb
              AND v_raw #>> '{data,gstin}' = '27AAACR5055K1ZQ';

  -- ⭐ And the raw itself. MUST be refused.
  BEGIN
    UPDATE gstr2b_documents SET raw_document = '{}'::jsonb WHERE id = v_doc;
  EXCEPTION WHEN OTHERS THEN
    v_refused := true;
  END;

  IF v_marked AND v_intact AND v_refused THEN
    RAISE NOTICE 'PASS: ⭐ a malformed statement is recorded as failed WITHOUT '
                 'destroying the raw document, and the raw document cannot be '
                 'overwritten.';
  ELSIF NOT v_marked THEN
    RAISE WARNING '*** FAIL — marking a parse as failed was refused, so the only '
                  'way to record a bad file is to roll back the transaction that '
                  'stored it. The raw file is then lost, and a parse bug found a '
                  'year later has nothing to re-read. ***';
  ELSIF NOT v_intact THEN
    RAISE WARNING '*** FAIL — ⭐⭐ THE RAW DOCUMENT DID NOT SURVIVE A FAILED '
                  'PARSE. It is the only artefact the customer cannot reconstruct '
                  'from their own paper. ***';
  ELSE
    RAISE WARNING '*** FAIL — the raw GSTR-2B was OVERWRITTEN. Every parsed row is '
                  'an interpretation of it; without it, the only remaining copy of '
                  'what the Government said about us is our opinion of what the '
                  'Government said about us. ***';
  END IF;

  RAISE EXCEPTION 'verification rollback';
EXCEPTION WHEN OTHERS THEN
  IF SQLERRM <> 'verification rollback' THEN
    RAISE WARNING '*** FAIL — verification could not run: % ***', SQLERRM;
  END IF;
END
$$;


-- Check 6 — ⭐⭐ A FILED PERIOD FREEZES, AND A DIFFERENT PERIOD DOES NOT.
--
-- Both halves matter. A freeze that also blocked the NEXT period would stop the
-- product working in the one week of the month it is used, and somebody would
-- delete the reconciliation to get past it.
DO $$
DECLARE
  v_tenant    uuid := gen_random_uuid();
  v_first_ok  boolean := false;
  v_refused   boolean := false;
  v_next_ok   boolean := false;
  v_frozen    boolean := false;
BEGIN
  INSERT INTO tenants (id, clerk_org_id, slug, name, status)
    VALUES (v_tenant, 'org_2bfreeze_' || v_tenant, 'frz-' || left(v_tenant::text, 8),
            'GSTR-2B freeze verification', 'active');

  -- July's statement, reconciled and FILED.
  BEGIN
    INSERT INTO gstr2b_documents
      (tenant_id, gstin, return_period, source_format, file_hash, raw_document)
      VALUES (v_tenant, '27AAACR5055K1ZQ', '2024-07', 'portal_json',
              repeat('b', 64), '{"data":{"gstin":"x"}}'::jsonb);
    v_first_ok := true;
  EXCEPTION WHEN OTHERS THEN
    v_first_ok := false;
    RAISE NOTICE 'first import refused: %', SQLERRM;
  END;

  INSERT INTO gstr2b_reconciliations
    (tenant_id, gstin, tax_period, status, filed_at, filed_reference)
    VALUES (v_tenant, '27AAACR5055K1ZQ', '2024-07', 'filed', now(), 'AA270724TEST');

  -- ⭐ July again — the portal regenerates 2B when a supplier files late, so
  -- this is ordinary work and it MUST be refused.
  BEGIN
    INSERT INTO gstr2b_documents
      (tenant_id, gstin, return_period, source_format, file_hash, raw_document)
      VALUES (v_tenant, '27AAACR5055K1ZQ', '2024-07', 'portal_json',
              repeat('c', 64), '{"data":{"gstin":"x"}}'::jsonb);
  EXCEPTION WHEN OTHERS THEN
    v_refused := true;
  END;

  -- August. MUST be accepted — this is where the late credit belongs.
  BEGIN
    INSERT INTO gstr2b_documents
      (tenant_id, gstin, return_period, source_format, file_hash, raw_document)
      VALUES (v_tenant, '27AAACR5055K1ZQ', '2024-08', 'portal_json',
              repeat('d', 64), '{"data":{"gstin":"x"}}'::jsonb);
    v_next_ok := true;
  EXCEPTION WHEN OTHERS THEN
    v_next_ok := false;
    RAISE NOTICE 'next period refused: %', SQLERRM;
  END;

  -- And the filed totals themselves. MUST be refused.
  BEGIN
    UPDATE gstr2b_reconciliations
       SET books_tax_minor = 100000,
           in_books_not_in_2b_tax_minor = 100000
     WHERE tenant_id = v_tenant AND tax_period = '2024-07';
  EXCEPTION WHEN OTHERS THEN
    v_frozen := true;
  END;

  IF v_first_ok AND v_refused AND v_next_ok AND v_frozen THEN
    RAISE NOTICE 'PASS: ⭐ a FILED period refuses re-import and refuses restatement, '
                 'and the next period is unaffected.';
  ELSIF NOT v_first_ok THEN
    RAISE WARNING '*** FAIL — an ordinary first import was refused. ***';
  ELSIF NOT v_refused THEN
    RAISE WARNING '*** FAIL — ⭐⭐ A FILED PERIOD WAS RE-IMPORTED. The working paper '
                  'for a GSTR-3B the Government holds a copy of would be rewritten '
                  'by the newer statement, and nothing anywhere would say it had '
                  'changed. ***';
  ELSIF NOT v_next_ok THEN
    RAISE WARNING '*** FAIL — the NEXT period was refused because an earlier one was '
                  'filed. The product would stop working in the one week of the '
                  'month it is used, and somebody would delete the reconciliation to '
                  'get past it. ***';
  ELSE
    RAISE WARNING '*** FAIL — a FILED reconciliation''s totals were restated. ***';
  END IF;

  RAISE EXCEPTION 'verification rollback';
EXCEPTION WHEN OTHERS THEN
  IF SQLERRM <> 'verification rollback' THEN
    RAISE WARNING '*** FAIL — verification could not run: % ***', SQLERRM;
  END IF;
END
$$;


-- Check 7 — ⭐⭐ NOTHING BELOW AN EXACT MATCH IS ACCEPTED WITHOUT A HUMAN.
--
-- Three cases, because a constraint that refused all three would be just as
-- broken as one that allowed all three: an EXACT match may be accepted by the
-- engine, a PROBABLE one may be accepted by a person, and a PROBABLE one may
-- never be accepted by nobody.
DO $$
DECLARE
  v_tenant   uuid := gen_random_uuid();
  v_user     uuid := gen_random_uuid();
  v_rec      uuid := gen_random_uuid();
  v_doc      uuid := gen_random_uuid();
  v_row1     uuid := gen_random_uuid();
  v_row2     uuid := gen_random_uuid();
  v_vendor   uuid := gen_random_uuid();
  v_inv1     uuid := gen_random_uuid();
  v_inv2     uuid := gen_random_uuid();
  v_exact_ok boolean := false;
  v_human_ok boolean := false;
  v_silent_refused boolean := false;
BEGIN
  INSERT INTO tenants (id, clerk_org_id, slug, name, status)
    VALUES (v_tenant, 'org_2bacc_' || v_tenant, 'acc-' || left(v_tenant::text, 8),
            'GSTR-2B accept verification', 'active');
  INSERT INTO users (id, tenant_id, clerk_user_id, email, role, status)
    VALUES (v_user, v_tenant, 'usr_' || v_user, 'acc@example.test',
            'tenant_admin', 'active');
  INSERT INTO vendors (id, tenant_id, code, legal_name)
    VALUES (v_vendor, v_tenant, 'V-2B', 'Verification Supplier');

  INSERT INTO gstr2b_documents
    (id, tenant_id, gstin, return_period, source_format, file_hash, raw_document)
    VALUES (v_doc, v_tenant, '27AAACR5055K1ZQ', '2024-07', 'portal_json',
            repeat('e', 64), '{"data":{"gstin":"x"}}'::jsonb);

  INSERT INTO gstr2b_rows
    (id, tenant_id, document_id, section, supplier_gstin, invoice_number,
     normalised_number, invoice_date, taxable_value_minor, cgst_minor, sgst_minor)
    VALUES
    (v_row1, v_tenant, v_doc, 'b2b', '29AAACR5055K1ZP', 'INV-001', 'INV1',
     DATE '2024-07-05', 10000000, 900000, 900000),
    (v_row2, v_tenant, v_doc, 'b2b', '29AAACR5055K1ZP', 'INV-002', 'INV2',
     DATE '2024-07-06', 10000000, 900000, 900000);

  INSERT INTO purchase_invoices
    (id, tenant_id, vendor_id, supplier_gstin, invoice_number, invoice_date,
     subtotal_minor, taxable_value_minor, cgst_minor, sgst_minor, total_minor,
     itc_eligible_tax_minor)
    VALUES
    (v_inv1, v_tenant, v_vendor, '29AAACR5055K1ZP', 'INV-001', DATE '2024-07-05',
     10000000, 10000000, 900000, 900000, 11800000, 1800000),
    (v_inv2, v_tenant, v_vendor, '29AAACR5055K1ZP', 'INV/002', DATE '2024-07-06',
     10000000, 10000000, 900000, 900000, 11800000, 1800000);

  INSERT INTO gstr2b_reconciliations
    (id, tenant_id, gstin, tax_period, document_id, status,
     books_tax_minor, matched_books_tax_minor,
     twob_tax_minor, matched_twob_tax_minor, matched_count)
    VALUES (v_rec, v_tenant, '27AAACR5055K1ZQ', '2024-07', v_doc, 'in_progress',
            3600000, 3600000, 3600000, 3600000, 2);

  -- ⭐ An EXACT match, accepted by the engine with nobody named. MUST be
  -- accepted — there is nothing left to judge.
  BEGIN
    INSERT INTO gstr2b_matches
      (tenant_id, reconciliation_id, gstr2b_row_id, purchase_invoice_id,
       supplier_gstin, match_category, confidence, match_score, explanation,
       action, action_at)
      VALUES (v_tenant, v_rec, v_row1, v_inv1, '29AAACR5055K1ZP', 'exact', 'exact',
              100, 'Every field agrees exactly.', 'accepted', now());
    v_exact_ok := true;
  EXCEPTION WHEN OTHERS THEN
    v_exact_ok := false;
    RAISE NOTICE 'exact auto-accept refused: %', SQLERRM;
  END;

  -- ⭐⭐ A NUMBER MISMATCH accepted with NOBODY named. MUST be refused.
  BEGIN
    INSERT INTO gstr2b_matches
      (tenant_id, reconciliation_id, gstr2b_row_id, purchase_invoice_id,
       supplier_gstin, match_category, confidence, match_score, explanation,
       action, action_at)
      VALUES (v_tenant, v_rec, v_row2, v_inv2, '29AAACR5055K1ZP', 'number_mismatch',
              'medium', 75, 'INV-002 vs INV/002.', 'accepted', now());
  EXCEPTION WHEN OTHERS THEN
    v_silent_refused := true;
  END;

  -- The same match, accepted BY A PERSON. MUST be accepted.
  BEGIN
    INSERT INTO gstr2b_matches
      (tenant_id, reconciliation_id, gstr2b_row_id, purchase_invoice_id,
       supplier_gstin, match_category, confidence, match_score, explanation,
       action, action_by, action_at)
      VALUES (v_tenant, v_rec, v_row2, v_inv2, '29AAACR5055K1ZP', 'number_mismatch',
              'medium', 75, 'INV-002 vs INV/002.', 'accepted', v_user, now());
    v_human_ok := true;
  EXCEPTION WHEN OTHERS THEN
    v_human_ok := false;
    RAISE NOTICE 'human accept refused: %', SQLERRM;
  END;

  IF v_exact_ok AND v_silent_refused AND v_human_ok THEN
    RAISE NOTICE 'PASS: ⭐ an EXACT match may be accepted by the engine, anything '
                 'below it may not be accepted without a named human, and a person '
                 'can still accept it.';
  ELSIF NOT v_exact_ok THEN
    RAISE WARNING '*** FAIL — an EXACT match could not be accepted automatically, so '
                  'every one of several thousand perfect matches needs a click. The '
                  'worklist becomes unusable and the real exceptions are lost in it. ***';
  ELSIF NOT v_silent_refused THEN
    RAISE WARNING '*** FAIL — ⭐⭐ A MATCH BELOW EXACT WAS ACCEPTED WITH NOBODY NAMED '
                  'AGAINST IT. That is a year of matches no person looked at, found '
                  'at the one assessment where the answer to "who decided this" has '
                  'to be a person. ***';
  ELSE
    RAISE WARNING '*** FAIL — a person could not accept a proposed match. The '
                  'workbench cannot be used at all. ***';
  END IF;

  RAISE EXCEPTION 'verification rollback';
EXCEPTION WHEN OTHERS THEN
  IF SQLERRM <> 'verification rollback' THEN
    RAISE WARNING '*** FAIL — verification could not run: % ***', SQLERRM;
  END IF;
END
$$;


-- Check 8 — ⭐⭐ THE SUMMARY MUST ADD UP, AND ONE INVOICE MAY NOT BE MATCHED
-- TWICE.
--
-- ⚠️ `SET CONSTRAINTS … IMMEDIATE` IS WHAT MAKES THE SECOND HALF MEAN
-- ANYTHING. The summary guard is DEFERRABLE INITIALLY DEFERRED, so it fires at
-- COMMIT — and this whole DO block ends in a deliberate rollback, so COMMIT
-- never happens and the offending row would appear to succeed. Forcing the
-- constraint IMMEDIATE inside the sub-block fires the pending events there.
--
-- ⚠️ AND THE INSERT AND THE `SET CONSTRAINTS` MUST BE IN THE **SAME** plpgsql
-- BEGIN…EXCEPTION BLOCK. When a subtransaction aborts, the after-trigger events
-- queued inside it are discarded; events queued OUTSIDE it are not, and would
-- fire again at the block's own rollback and surface as an unrelated failure.
DO $$
DECLARE
  v_tenant    uuid := gen_random_uuid();
  v_rec       uuid := gen_random_uuid();
  v_doc       uuid := gen_random_uuid();
  v_row       uuid := gen_random_uuid();
  v_vendor    uuid := gen_random_uuid();
  v_inv1      uuid := gen_random_uuid();
  v_inv2      uuid := gen_random_uuid();
  v_identity_refused boolean := false;
  v_twice_refused    boolean := false;
  v_agrees_refused   boolean := false;
BEGIN
  INSERT INTO tenants (id, clerk_org_id, slug, name, status)
    VALUES (v_tenant, 'org_2bsum_' || v_tenant, 'sum-' || left(v_tenant::text, 8),
            'GSTR-2B summary verification', 'active');
  INSERT INTO vendors (id, tenant_id, code, legal_name)
    VALUES (v_vendor, v_tenant, 'V-SUM', 'Verification Supplier');
  INSERT INTO gstr2b_documents
    (id, tenant_id, gstin, return_period, source_format, file_hash, raw_document)
    VALUES (v_doc, v_tenant, '27AAACR5055K1ZQ', '2024-07', 'portal_json',
            repeat('f', 64), '{"data":{"gstin":"x"}}'::jsonb);
  INSERT INTO gstr2b_rows
    (id, tenant_id, document_id, section, supplier_gstin, invoice_number,
     normalised_number, invoice_date, taxable_value_minor, cgst_minor, sgst_minor)
    VALUES (v_row, v_tenant, v_doc, 'b2b', '29AAACR5055K1ZP', 'INV-001', 'INV1',
            DATE '2024-07-05', 10000000, 900000, 900000);
  INSERT INTO purchase_invoices
    (id, tenant_id, vendor_id, supplier_gstin, invoice_number, invoice_date,
     subtotal_minor, taxable_value_minor, cgst_minor, sgst_minor, total_minor,
     itc_eligible_tax_minor)
    VALUES
    (v_inv1, v_tenant, v_vendor, '29AAACR5055K1ZP', 'INV-001', DATE '2024-07-05',
     10000000, 10000000, 900000, 900000, 11800000, 1800000),
    (v_inv2, v_tenant, v_vendor, '29AAACR5055K1ZP', 'INV-009', DATE '2024-07-09',
     10000000, 10000000, 900000, 900000, 11800000, 1800000);

  -- ⭐ A summary whose books total does not equal matched + unmatched.
  -- MUST be refused by the CHECK, immediately.
  BEGIN
    INSERT INTO gstr2b_reconciliations
      (tenant_id, gstin, tax_period, status,
       books_tax_minor, matched_books_tax_minor, in_books_not_in_2b_tax_minor)
      VALUES (v_tenant, '27AAACR5055K1ZQ', '2024-09', 'in_progress',
              3600000, 1800000, 900000);
  EXCEPTION WHEN OTHERS THEN
    v_identity_refused := true;
  END;

  INSERT INTO gstr2b_reconciliations
    (id, tenant_id, gstin, tax_period, document_id, status,
     books_tax_minor, matched_books_tax_minor, in_books_not_in_2b_tax_minor,
     twob_tax_minor, matched_twob_tax_minor, matched_count)
    VALUES (v_rec, v_tenant, '27AAACR5055K1ZQ', '2024-07', v_doc, 'in_progress',
            3600000, 1800000, 1800000, 1800000, 1800000, 1);

  INSERT INTO gstr2b_matches
    (tenant_id, reconciliation_id, gstr2b_row_id, purchase_invoice_id,
     supplier_gstin, match_category, confidence, match_score, explanation)
    VALUES (v_tenant, v_rec, v_row, v_inv1, '29AAACR5055K1ZP', 'exact', 'exact',
            100, 'Every field agrees.');
  INSERT INTO gstr2b_matches
    (tenant_id, reconciliation_id, purchase_invoice_id, supplier_gstin,
     match_category, confidence, match_score, explanation, itc_at_risk_minor)
    VALUES (v_tenant, v_rec, v_inv2, '29AAACR5055K1ZP', 'in_books_not_in_2b',
            'none', 0, 'The supplier has not filed this invoice.', 1800000);

  -- ⭐ The SAME 2B row matched to a SECOND purchase invoice. Both rows look
  -- ordinary. MUST be refused by the one-to-one index.
  BEGIN
    INSERT INTO gstr2b_matches
      (tenant_id, reconciliation_id, gstr2b_row_id, purchase_invoice_id,
       supplier_gstin, match_category, confidence, match_score, explanation)
      VALUES (v_tenant, v_rec, v_row, v_inv2, '29AAACR5055K1ZP', 'probable',
              'high', 90, 'Same supplier and number.');
  EXCEPTION WHEN OTHERS THEN
    v_twice_refused := true;
  END;

  -- ⭐ And a summary that claims figures its own matches do not support.
  BEGIN
    UPDATE gstr2b_reconciliations
       SET books_tax_minor = 5400000,
           matched_books_tax_minor = 1800000,
           in_books_not_in_2b_tax_minor = 3600000
     WHERE id = v_rec;
    SET CONSTRAINTS gstr2b_reconciliations_summary_agrees,
                    gstr2b_matches_summary_agrees IMMEDIATE;
    SET CONSTRAINTS gstr2b_reconciliations_summary_agrees,
                    gstr2b_matches_summary_agrees DEFERRED;
  EXCEPTION WHEN OTHERS THEN
    v_agrees_refused := true;
  END;

  IF v_identity_refused AND v_twice_refused AND v_agrees_refused THEN
    RAISE NOTICE 'PASS: ⭐ a summary that does not add up is refused, one 2B row '
                 'cannot be matched to two purchase invoices, and the stored totals '
                 'must describe the matches actually held.';
  ELSIF NOT v_identity_refused THEN
    RAISE WARNING '*** FAIL — ⭐⭐ A SUMMARY THAT DOES NOT ADD UP WAS ACCEPTED. An '
                  'invoice is then in no bucket, "in books, not in 2B" is smaller '
                  'than it should be, and that reads as GOOD NEWS — fewer suppliers '
                  'to chase. The credit is claimed under Section 16(2)(aa) with '
                  'nothing behind it. ***';
  ELSIF NOT v_twice_refused THEN
    RAISE WARNING '*** FAIL — one GSTR-2B row was matched to TWO purchase invoices. '
                  'Both rows look ordinary; the matched total exceeds the books '
                  'total and one supplier drops off the chase list. ***';
  ELSE
    RAISE WARNING '*** FAIL — a reconciliation''s stored totals were allowed to '
                  'disagree with its own match rows, so the summary describes a '
                  'reconciliation that does not exist. ***';
  END IF;

  RAISE EXCEPTION 'verification rollback';
EXCEPTION WHEN OTHERS THEN
  IF SQLERRM <> 'verification rollback' THEN
    RAISE WARNING '*** FAIL — verification could not run: % ***', SQLERRM;
  END IF;
END
$$;


-- Check 9 — the app role cannot DELETE the evidence.
SELECT
  t.table_name, t.privilege_type,
  '*** FAIL — DELETE granted: the only artefact the customer cannot reconstruct '
  'from their own paper can be erased ***' AS verdict
FROM information_schema.role_table_grants t
WHERE t.grantee = 'ordence_app'
  AND t.privilege_type = 'DELETE'
  AND t.table_name IN ('gstr2b_documents','gstr2b_reconciliations');
-- (No rows returned = PASS.)


-- Check 10 — nothing points across a tenant boundary TODAY.
SELECT 'gstr2b rows → documents' AS relationship, count(*) AS violations,
       CASE WHEN count(*) = 0 THEN 'PASS' ELSE '*** FAIL ***' END AS verdict
  FROM gstr2b_rows r JOIN gstr2b_documents d ON d.id = r.document_id
 WHERE r.tenant_id <> d.tenant_id
UNION ALL
SELECT 'matches → reconciliations', count(*),
       CASE WHEN count(*) = 0 THEN 'PASS' ELSE '*** FAIL ***' END
  FROM gstr2b_matches m JOIN gstr2b_reconciliations c ON c.id = m.reconciliation_id
 WHERE m.tenant_id <> c.tenant_id
UNION ALL
SELECT 'matches → purchase invoices', count(*),
       CASE WHEN count(*) = 0 THEN 'PASS' ELSE '*** FAIL ***' END
  FROM gstr2b_matches m JOIN purchase_invoices i ON i.id = m.purchase_invoice_id
 WHERE m.tenant_id <> i.tenant_id
UNION ALL
SELECT 'matches → gstr2b rows', count(*),
       CASE WHEN count(*) = 0 THEN 'PASS' ELSE '*** FAIL ***' END
  FROM gstr2b_matches m JOIN gstr2b_rows r ON r.id = m.gstr2b_row_id
 WHERE m.tenant_id <> r.tenant_id;


-- Check 11 — ⭐ every reconciliation in the database adds up TODAY.
-- Belt and braces: if the CHECKs were added after data existed, a wrong row
-- could predate them. This is the single query an auditor would run first.
SELECT
  CASE WHEN count(*) = 0
       THEN 'PASS: every GSTR-2B reconciliation balances on both sides'
       ELSE '*** FAIL — ' || count(*) || ' reconciliation(s) do not balance. An '
            'invoice is in no bucket or in two, and the credit at risk is '
            'misstated in the direction that looks like good news. ***'
  END AS check_summaries_balance
FROM gstr2b_reconciliations
WHERE books_tax_minor <> matched_books_tax_minor + in_books_not_in_2b_tax_minor
   OR twob_tax_minor  <> matched_twob_tax_minor + in_2b_not_in_books_tax_minor;


-- Check 12 — ⭐ no match anywhere has been accepted below EXACT with nobody
-- named against it.
SELECT
  CASE WHEN count(*) = 0
       THEN 'PASS: every accepted match below EXACT names the person who accepted it'
       ELSE '*** FAIL — ' || count(*) || ' match(es) below EXACT are ACCEPTED with '
            'no person named. At an assessment the answer to "who decided this" is '
            '"nobody did". ***'
  END AS check_no_silent_accepts
FROM gstr2b_matches
WHERE action = 'accepted' AND match_category <> 'exact' AND action_by IS NULL;


-- Check 13 — ⭐ a support session cannot DELETE GSTR-2B evidence.
SELECT
  expected.tbl,
  CASE WHEN t.tgname IS NOT NULL THEN 'PASS'
       ELSE '*** FAIL — an impersonating operator can delete from this table. For '
            'gstr2b_documents that destroys the only artefact the customer cannot '
            'reconstruct, and the portal will not serve the same generation twice ***'
  END AS verdict
FROM (VALUES
  ('gstr2b_documents'), ('gstr2b_rows'),
  ('gstr2b_reconciliations'), ('gstr2b_matches')
) AS expected(tbl)
LEFT JOIN pg_trigger t
       ON t.tgname = 'no_delete_under_impersonation'
      AND t.tgrelid = expected.tbl::regclass
      AND NOT t.tgisinternal
ORDER BY expected.tbl;


-- Check 14 — the change log covers this phase, ALL FOUR TABLES.
-- ⚠️ Including `gstr2b_rows`. The change log is not only evidence, it is how a
-- tenant-scoped table SYNCS — a table without the trigger simply never
-- replicates, silently, until data is missing on one machine and present on
-- another.
SELECT
  expected.tbl,
  CASE WHEN t.tgname IS NOT NULL THEN 'PASS'
       ELSE '*** FAIL — changes here are not recorded and could never sync ***'
  END AS verdict
FROM (VALUES
  ('gstr2b_documents'), ('gstr2b_rows'),
  ('gstr2b_reconciliations'), ('gstr2b_matches')
) AS expected(tbl)
LEFT JOIN pg_trigger t
       ON t.tgname = expected.tbl || '_change_log'
      AND t.tgrelid = expected.tbl::regclass
      AND NOT t.tgisinternal
ORDER BY expected.tbl;


-- Check 15 — the one-to-one match indexes exist.
SELECT
  expected.indexname,
  CASE WHEN i.indexname IS NOT NULL THEN 'PASS'
       ELSE '*** FAIL: MISSING — a re-run can match one document to two, the '
            'matched total exceeds the books total, and a supplier drops off the '
            'chase list ***'
  END AS verdict
FROM (VALUES
  ('gstr2b_matches_one_per_2b_row'),
  ('gstr2b_matches_one_per_invoice'),
  ('gstr2b_documents_identity_unique'),
  ('gstr2b_reconciliations_period_unique')
) AS expected(indexname)
LEFT JOIN pg_indexes i ON i.indexname = expected.indexname
ORDER BY expected.indexname;
