-- =====================================================================
--  ORDENCE , WHAT IS ACTUALLY ON THIS DATABASE, AND WHAT TO RUN NEXT
--  GENERATED by scripts/generate-pending-checker.mjs. Do not hand-edit;
--  edit the migrations or pending-probe-overrides.json and regenerate.
--  Covers 154 migrations: 0001 to 0168.
-- =====================================================================
--
--  READ ONLY. SAFE ON PRODUCTION. SAFE ON NEON. Every statement is a
--  SELECT. Nothing is created, altered, dropped, granted or written.
--
--  It cannot read a ledger, so for each migration it asks whether the
--  artefact that ONLY that migration creates exists right now.
--  Policies, triggers, functions and views are used deliberately:
--  drizzle-kit push creates none of them, and an earlier checker that
--  probed tables and columns reported twelve files as applied on a
--  database that had never seen them.
--
--    PRESENT      the artefact exists. In practice the file ran.
--    MISSING      the file did not run, or ran and failed early.
--    UNPROBEABLE  no probe can answer it. See the notes beside each.
--
--  ⚠️ THESE FILES CANNOT BE PROVEN COMPLETE BY ANY PROBE:
--    0013, 0122, 0125, 0128, 0129, 0130, 0131, 0132, 0134, 0137, 0138, 0140, 0146, 0147, 0148, 0149, 0150, 0155, 0158
--    Their last catalogue artefact sits early and they RAISE after it, so
--    a PRESENT here means "it started". Run the VERIFY-00NN file beside
--    each before believing it. This list is computed, not maintained.
--
--  It cannot prove a migration ran COMPLETELY. A file that created its
--  first object then failed on statement forty reads PRESENT. Run the
--  VERIFY-00NN file beside the highest PRESENT number before trusting it.
-- =====================================================================

WITH probes(num, file_name, looked_for, how, present) AS (VALUES
  ('0001', '0001_rls_and_audit_guard.sql', 'trigger roles_set_updated_at', 'object', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='roles_set_updated_at'))),
  ('0002', '0002_phase2_rls.sql', 'trigger cor_set_updated_at', 'object', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='cor_set_updated_at'))),
  ('0003', '0003_phase3_rls.sql', 'trigger assets_set_updated_at', 'object', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='assets_set_updated_at'))),
  ('0005', '0005_phase5_controls.sql', 'trigger financial_periods_set_updated_at', 'object', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='financial_periods_set_updated_at'))),
  ('0006', '0006_phase8_storage.sql', 'trigger documents_parent_immutable', 'object', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='documents_parent_immutable'))),
  ('0007', '0007_phase9_portals.sql', 'trigger contract_signatures_no_delete', 'object', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='contract_signatures_no_delete'))),
  ('0008', '0008_phase10_analytics.sql', 'view v_asset_portfolio (v_asset_portfolio is re-created by a later file, so no artefact is unique to 0008)', 'object', (to_regclass('public.v_asset_portfolio') IS NOT NULL)),
  ('0009', '0009_phase11_billing.sql', 'trigger subscriptions_tenant_fixed', 'object', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='subscriptions_tenant_fixed'))),
  ('0011', '0011_phase19_telemetry.sql', 'function telemetry_retention_sweep()', 'object', (EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='telemetry_retention_sweep'))),
  ('0012', '0012_phase20_secops.sql', 'trigger security_events_no_delete', 'object', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='security_events_no_delete'))),
  ('0013', '0013_phase15_metering.sql', 'trigger usage_levels_identity_fixed', 'object', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='usage_levels_identity_fixed'))),
  ('0014', '0014_phase17_platform.sql', 'function app_platform_scope()', 'object', (EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='app_platform_scope'))),
  ('0015', '0015_phase16_invoicing.sql', 'function invoice_sequence_is_sane()', 'object', (EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='invoice_sequence_is_sane'))),
  ('0016', '0016_phase22_sales.sql', 'trigger payment_milestones_set_updated_at', 'object', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='payment_milestones_set_updated_at'))),
  ('0017', '0017_change_log.sql', 'policy change_log_tenant_isolation on change_log', 'object', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='change_log' AND policyname='change_log_tenant_isolation'))),
  ('0018', '0018_phase23_workflows.sql', 'trigger workflow_tasks_set_updated_at', 'object', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='workflow_tasks_set_updated_at'))),
  ('0019', '0019_phase24_dynamic_objects.sql', 'trigger dynamic_fields_set_updated_at', 'object', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='dynamic_fields_set_updated_at'))),
  ('0020', '0020_phase25_views.sql', 'trigger saved_view_defaults_set_updated_at', 'object', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='saved_view_defaults_set_updated_at'))),
  ('0021', '0021_phase32_gst.sql', 'trigger hsn_sac_rates_set_updated_at', 'object', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='hsn_sac_rates_set_updated_at'))),
  ('0022', '0022_phase29_admin_console.sql', 'constraint platform_action_justification_length', 'object-weak', (EXISTS (SELECT 1 FROM pg_constraint WHERE conname='platform_action_justification_length'))),
  ('0023', '0023_phase33_purchases.sql', 'function itc_claim_deadline_period()', 'object', (EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='itc_claim_deadline_period'))),
  ('0024', '0024_phase34_gstr2b.sql', 'trigger gstr2b_matches_within_statement', 'object', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='gstr2b_matches_within_statement'))),
  ('0025', '0025_phase36_tds.sql', 'function tds_return_due_date()', 'object', (EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='tds_return_due_date'))),
  ('0026', '0026_phase37_tally.sql', 'function tally_batch_matches_its_vouchers()', 'object', (EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='tally_batch_matches_its_vouchers'))),
  ('0027', '0027_phase38_receivables.sql', 'trigger demand_notices_frozen_once_issued', 'object', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='demand_notices_frozen_once_issued'))),
  ('0028', '0028_phase39_orders.sql', 'trigger trg_touch_sales_order_fulfillments', 'object', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='trg_touch_sales_order_fulfillments'))),
  ('0029', '0029_phase40_inventory.sql', 'trigger trg_refresh_reserved_quantity', 'object', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='trg_refresh_reserved_quantity'))),
  ('0030', '0030_phase42_land.sql', 'trigger trg_guard_heir_shares', 'object', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='trg_guard_heir_shares'))),
  ('0031', '0031_phase44_ra_bills.sql', 'trigger trg_guard_retention_release', 'object', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='trg_guard_retention_release'))),
  ('0032', '0032_engine4_compliance.sql', 'view v_compliance_licence_board', 'object', (EXISTS (SELECT 1 FROM pg_views WHERE schemaname='public' AND viewname='v_compliance_licence_board'))),
  ('0033', '0033_engine1_scheduling.sql', 'view v_schedule_utilisation', 'object', (EXISTS (SELECT 1 FROM pg_views WHERE schemaname='public' AND viewname='v_schedule_utilisation'))),
  ('0034', '0034_engine2_pricing.sql', 'function ordence_select_rate_card()', 'object', (EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='ordence_select_rate_card'))),
  ('0035', '0035_engine5_metering.sql', 'view v_meter_estimates_outstanding', 'object', (EXISTS (SELECT 1 FROM pg_views WHERE schemaname='public' AND viewname='v_meter_estimates_outstanding'))),
  ('0036', '0036_engine3_field_ops.sql', 'view v_field_technician_performance', 'object', (EXISTS (SELECT 1 FROM pg_views WHERE schemaname='public' AND viewname='v_field_technician_performance'))),
  ('0037', '0037_engine6_vault.sql', 'view v_vault_access_summary', 'object', (EXISTS (SELECT 1 FROM pg_views WHERE schemaname='public' AND viewname='v_vault_access_summary'))),
  ('0038', '0038_construction_labour.sql', 'view v_site_labour_summary', 'object', (EXISTS (SELECT 1 FROM pg_views WHERE schemaname='public' AND viewname='v_site_labour_summary'))),
  ('0039', '0039_tables_paste_only.sql', 'table rate_cards', 'object-weak', (EXISTS (SELECT 1 FROM pg_tables WHERE schemaname='public' AND tablename='rate_cards'))),
  ('0040', '0040_stock_reservation_floor.sql', 'view v_stock_over_committed', 'object', (EXISTS (SELECT 1 FROM pg_views WHERE schemaname='public' AND viewname='v_stock_over_committed'))),
  ('0041', '0041_contracting_depth.sql', 'view v_boq_billing_position', 'object', (EXISTS (SELECT 1 FROM pg_views WHERE schemaname='public' AND viewname='v_boq_billing_position'))),
  ('0042', '0042_mcp_access.sql', 'view v_mcp_activity', 'object', (EXISTS (SELECT 1 FROM pg_views WHERE schemaname='public' AND viewname='v_mcp_activity'))),
  ('0043', '0043_engine1_engine4_tables.sql', 'table compliance_obligations', 'object-weak', (EXISTS (SELECT 1 FROM pg_tables WHERE schemaname='public' AND tablename='compliance_obligations'))),
  ('0044', '0044_tenant_patterns.sql', 'policy tenant_patterns_tenant_isolation on tenant_patterns', 'object', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='tenant_patterns' AND policyname='tenant_patterns_tenant_isolation'))),
  ('0045', '0045_notifications.sql', 'policy notifications_tenant_isolation on notifications', 'object', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='notifications' AND policyname='notifications_tenant_isolation'))),
  ('0046', '0046_deployment_flows_governance.sql', 'constraint deployment_backups_release_fkey', 'object-weak', (EXISTS (SELECT 1 FROM pg_constraint WHERE conname='deployment_backups_release_fkey'))),
  ('0047', '0047_grant_missing_views.sql', 'grant: SELECT on v_boq_billing_position to ordence_app', 'privilege', (EXISTS (SELECT 1 FROM information_schema.role_table_grants WHERE table_schema='public' AND table_name='v_boq_billing_position' AND grantee='ordence_app' AND privilege_type='SELECT'))),
  ('0048', '0048_credit_limits.sql', 'policy approval_limits_tenant_isolation on approval_limits', 'object', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='approval_limits' AND policyname='approval_limits_tenant_isolation'))),
  ('0049', '0049_sales_invoices.sql', 'policy customer_receipt_allocations_tenant_isolation on customer_receipt_allocations', 'object', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='customer_receipt_allocations' AND policyname='customer_receipt_allocations_tenant_isolation'))),
  ('0050', '0050_sales_credit_notes.sql', 'policy sales_credit_note_lines_tenant_isolation on sales_credit_note_lines', 'object', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='sales_credit_note_lines' AND policyname='sales_credit_note_lines_tenant_isolation'))),
  ('0051', '0051_sales_posting_accounts.sql', 'policy sales_posting_accounts_tenant_isolation on sales_posting_accounts', 'object', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='sales_posting_accounts' AND policyname='sales_posting_accounts_tenant_isolation'))),
  ('0052', '0052_booking_possession.sql', 'constraint bookings_possession_not_cancelled', 'object-weak', (EXISTS (SELECT 1 FROM pg_constraint WHERE conname='bookings_possession_not_cancelled'))),
  ('0053', '0053_time_and_billing.sql', 'policy time_entries_tenant_isolation on time_entries', 'object', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='time_entries' AND policyname='time_entries_tenant_isolation'))),
  ('0054', '0054_eway_bills.sql', 'policy eway_bill_items_tenant_isolation on eway_bill_items', 'object', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='eway_bill_items' AND policyname='eway_bill_items_tenant_isolation'))),
  ('0055', '0055_batch_serial_returns.sql', 'policy stock_write_offs_tenant_isolation on stock_write_offs', 'object', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='stock_write_offs' AND policyname='stock_write_offs_tenant_isolation'))),
  ('0056', '0056_transfers_landed_cost.sql', 'policy landed_cost_allocations_tenant_isolation on landed_cost_allocations', 'object', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='landed_cost_allocations' AND policyname='landed_cost_allocations_tenant_isolation'))),
  ('0057', '0057_pricing_discounts.sql', 'policy post_supply_discount_invoices_tenant_isolation on post_supply_discount_invoices', 'object', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='post_supply_discount_invoices' AND policyname='post_supply_discount_invoices_tenant_isolation'))),
  ('0058', '0058_legal_matters.sql', 'policy client_account_entries_tenant_isolation on client_account_entries', 'object', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='client_account_entries' AND policyname='client_account_entries_tenant_isolation'))),
  ('0059', '0059_court_fees_disbursements.sql', 'policy legal_client_tax_status_tenant_isolation on legal_client_tax_status', 'object', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='legal_client_tax_status' AND policyname='legal_client_tax_status_tenant_isolation'))),
  ('0060', '0060_tasks_activities_calendar.sql', 'policy calendar_event_attendees_tenant_isolation on calendar_event_attendees', 'object', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='calendar_event_attendees' AND policyname='calendar_event_attendees_tenant_isolation'))),
  ('0061', '0061_crm_consent_messaging.sql', 'policy messages_tenant_isolation on messages', 'object', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='messages' AND policyname='messages_tenant_isolation'))),
  ('0063', '0063_purchase_orders_payments.sql', 'policy vendor_payment_allocations_tenant_isolation on vendor_payment_allocations', 'object', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='vendor_payment_allocations' AND policyname='vendor_payment_allocations_tenant_isolation'))),
  ('0064', '0064_integration_frame.sql', 'policy webhook_deliveries_tenant_isolation on webhook_deliveries', 'object', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='webhook_deliveries' AND policyname='webhook_deliveries_tenant_isolation'))),
  ('0065', '0065_lead_intake.sql', 'policy lead_intake_failures_tenant_isolation on lead_intake_failures', 'object', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='lead_intake_failures' AND policyname='lead_intake_failures_tenant_isolation'))),
  ('0066', '0066_utility_messaging.sql', 'policy message_sends_tenant_isolation on message_sends', 'object', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='message_sends' AND policyname='message_sends_tenant_isolation'))),
  ('0067', '0067_campaigns.sql', 'policy campaign_recipients_tenant_isolation on campaign_recipients', 'object', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='campaign_recipients' AND policyname='campaign_recipients_tenant_isolation'))),
  ('0068', '0068_order_rhythm.sql', 'policy automation_events_tenant_isolation on automation_events', 'object', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='automation_events' AND policyname='automation_events_tenant_isolation'))),
  ('0069', '0069_connection_probes.sql', 'trigger ordence_guard_probe_scope', 'object', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='ordence_guard_probe_scope'))),
  ('0070', '0070_bank_reconciliation.sql', 'trigger ordence_guard_posted_count', 'object', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='ordence_guard_posted_count'))),
  ('0071', '0071_tenant_agents.sql', 'trigger ordence_guard_agent_autonomy', 'object', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='ordence_guard_agent_autonomy'))),
  ('0073', '0073_period_lock_and_reorder.sql', 'index stock_items_vendor_idx', 'object-weak', (EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname='public' AND indexname='stock_items_vendor_idx'))),
  ('0074', '0074_platform_control.sql', 'trigger ordence_guard_self_approval', 'object', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='ordence_guard_self_approval'))),
  ('0075', '0075_payroll.sql', 'trigger ordence_guard_payroll_status', 'object', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='ordence_guard_payroll_status'))),
  ('0077', '0077_monthly_return.sql', 'policy gst_returns_isolation on gst_returns', 'object', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='gst_returns' AND policyname='gst_returns_isolation'))),
  ('0078', '0078_real_estate_completion.sql', 'policy cp_commissions_isolation on channel_partner_commissions', 'object', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='channel_partner_commissions' AND policyname='cp_commissions_isolation'))),
  ('0079', '0079_rls_opt_in_and_telemetry.sql', 'security_events policy carries app_platform_scope in USING', 'content', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='security_events' AND policyname='security_events_tenant_isolation' AND qual LIKE '%app_platform_scope%'))),
  ('0080', '0080_orders_place_of_supply.sql', 'constraint sales_orders_immovable_property_pos', 'object-weak', (EXISTS (SELECT 1 FROM pg_constraint WHERE conname='sales_orders_immovable_property_pos'))),
  ('0081', '0081_audit_hash_chain.sql', 'function audit_chain_link_hash()', 'object', (EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='audit_chain_link_hash'))),
  ('0082', '0082_leave_and_attendance.sql', 'trigger staff_attendance_set_updated_at', 'object', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='staff_attendance_set_updated_at'))),
  ('0083', '0083_credit_control_and_dunning.sql', 'trigger credit_dunning_log_identity', 'object', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='credit_dunning_log_identity'))),
  ('0084', '0084_cost_centres_and_budgets.sql', 'trigger budget_lines_period_lock', 'object', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='budget_lines_period_lock'))),
  ('0085', '0085_appraisals_and_org.sql', 'trigger appraisal_reviews_set_updated_at', 'object', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='appraisal_reviews_set_updated_at'))),
  ('0086', '0086_policy_platform_platform_tables.sql', 'tenant_health_events policy restored to the house form', 'content', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND policyname='tenant_health_events_platform_only' AND qual LIKE '%IS NULL) OR app_platform_scope%'))),
  ('0087', '0087_hardening_narrow_grants.sql', 'NOT PROBEABLE , run VERIFY-0087-neon-safe.sql', 'manual', (NULL::boolean)),
  ('0088', '0088_hardening_auth_events.sql', 'enum security_event_type carries the value ''auth.account_created''', 'object-weak', (EXISTS (SELECT 1 FROM pg_enum e JOIN pg_type t ON t.oid=e.enumtypid WHERE t.typname='security_event_type' AND e.enumlabel='auth.account_created'))),
  ('0089', '0089_hardening_login_lockouts.sql', 'policy login_lockouts_write_platform on login_lockouts', 'object', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='login_lockouts' AND policyname='login_lockouts_write_platform'))),
  ('0090', '0090_period_close_message_normalization.sql', 'function enforce_period_close() contains "FROM public.transactions"', 'content', (EXISTS (SELECT 1 FROM pg_proc WHERE proname='enforce_period_close' AND position('FROM public.transactions' in prosrc) > 0))),
  ('0091', '0091_slug_authority.sql', 'trigger ordence_guard_tenant_slug', 'object', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='ordence_guard_tenant_slug'))),
  ('0093', '0093_user_notification_preferences.sql', 'users.preferences , ALSO created by drizzle-kit push, so cannot be distinguished', 'indistinguishable', (NULL::boolean)),
  ('0094', '0094_wage_payment_date_and_settlement.sql', 'policy employee_settlements_tenant_isolation on employee_settlements', 'object', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='employee_settlements' AND policyname='employee_settlements_tenant_isolation'))),
  ('0095', '0095_employee_tax_regime_elections.sql', 'employees.tax_regime_elections , ALSO created by drizzle-kit push', 'indistinguishable', (NULL::boolean)),
  ('0096', '0096_advances_loans_and_reimbursements.sql', 'policy employee_reimbursement_claims_tenant_isolation on employee_reimbursement_claims', 'object', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='employee_reimbursement_claims' AND policyname='employee_reimbursement_claims_tenant_isolation'))),
  ('0097', '0097_email_outbox_and_suppressions.sql', 'policy email_suppressions_tenant_isolation on email_suppressions', 'object', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='email_suppressions' AND policyname='email_suppressions_tenant_isolation'))),
  ('0098', '0098_dunning_service_evidence.sql', 'constraint dunning_events_service_recorder_fk', 'object-weak', (EXISTS (SELECT 1 FROM pg_constraint WHERE conname='dunning_events_service_recorder_fk'))),
  ('0099', '0099_stock_movement_valuation.sql', 'function ordence_validate_stock_movement() contains "SELECT id, name, uom, tenant_id INTO ite"', 'content', (EXISTS (SELECT 1 FROM pg_proc WHERE proname='ordence_validate_stock_movement' AND position('SELECT id, name, uom, tenant_id INTO item' in prosrc) > 0))),
  ('0100', '0100_fixed_asset_register_and_depreciation.sql', 'policy depreciation_lines_tenant_isolation on depreciation_lines', 'object', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='depreciation_lines' AND policyname='depreciation_lines_tenant_isolation'))),
  ('0101', '0101_multi_currency_and_fx.sql', 'policy fx_revaluation_lines_tenant_isolation on fx_revaluation_lines', 'object', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='fx_revaluation_lines' AND policyname='fx_revaluation_lines_tenant_isolation'))),
  ('0102', '0102_bank_reconciliation_statement_and_lock.sql', 'policy bank_reconciliation_items_tenant on bank_reconciliation_items', 'object', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='bank_reconciliation_items' AND policyname='bank_reconciliation_items_tenant'))),
  ('0104', '0104_analytics_views_carry_currency.sql', 'view v_ledger_daily carries a currency column', 'content', (EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='v_ledger_daily' AND column_name='currency'))),
  ('0105', '0105_per_tenant_ai_provider_credentials.sql', 'policy ai_provider_credentials_tenant_isolation on ai_provider_credentials', 'object', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='ai_provider_credentials' AND policyname='ai_provider_credentials_tenant_isolation'))),
  ('0106', '0106_tds_foreign_payments_rule_26.sql', 'constraint fx_reference_rates_rate_type_known', 'object-weak', (EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fx_reference_rates_rate_type_known'))),
  ('0108', '0108_journal_entries_minor_units.sql', 'function enforce_double_entry_balance()', 'object', (EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='enforce_double_entry_balance'))),
  ('0109', '0109_payroll_entitlement_grandfather.sql', 'CONDITIONAL , only writes a row for basic-tier tenants already using payroll', 'conditional', (NULL::boolean)),
  ('0110', '0110_bank_allocation_and_bank_charge_itc.sql', 'trigger ordence_guard_reconciled_statement_delete', 'object', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='ordence_guard_reconciled_statement_delete'))),
  ('0111', '0111_deemed_service_and_notice_authority.sql', 'constraint dunning_events_deemed_states_its_basis', 'object-weak', (EXISTS (SELECT 1 FROM pg_constraint WHERE conname='dunning_events_deemed_states_its_basis'))),
  ('0112', '0112_bank_charge_itc_posting.sql', 'trigger ordence_guard_posted_itc_deferral', 'object', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='ordence_guard_posted_itc_deferral'))),
  ('0113', '0113_dpdp_data_principal_requests.sql', 'policy personal_data_breaches_tenant_isolation on personal_data_breaches', 'object', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='personal_data_breaches' AND policyname='personal_data_breaches_tenant_isolation'))),
  ('0114', '0114_seat_grants_and_pending_seats.sql', 'trigger ordence_guard_resolved_seat_request', 'object', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='ordence_guard_resolved_seat_request'))),
  ('0115', '0115_ai_credential_policy_and_usage.sql', 'trigger ordence_guard_ai_usage_append_only', 'object', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='ordence_guard_ai_usage_append_only'))),
  ('0116', '0116_data_exports.sql', 'trigger ordence_guard_data_exports_append_only', 'object', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='ordence_guard_data_exports_append_only'))),
  ('0117', '0117_import_runs_and_mapping.sql', 'trigger ordence_guard_import_chunks_append_only', 'object', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='ordence_guard_import_chunks_append_only'))),
  ('0118', '0118_drawing_register.sql', 'trigger ordence_guard_drawing_measurements', 'object', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='ordence_guard_drawing_measurements'))),
  ('0119', '0119_rate_limit_counters.sql', 'function ordence_rate_limit_sweep()', 'object', (EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='ordence_rate_limit_sweep'))),
  ('0120', '0120_schema_migrations.sql', 'table schema_migrations', 'object-weak', (EXISTS (SELECT 1 FROM pg_tables WHERE schemaname='public' AND tablename='schema_migrations'))),
  ('0121', '0121_revoke_prune_from_app_role.sql', 'ordence_app has NO EXECUTE on prune_security_events', 'privilege', (CASE WHEN NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='ordence_app') THEN NULL WHEN NOT EXISTS (SELECT 1 FROM pg_proc WHERE proname='prune_security_events') THEN FALSE ELSE NOT EXISTS (SELECT 1 FROM pg_proc p, aclexplode(p.proacl) a JOIN pg_roles r ON r.oid=a.grantee WHERE p.proname='prune_security_events' AND r.rolname='ordence_app' AND a.privilege_type='EXECUTE') END)),
  ('0122', '0122_change_log_coverage_sweep.sql', 'function attach_change_log_triggers()', 'object', (EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='attach_change_log_triggers'))),
  ('0123', '0123_dunning_chronology_uses_raised_at.sql', 'function dunning_ladder_has_no_gaps() contains "v_last_effective timestamptz;"', 'content', (EXISTS (SELECT 1 FROM pg_proc WHERE proname='dunning_ladder_has_no_gaps' AND position('v_last_effective timestamptz;' in prosrc) > 0))),
  ('0124', '0124_restore_stock_movement_checks.sql', 'stock validator has BOTH the tenant match and the reversal check', 'content', (EXISTS (SELECT 1 FROM pg_proc WHERE proname='ordence_validate_stock_movement' AND position('reverses_movement_id' in prosrc) > 0 AND position('tenant_id = NEW.tenant_id' in prosrc) > 0))),
  ('0125', '0125_impersonation_guard_coverage.sql', 'function attach_impersonation_guards()', 'object', (EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='attach_impersonation_guards'))),
  ('0127', '0127_dunning_log_delivery_writeback.sql', 'column UPDATE on credit_dunning_log.delivery to ordence_app', 'privilege', (EXISTS (SELECT 1 FROM information_schema.column_privileges WHERE table_schema='public' AND table_name='credit_dunning_log' AND column_name='delivery' AND grantee='ordence_app' AND privilege_type='UPDATE'))),
  ('0128', '0128_change_log_retention.sql', 'function prune_change_log()', 'object', (EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='prune_change_log'))),
  ('0129', '0129_scheduler_run_ledger.sql', 'policy scheduler_runs_platform_only on scheduler_runs', 'object', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='scheduler_runs' AND policyname='scheduler_runs_platform_only'))),
  ('0130', '0130_scheduler_control_plane.sql', 'function scheduler_pause_reason()', 'object', (EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='scheduler_pause_reason'))),
  ('0131', '0131_scheduler_watchdog.sql', 'function scheduler_reclaim_stale()', 'object', (EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='scheduler_reclaim_stale'))),
  ('0132', '0132_scheduler_retention_and_seal.sql', 'function prune_scheduler_runs()', 'object', (EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='prune_scheduler_runs'))),
  ('0133', '0133_request_outcomes.sql', 'function prune_request_outcomes()', 'object', (EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='prune_request_outcomes'))),
  ('0134', '0134_audit_event_stream.sql', 'view security_event_stream', 'object', (EXISTS (SELECT 1 FROM pg_views WHERE schemaname='public' AND viewname='security_event_stream'))),
  ('0135', '0135_observability_alerts.sql', 'function prune_observability_alerts()', 'object', (EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='prune_observability_alerts'))),
  ('0136', '0136_phase4_clm_and_ledger_isolation.sql', 'trigger journal_entries_update_balance', 'object', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='journal_entries_update_balance'))),
  ('0137', '0137_force_rls_and_isolation_posture.sql', 'function isolation_posture()', 'object', (EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='isolation_posture'))),
  ('0138', '0138_updated_at_consolidation.sql', 'function updated_at_census()', 'object', (EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='updated_at_census'))),
  ('0139', '0139_schema_contract_snapshot.sql', 'function diff_schema_contract()', 'object', (EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='diff_schema_contract'))),
  ('0140', '0140_tenant_table_drift_detector.sql', 'function assert_no_tenant_table_drift()', 'object', (EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='assert_no_tenant_table_drift'))),
  ('0141', '0141_retention_with_teeth.sql', 'prune_security_events takes older_than_days and dry_run (0141 rewrote the signature)', 'content', (EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='prune_security_events' AND pg_get_function_identity_arguments(p.oid) LIKE '%boolean%'))),
  ('0146', '0146_gst_rate_pin_integrity.sql', 'function gst_rate_usage()', 'object', (EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='gst_rate_usage'))),
  ('0147', '0147_gst_line_tax_recomputes.sql', 'trigger purchase_invoice_lines_gst_recomputes', 'object', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='purchase_invoice_lines_gst_recomputes'))),
  ('0148', '0148_gst_rate_pin_backfill.sql', 'function gst_backfill_rate_pins()', 'object', (EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='gst_backfill_rate_pins'))),
  ('0149', '0149_einvoice_irn_readiness.sql', 'trigger sales_invoices_irn_integrity', 'object', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='sales_invoices_irn_integrity'))),
  ('0150', '0150_tax_decision_trail.sql', 'view tax_decision_gaps', 'object', (EXISTS (SELECT 1 FROM pg_views WHERE schemaname='public' AND viewname='tax_decision_gaps'))),
  ('0151', '0151_perf_sales_invoices_due_date_index.sql', 'index sales_invoices_tenant_due_idx', 'object-weak', (EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname='public' AND indexname='sales_invoices_tenant_due_idx'))),
  ('0152', '0152_perf_audit_logs_keyset_index.sql', 'index audit_logs_tenant_keyset_idx', 'object-weak', (EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname='public' AND indexname='audit_logs_tenant_keyset_idx'))),
  ('0153', '0153_perf_change_log_tenant_index.sql', 'index change_log_tenant_changed_at_idx', 'object-weak', (EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname='public' AND indexname='change_log_tenant_changed_at_idx'))),
  ('0154', '0154_perf_contacts_live_index.sql', 'index contacts_tenant_live_idx', 'object-weak', (EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname='public' AND indexname='contacts_tenant_live_idx'))),
  ('0155', '0155_perf_index_health_function.sql', 'function ordence_index_health()', 'object', (EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='ordence_index_health'))),
  ('0156', '0156_perf_drop_duplicate_indexes.sql', 'NOT PROBEABLE , it only DROPS indexes. Absence cannot be told apart from never having existed.', 'manual', (NULL::boolean)),
  ('0157', '0157_perf_drop_redundant_tenant_indexes.sql', 'NOT PROBEABLE , same reason as 0156: a dropped index leaves nothing to find.', 'manual', (NULL::boolean)),
  ('0158', '0158_perf_slow_query_visibility.sql', 'function ordence_active_queries()', 'object', (EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='ordence_active_queries'))),
  ('0159', '0159_email_outbox_ceiling_and_terminal_evidence.sql', 'constraint email_outbox_max_attempts_check', 'object-weak', (EXISTS (SELECT 1 FROM pg_constraint WHERE conname='email_outbox_max_attempts_check'))),
  ('0160', '0160_email_outbox_claim_is_complete.sql', 'constraint email_outbox_claim_is_complete_check', 'object-weak', (EXISTS (SELECT 1 FROM pg_constraint WHERE conname='email_outbox_claim_is_complete_check'))),
  ('0166', '0166_security_event_types.sql', 'enum security_event_type carries the value ''billing.standing_unresolved''', 'object-weak', (EXISTS (SELECT 1 FROM pg_enum e JOIN pg_type t ON t.oid=e.enumtypid WHERE t.typname='security_event_type' AND e.enumlabel='billing.standing_unresolved'))),
  ('0168', '0168_audit_stream_comment_correction.sql', 'the COMMENT on view security_event_stream no longer says platform-scope raises are unrecorded , 0168 only rewrites a comment, so the comment text IS the artefact', 'content', ((EXISTS (SELECT 1 FROM pg_views WHERE schemaname='public' AND viewname='security_event_stream') AND coalesce(obj_description((SELECT c.oid FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relname='security_event_stream'),'pg_class'),'') NOT LIKE '%not recorded anywhere%')))
)
SELECT
  jsonb_pretty(jsonb_agg(jsonb_build_object(
    'num', num, 'status',
      CASE WHEN present IS NULL THEN 'UNPROBEABLE' WHEN present THEN 'PRESENT' ELSE 'MISSING' END,
    'how', how, 'file_name', file_name, 'looked_for', looked_for
  ) ORDER BY num)) AS section_2_every_migration
FROM probes;

WITH probes(num, file_name, present) AS (VALUES
  ('0001', '0001_rls_and_audit_guard.sql', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='roles_set_updated_at'))),
  ('0002', '0002_phase2_rls.sql', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='cor_set_updated_at'))),
  ('0003', '0003_phase3_rls.sql', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='assets_set_updated_at'))),
  ('0005', '0005_phase5_controls.sql', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='financial_periods_set_updated_at'))),
  ('0006', '0006_phase8_storage.sql', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='documents_parent_immutable'))),
  ('0007', '0007_phase9_portals.sql', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='contract_signatures_no_delete'))),
  ('0008', '0008_phase10_analytics.sql', (to_regclass('public.v_asset_portfolio') IS NOT NULL)),
  ('0009', '0009_phase11_billing.sql', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='subscriptions_tenant_fixed'))),
  ('0011', '0011_phase19_telemetry.sql', (EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='telemetry_retention_sweep'))),
  ('0012', '0012_phase20_secops.sql', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='security_events_no_delete'))),
  ('0013', '0013_phase15_metering.sql', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='usage_levels_identity_fixed'))),
  ('0014', '0014_phase17_platform.sql', (EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='app_platform_scope'))),
  ('0015', '0015_phase16_invoicing.sql', (EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='invoice_sequence_is_sane'))),
  ('0016', '0016_phase22_sales.sql', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='payment_milestones_set_updated_at'))),
  ('0017', '0017_change_log.sql', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='change_log' AND policyname='change_log_tenant_isolation'))),
  ('0018', '0018_phase23_workflows.sql', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='workflow_tasks_set_updated_at'))),
  ('0019', '0019_phase24_dynamic_objects.sql', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='dynamic_fields_set_updated_at'))),
  ('0020', '0020_phase25_views.sql', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='saved_view_defaults_set_updated_at'))),
  ('0021', '0021_phase32_gst.sql', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='hsn_sac_rates_set_updated_at'))),
  ('0022', '0022_phase29_admin_console.sql', (EXISTS (SELECT 1 FROM pg_constraint WHERE conname='platform_action_justification_length'))),
  ('0023', '0023_phase33_purchases.sql', (EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='itc_claim_deadline_period'))),
  ('0024', '0024_phase34_gstr2b.sql', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='gstr2b_matches_within_statement'))),
  ('0025', '0025_phase36_tds.sql', (EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='tds_return_due_date'))),
  ('0026', '0026_phase37_tally.sql', (EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='tally_batch_matches_its_vouchers'))),
  ('0027', '0027_phase38_receivables.sql', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='demand_notices_frozen_once_issued'))),
  ('0028', '0028_phase39_orders.sql', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='trg_touch_sales_order_fulfillments'))),
  ('0029', '0029_phase40_inventory.sql', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='trg_refresh_reserved_quantity'))),
  ('0030', '0030_phase42_land.sql', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='trg_guard_heir_shares'))),
  ('0031', '0031_phase44_ra_bills.sql', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='trg_guard_retention_release'))),
  ('0032', '0032_engine4_compliance.sql', (EXISTS (SELECT 1 FROM pg_views WHERE schemaname='public' AND viewname='v_compliance_licence_board'))),
  ('0033', '0033_engine1_scheduling.sql', (EXISTS (SELECT 1 FROM pg_views WHERE schemaname='public' AND viewname='v_schedule_utilisation'))),
  ('0034', '0034_engine2_pricing.sql', (EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='ordence_select_rate_card'))),
  ('0035', '0035_engine5_metering.sql', (EXISTS (SELECT 1 FROM pg_views WHERE schemaname='public' AND viewname='v_meter_estimates_outstanding'))),
  ('0036', '0036_engine3_field_ops.sql', (EXISTS (SELECT 1 FROM pg_views WHERE schemaname='public' AND viewname='v_field_technician_performance'))),
  ('0037', '0037_engine6_vault.sql', (EXISTS (SELECT 1 FROM pg_views WHERE schemaname='public' AND viewname='v_vault_access_summary'))),
  ('0038', '0038_construction_labour.sql', (EXISTS (SELECT 1 FROM pg_views WHERE schemaname='public' AND viewname='v_site_labour_summary'))),
  ('0039', '0039_tables_paste_only.sql', (EXISTS (SELECT 1 FROM pg_tables WHERE schemaname='public' AND tablename='rate_cards'))),
  ('0040', '0040_stock_reservation_floor.sql', (EXISTS (SELECT 1 FROM pg_views WHERE schemaname='public' AND viewname='v_stock_over_committed'))),
  ('0041', '0041_contracting_depth.sql', (EXISTS (SELECT 1 FROM pg_views WHERE schemaname='public' AND viewname='v_boq_billing_position'))),
  ('0042', '0042_mcp_access.sql', (EXISTS (SELECT 1 FROM pg_views WHERE schemaname='public' AND viewname='v_mcp_activity'))),
  ('0043', '0043_engine1_engine4_tables.sql', (EXISTS (SELECT 1 FROM pg_tables WHERE schemaname='public' AND tablename='compliance_obligations'))),
  ('0044', '0044_tenant_patterns.sql', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='tenant_patterns' AND policyname='tenant_patterns_tenant_isolation'))),
  ('0045', '0045_notifications.sql', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='notifications' AND policyname='notifications_tenant_isolation'))),
  ('0046', '0046_deployment_flows_governance.sql', (EXISTS (SELECT 1 FROM pg_constraint WHERE conname='deployment_backups_release_fkey'))),
  ('0047', '0047_grant_missing_views.sql', (EXISTS (SELECT 1 FROM information_schema.role_table_grants WHERE table_schema='public' AND table_name='v_boq_billing_position' AND grantee='ordence_app' AND privilege_type='SELECT'))),
  ('0048', '0048_credit_limits.sql', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='approval_limits' AND policyname='approval_limits_tenant_isolation'))),
  ('0049', '0049_sales_invoices.sql', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='customer_receipt_allocations' AND policyname='customer_receipt_allocations_tenant_isolation'))),
  ('0050', '0050_sales_credit_notes.sql', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='sales_credit_note_lines' AND policyname='sales_credit_note_lines_tenant_isolation'))),
  ('0051', '0051_sales_posting_accounts.sql', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='sales_posting_accounts' AND policyname='sales_posting_accounts_tenant_isolation'))),
  ('0052', '0052_booking_possession.sql', (EXISTS (SELECT 1 FROM pg_constraint WHERE conname='bookings_possession_not_cancelled'))),
  ('0053', '0053_time_and_billing.sql', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='time_entries' AND policyname='time_entries_tenant_isolation'))),
  ('0054', '0054_eway_bills.sql', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='eway_bill_items' AND policyname='eway_bill_items_tenant_isolation'))),
  ('0055', '0055_batch_serial_returns.sql', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='stock_write_offs' AND policyname='stock_write_offs_tenant_isolation'))),
  ('0056', '0056_transfers_landed_cost.sql', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='landed_cost_allocations' AND policyname='landed_cost_allocations_tenant_isolation'))),
  ('0057', '0057_pricing_discounts.sql', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='post_supply_discount_invoices' AND policyname='post_supply_discount_invoices_tenant_isolation'))),
  ('0058', '0058_legal_matters.sql', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='client_account_entries' AND policyname='client_account_entries_tenant_isolation'))),
  ('0059', '0059_court_fees_disbursements.sql', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='legal_client_tax_status' AND policyname='legal_client_tax_status_tenant_isolation'))),
  ('0060', '0060_tasks_activities_calendar.sql', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='calendar_event_attendees' AND policyname='calendar_event_attendees_tenant_isolation'))),
  ('0061', '0061_crm_consent_messaging.sql', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='messages' AND policyname='messages_tenant_isolation'))),
  ('0063', '0063_purchase_orders_payments.sql', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='vendor_payment_allocations' AND policyname='vendor_payment_allocations_tenant_isolation'))),
  ('0064', '0064_integration_frame.sql', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='webhook_deliveries' AND policyname='webhook_deliveries_tenant_isolation'))),
  ('0065', '0065_lead_intake.sql', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='lead_intake_failures' AND policyname='lead_intake_failures_tenant_isolation'))),
  ('0066', '0066_utility_messaging.sql', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='message_sends' AND policyname='message_sends_tenant_isolation'))),
  ('0067', '0067_campaigns.sql', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='campaign_recipients' AND policyname='campaign_recipients_tenant_isolation'))),
  ('0068', '0068_order_rhythm.sql', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='automation_events' AND policyname='automation_events_tenant_isolation'))),
  ('0069', '0069_connection_probes.sql', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='ordence_guard_probe_scope'))),
  ('0070', '0070_bank_reconciliation.sql', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='ordence_guard_posted_count'))),
  ('0071', '0071_tenant_agents.sql', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='ordence_guard_agent_autonomy'))),
  ('0073', '0073_period_lock_and_reorder.sql', (EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname='public' AND indexname='stock_items_vendor_idx'))),
  ('0074', '0074_platform_control.sql', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='ordence_guard_self_approval'))),
  ('0075', '0075_payroll.sql', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='ordence_guard_payroll_status'))),
  ('0077', '0077_monthly_return.sql', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='gst_returns' AND policyname='gst_returns_isolation'))),
  ('0078', '0078_real_estate_completion.sql', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='channel_partner_commissions' AND policyname='cp_commissions_isolation'))),
  ('0079', '0079_rls_opt_in_and_telemetry.sql', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='security_events' AND policyname='security_events_tenant_isolation' AND qual LIKE '%app_platform_scope%'))),
  ('0080', '0080_orders_place_of_supply.sql', (EXISTS (SELECT 1 FROM pg_constraint WHERE conname='sales_orders_immovable_property_pos'))),
  ('0081', '0081_audit_hash_chain.sql', (EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='audit_chain_link_hash'))),
  ('0082', '0082_leave_and_attendance.sql', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='staff_attendance_set_updated_at'))),
  ('0083', '0083_credit_control_and_dunning.sql', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='credit_dunning_log_identity'))),
  ('0084', '0084_cost_centres_and_budgets.sql', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='budget_lines_period_lock'))),
  ('0085', '0085_appraisals_and_org.sql', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='appraisal_reviews_set_updated_at'))),
  ('0086', '0086_policy_platform_platform_tables.sql', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND policyname='tenant_health_events_platform_only' AND qual LIKE '%IS NULL) OR app_platform_scope%'))),
  ('0087', '0087_hardening_narrow_grants.sql', (NULL::boolean)),
  ('0088', '0088_hardening_auth_events.sql', (EXISTS (SELECT 1 FROM pg_enum e JOIN pg_type t ON t.oid=e.enumtypid WHERE t.typname='security_event_type' AND e.enumlabel='auth.account_created'))),
  ('0089', '0089_hardening_login_lockouts.sql', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='login_lockouts' AND policyname='login_lockouts_write_platform'))),
  ('0090', '0090_period_close_message_normalization.sql', (EXISTS (SELECT 1 FROM pg_proc WHERE proname='enforce_period_close' AND position('FROM public.transactions' in prosrc) > 0))),
  ('0091', '0091_slug_authority.sql', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='ordence_guard_tenant_slug'))),
  ('0093', '0093_user_notification_preferences.sql', (NULL::boolean)),
  ('0094', '0094_wage_payment_date_and_settlement.sql', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='employee_settlements' AND policyname='employee_settlements_tenant_isolation'))),
  ('0095', '0095_employee_tax_regime_elections.sql', (NULL::boolean)),
  ('0096', '0096_advances_loans_and_reimbursements.sql', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='employee_reimbursement_claims' AND policyname='employee_reimbursement_claims_tenant_isolation'))),
  ('0097', '0097_email_outbox_and_suppressions.sql', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='email_suppressions' AND policyname='email_suppressions_tenant_isolation'))),
  ('0098', '0098_dunning_service_evidence.sql', (EXISTS (SELECT 1 FROM pg_constraint WHERE conname='dunning_events_service_recorder_fk'))),
  ('0099', '0099_stock_movement_valuation.sql', (EXISTS (SELECT 1 FROM pg_proc WHERE proname='ordence_validate_stock_movement' AND position('SELECT id, name, uom, tenant_id INTO item' in prosrc) > 0))),
  ('0100', '0100_fixed_asset_register_and_depreciation.sql', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='depreciation_lines' AND policyname='depreciation_lines_tenant_isolation'))),
  ('0101', '0101_multi_currency_and_fx.sql', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='fx_revaluation_lines' AND policyname='fx_revaluation_lines_tenant_isolation'))),
  ('0102', '0102_bank_reconciliation_statement_and_lock.sql', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='bank_reconciliation_items' AND policyname='bank_reconciliation_items_tenant'))),
  ('0104', '0104_analytics_views_carry_currency.sql', (EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='v_ledger_daily' AND column_name='currency'))),
  ('0105', '0105_per_tenant_ai_provider_credentials.sql', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='ai_provider_credentials' AND policyname='ai_provider_credentials_tenant_isolation'))),
  ('0106', '0106_tds_foreign_payments_rule_26.sql', (EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fx_reference_rates_rate_type_known'))),
  ('0108', '0108_journal_entries_minor_units.sql', (EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='enforce_double_entry_balance'))),
  ('0109', '0109_payroll_entitlement_grandfather.sql', (NULL::boolean)),
  ('0110', '0110_bank_allocation_and_bank_charge_itc.sql', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='ordence_guard_reconciled_statement_delete'))),
  ('0111', '0111_deemed_service_and_notice_authority.sql', (EXISTS (SELECT 1 FROM pg_constraint WHERE conname='dunning_events_deemed_states_its_basis'))),
  ('0112', '0112_bank_charge_itc_posting.sql', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='ordence_guard_posted_itc_deferral'))),
  ('0113', '0113_dpdp_data_principal_requests.sql', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='personal_data_breaches' AND policyname='personal_data_breaches_tenant_isolation'))),
  ('0114', '0114_seat_grants_and_pending_seats.sql', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='ordence_guard_resolved_seat_request'))),
  ('0115', '0115_ai_credential_policy_and_usage.sql', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='ordence_guard_ai_usage_append_only'))),
  ('0116', '0116_data_exports.sql', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='ordence_guard_data_exports_append_only'))),
  ('0117', '0117_import_runs_and_mapping.sql', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='ordence_guard_import_chunks_append_only'))),
  ('0118', '0118_drawing_register.sql', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='ordence_guard_drawing_measurements'))),
  ('0119', '0119_rate_limit_counters.sql', (EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='ordence_rate_limit_sweep'))),
  ('0120', '0120_schema_migrations.sql', (EXISTS (SELECT 1 FROM pg_tables WHERE schemaname='public' AND tablename='schema_migrations'))),
  ('0121', '0121_revoke_prune_from_app_role.sql', (CASE WHEN NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='ordence_app') THEN NULL WHEN NOT EXISTS (SELECT 1 FROM pg_proc WHERE proname='prune_security_events') THEN FALSE ELSE NOT EXISTS (SELECT 1 FROM pg_proc p, aclexplode(p.proacl) a JOIN pg_roles r ON r.oid=a.grantee WHERE p.proname='prune_security_events' AND r.rolname='ordence_app' AND a.privilege_type='EXECUTE') END)),
  ('0122', '0122_change_log_coverage_sweep.sql', (EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='attach_change_log_triggers'))),
  ('0123', '0123_dunning_chronology_uses_raised_at.sql', (EXISTS (SELECT 1 FROM pg_proc WHERE proname='dunning_ladder_has_no_gaps' AND position('v_last_effective timestamptz;' in prosrc) > 0))),
  ('0124', '0124_restore_stock_movement_checks.sql', (EXISTS (SELECT 1 FROM pg_proc WHERE proname='ordence_validate_stock_movement' AND position('reverses_movement_id' in prosrc) > 0 AND position('tenant_id = NEW.tenant_id' in prosrc) > 0))),
  ('0125', '0125_impersonation_guard_coverage.sql', (EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='attach_impersonation_guards'))),
  ('0127', '0127_dunning_log_delivery_writeback.sql', (EXISTS (SELECT 1 FROM information_schema.column_privileges WHERE table_schema='public' AND table_name='credit_dunning_log' AND column_name='delivery' AND grantee='ordence_app' AND privilege_type='UPDATE'))),
  ('0128', '0128_change_log_retention.sql', (EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='prune_change_log'))),
  ('0129', '0129_scheduler_run_ledger.sql', (EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='scheduler_runs' AND policyname='scheduler_runs_platform_only'))),
  ('0130', '0130_scheduler_control_plane.sql', (EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='scheduler_pause_reason'))),
  ('0131', '0131_scheduler_watchdog.sql', (EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='scheduler_reclaim_stale'))),
  ('0132', '0132_scheduler_retention_and_seal.sql', (EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='prune_scheduler_runs'))),
  ('0133', '0133_request_outcomes.sql', (EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='prune_request_outcomes'))),
  ('0134', '0134_audit_event_stream.sql', (EXISTS (SELECT 1 FROM pg_views WHERE schemaname='public' AND viewname='security_event_stream'))),
  ('0135', '0135_observability_alerts.sql', (EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='prune_observability_alerts'))),
  ('0136', '0136_phase4_clm_and_ledger_isolation.sql', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='journal_entries_update_balance'))),
  ('0137', '0137_force_rls_and_isolation_posture.sql', (EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='isolation_posture'))),
  ('0138', '0138_updated_at_consolidation.sql', (EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='updated_at_census'))),
  ('0139', '0139_schema_contract_snapshot.sql', (EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='diff_schema_contract'))),
  ('0140', '0140_tenant_table_drift_detector.sql', (EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='assert_no_tenant_table_drift'))),
  ('0141', '0141_retention_with_teeth.sql', (EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='prune_security_events' AND pg_get_function_identity_arguments(p.oid) LIKE '%boolean%'))),
  ('0146', '0146_gst_rate_pin_integrity.sql', (EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='gst_rate_usage'))),
  ('0147', '0147_gst_line_tax_recomputes.sql', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='purchase_invoice_lines_gst_recomputes'))),
  ('0148', '0148_gst_rate_pin_backfill.sql', (EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='gst_backfill_rate_pins'))),
  ('0149', '0149_einvoice_irn_readiness.sql', (EXISTS (SELECT 1 FROM pg_trigger WHERE NOT tgisinternal AND tgname='sales_invoices_irn_integrity'))),
  ('0150', '0150_tax_decision_trail.sql', (EXISTS (SELECT 1 FROM pg_views WHERE schemaname='public' AND viewname='tax_decision_gaps'))),
  ('0151', '0151_perf_sales_invoices_due_date_index.sql', (EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname='public' AND indexname='sales_invoices_tenant_due_idx'))),
  ('0152', '0152_perf_audit_logs_keyset_index.sql', (EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname='public' AND indexname='audit_logs_tenant_keyset_idx'))),
  ('0153', '0153_perf_change_log_tenant_index.sql', (EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname='public' AND indexname='change_log_tenant_changed_at_idx'))),
  ('0154', '0154_perf_contacts_live_index.sql', (EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname='public' AND indexname='contacts_tenant_live_idx'))),
  ('0155', '0155_perf_index_health_function.sql', (EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='ordence_index_health'))),
  ('0156', '0156_perf_drop_duplicate_indexes.sql', (NULL::boolean)),
  ('0157', '0157_perf_drop_redundant_tenant_indexes.sql', (NULL::boolean)),
  ('0158', '0158_perf_slow_query_visibility.sql', (EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='ordence_active_queries'))),
  ('0159', '0159_email_outbox_ceiling_and_terminal_evidence.sql', (EXISTS (SELECT 1 FROM pg_constraint WHERE conname='email_outbox_max_attempts_check'))),
  ('0160', '0160_email_outbox_claim_is_complete.sql', (EXISTS (SELECT 1 FROM pg_constraint WHERE conname='email_outbox_claim_is_complete_check'))),
  ('0166', '0166_security_event_types.sql', (EXISTS (SELECT 1 FROM pg_enum e JOIN pg_type t ON t.oid=e.enumtypid WHERE t.typname='security_event_type' AND e.enumlabel='billing.standing_unresolved'))),
  ('0168', '0168_audit_stream_comment_correction.sql', ((EXISTS (SELECT 1 FROM pg_views WHERE schemaname='public' AND viewname='security_event_stream') AND coalesce(obj_description((SELECT c.oid FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relname='security_event_stream'),'pg_class'),'') NOT LIKE '%not recorded anywhere%')))
)
SELECT jsonb_pretty(jsonb_build_object(
  'applied',     count(*) FILTER (WHERE present),
  'pending',     count(*) FILTER (WHERE present IS FALSE),
  'unprobeable', count(*) FILTER (WHERE present IS NULL),
  'run_this_next', min(num) FILTER (WHERE present IS FALSE),
  'highest_applied', max(num) FILTER (WHERE present),
  'what_to_do', 'Run every MISSING file from section 2, oldest first, one at a time.'
)) AS section_1_summary
FROM probes;

-- ---------------------------------------------------------------------
--  SECTION 3 , the 5 migrations that only INSERT rows.
--
--  🔴 ONE STATEMENT PER PROBE, AND THAT IS A CORRECTION, NOT A STYLE
--     CHOICE.
--
--  These probes name tables directly, and PostgreSQL resolves table names
--  at PARSE time. An earlier version of this file put all 5 probes in
--  one VALUES list , and on a real database it failed whole:
--
--      ERROR: relation "public.schema_contract_snapshots" does not exist
--
--  One absent table took the answers for the other four with it, and the
--  one it hid was 0126, the file already known to have half-applied. The
--  guard to_regclass(...) IS NOT NULL AND EXISTS (SELECT 1 FROM t) does
--  NOT help: to_regclass is evaluated at run time, but FROM t is
--  resolved at parse time, so the guard never gets the chance to run.
--
--  ⚠️ RUN THESE ONE AT A TIME. An error is an ANSWER, not a failure:
--     "relation does not exist" means the table is absent, so the file
--     did not run. Note it as MISSING and run the next one.
-- ---------------------------------------------------------------------

-- 0092 , 0092_reserve_clerk_hosts.sql
-- If this errors with "relation does not exist", the answer is MISSING.
SELECT '0092' AS num,
       '0092_reserve_clerk_hosts.sql' AS file_name,
       CASE WHEN ((to_regclass('public.reserved_slugs') IS NOT NULL AND EXISTS (SELECT 1 FROM public.reserved_slugs WHERE added_by='migration:0092'))) THEN 'PRESENT' ELSE 'MISSING' END AS status,
       'reserved_slugs row added_by=migration:0092' AS looked_for;

-- 0103 , 0103_reserve_resend_hosts.sql
-- If this errors with "relation does not exist", the answer is MISSING.
SELECT '0103' AS num,
       '0103_reserve_resend_hosts.sql' AS file_name,
       CASE WHEN ((to_regclass('public.reserved_slugs') IS NOT NULL AND EXISTS (SELECT 1 FROM public.reserved_slugs WHERE added_by='migration:0103'))) THEN 'PRESENT' ELSE 'MISSING' END AS status,
       'reserved_slugs row added_by=migration:0103' AS looked_for;

-- 0126 , 0126_updated_at_coverage.sql
-- If this errors with "relation does not exist", the answer is MISSING.
SELECT '0126' AS num,
       '0126_updated_at_coverage.sql' AS file_name,
       CASE WHEN ((to_regclass('public.updated_at_exclusions') IS NOT NULL AND EXISTS (SELECT 1 FROM public.updated_at_exclusions))) THEN 'PRESENT' ELSE 'MISSING' END AS status,
       'the exclusion registry has been POPULATED, which only happens after the block that the original 0126 aborted on , reported in the data section because naming a table makes the probe fail at PARSE time on a database that lacks it, which would take sections 1 and 2 down with it.' AS looked_for;

-- 0142 , 0142_capture_schema_contract.sql
-- If this errors with "relation does not exist", the answer is MISSING.
SELECT '0142' AS num,
       '0142_capture_schema_contract.sql' AS file_name,
       CASE WHEN ((to_regclass('public.schema_contract_snapshots') IS NOT NULL AND EXISTS (SELECT 1 FROM public.schema_contract_snapshots))) THEN 'PRESENT' ELSE 'MISSING' END AS status,
       'a row in schema_contract_snapshots (0142 only CALLS capture_schema_contract, so the row is the artefact) , reported in the data section because naming a table makes the probe fail at PARSE time on a database that lacks it, which would take sections 1 and 2 down with it.' AS looked_for;

-- 0167 , 0167_impersonation_guard_exemption_record.sql
-- If this errors with "relation does not exist", the answer is MISSING.
SELECT '0167' AS num,
       '0167_impersonation_guard_exemption_record.sql' AS file_name,
       CASE WHEN ((to_regclass('public.change_log') IS NOT NULL AND coalesce(obj_description('public.change_log'::regclass,'pg_class'),'') LIKE '%needs_action%')) THEN 'PRESENT' ELSE 'MISSING' END AS status,
       'change_log carries Track D''s exemption verdict as a table comment , data section: obj_description() names a table and therefore resolves at parse time.' AS looked_for;
