/**
 * Ordence — ⭐ GSTR-2B RECONCILIATION
 * Version: v0.34.0-alpha
 *
 * ══════════════════════════════════════════════════════════════════════
 * WHAT GSTR-2B IS, AND WHY IT OUTRANKS OUR OWN BOOKS
 * ══════════════════════════════════════════════════════════════════════
 * GSTR-2B is a static monthly statement the GST portal generates for a
 * GSTIN. It lists every document that OUR SUPPLIERS filed against us in
 * their own GSTR-1 — invoice by invoice, with the tax they declared.
 *
 * Section 16(2)(aa), in force from 1 January 2022, makes it the ceiling:
 *
 *     "…the details of the invoice or debit note have been furnished by
 *      the supplier in the statement of outward supplies and such details
 *      have been communicated to the recipient of such invoice…"
 *
 * So the credit is not ours because we hold a tax invoice and paid the
 * tax. It is ours because the SUPPLIER filed. Rule 36(4) removed the old
 * 5% tolerance entirely in 2022; there is now no cushion at all.
 *
 * ⭐ THE CONSEQUENCE, STATED PLAINLY: a bill we have, have paid, and hold
 * a perfect tax invoice for, carries NO input tax credit if the supplier
 * did not file their GSTR-1. Nothing in our own records shows this. The
 * bill looks identical to one that is fine. The only way to know is to
 * compare our purchase register against a document generated by somebody
 * else, every month, invoice by invoice.
 *
 * That comparison is this phase.
 *
 * ══════════════════════════════════════════════════════════════════════
 * ⚠️ WHY THE MATCH ITSELF IS A STORED, EXPLAINED FACT AND NOT A QUERY
 * ══════════════════════════════════════════════════════════════════════
 * The obvious design is a view: join purchase invoices to 2B rows on
 * GSTIN and invoice number, count what falls out. It fails on the first
 * real month, for a reason that has nothing to do with SQL.
 *
 *   • The supplier types `INV-001`. We typed `INV/001` off the same
 *     paper. A join on equality reports both an unfiled supplier AND an
 *     unrecorded purchase, from ONE invoice, and the two errors are in
 *     opposite directions so the totals still look plausible.
 *   • The supplier declared ₹1,00,000.00 taxable; our line-level
 *     rounding produced ₹99,999.98. Same invoice, different number.
 *   • A finance manager has to defend every accepted match to an
 *     officer, months later, when the underlying rows have moved on.
 *
 * So a match is a ROW: which 2B line, which purchase invoice, WHICH
 * FIELDS AGREED, what differed and by how many paise, what confidence
 * the engine assigned, and who accepted it. Re-running the engine
 * produces the same answer from the same inputs — and where it does not,
 * `engine_version` says why.
 *
 * ══════════════════════════════════════════════════════════════════════
 * ⚠️ THE RAW DOCUMENT IS THE EVIDENCE. THE PARSED ROWS ARE AN OPINION.
 * ══════════════════════════════════════════════════════════════════════
 * `gstr2b_documents.raw_document` holds the file exactly as it was
 * downloaded, and it is immutable by trigger (SQL 0024 §5). The parsed
 * `gstr2b_rows` are derived and may be dropped and rebuilt.
 *
 * The asymmetry is deliberate and it is the most important line in this
 * file. A parse bug is discovered by definition AFTER the parse — often
 * a year later, at a notice. If the import overwrote the raw file with
 * its own interpretation, there is nothing left to re-read, and the only
 * remaining copy of what the Government actually said about us is on a
 * portal that keeps two years of history.
 *
 * ══════════════════════════════════════════════════════════════════════
 * ⚠️ AND A FILED PERIOD FREEZES
 * ══════════════════════════════════════════════════════════════════════
 * Once a GSTR-3B has been filed for a period, the reconciliation that
 * supported it is the working paper for a return the Government holds a
 * copy of. Re-importing 2B for that period — which people do, because
 * the portal REGENERATES 2B when a supplier files late — must not
 * silently rewrite it. The trigger in SQL 0024 §6 refuses.
 *
 * Money is `bigint` paise. Rates are integer basis points.
 */

import {
  pgTable,
  pgEnum,
  uuid,
  text,
  varchar,
  timestamp,
  date,
  jsonb,
  boolean,
  integer,
  bigint,
  index,
  uniqueIndex,
  check,
} from "drizzle-orm/pg-core";
import { relations, sql } from "drizzle-orm";
import { tenants, users } from "./core";
import { gstRegistrations } from "./gst";
import { purchaseInvoices, vendors } from "./purchases";

/* ------------------------------------------------------------------ */
/* ENUMS — THE STATEMENT                                               */
/* ------------------------------------------------------------------ */

/**
 * The sections of a GSTR-2B, named exactly as the portal's JSON names
 * them.
 *
 * ⚠️ THEY ARE NOT INTERCHANGEABLE AND THE ARITHMETIC DIFFERS BY SECTION.
 *
 *   b2b     — ordinary supplier invoices. The bulk.
 *   b2ba    — ⭐ AMENDMENTS to invoices declared in an EARLIER period.
 *             An amendment SUPERSEDES the original: the credit is the
 *             amended figure, not the sum of the two. Treating a `b2ba`
 *             row as another invoice double-counts the whole document.
 *   cdnr    — credit and debit notes from a registered supplier. A
 *             CREDIT note REDUCES our credit; a DEBIT note increases it.
 *             ⚠️ Both arrive as positive numbers with a type flag, so a
 *             parser that ignores `nttyp` gets the sign backwards on
 *             every return.
 *   cdnra   — amendments to those notes.
 *   isd     — Input Service Distributor documents: credit distributed
 *             from a head office registration to this one.
 *   isda    — amendments to those.
 *   impg    — ⭐ IMPORTS OF GOODS. A bill of entry, not an invoice. There
 *             is no supplier GSTIN at all — the counterparty is Customs
 *             — so every match rule keyed on GSTIN is inapplicable and
 *             the key is the bill-of-entry number and port code.
 *   impgsez — imports from an SEZ unit. Same shape, and the SEZ DOES
 *             have a GSTIN.
 */
export const gstr2bSectionEnum = pgEnum("gstr2b_section", [
  "b2b",
  "b2ba",
  "cdnr",
  "cdnra",
  "isd",
  "isda",
  "impg",
  "impgsez",
]);

/**
 * How the statement reached us.
 *
 * ⚠️ THE CSV/EXCEL PATH IS NOT A CONVENIENCE, IT IS THE COMMON CASE. The
 * portal's JSON download is the authoritative artefact, and almost no
 * accountant has one: they open the Excel, or their consultant emails a
 * sheet. Refusing everything but JSON means the feature is used by
 * nobody and the reconciliation is done in a spreadsheet instead — which
 * is the status quo this phase exists to replace.
 *
 * ⚠️ AND THE FORMAT IS RECORDED BECAUSE IT CHANGES WHAT WE CAN PROVE. A
 * portal JSON carries the checksum and the generation date; a
 * hand-edited sheet carries neither, and a match built on one is
 * evidence of a different quality. Storing the format is how a later
 * reader can tell the two apart.
 */
export const gstr2bSourceFormatEnum = pgEnum("gstr2b_source_format", [
  "portal_json",
  "portal_excel",
  "csv",
]);

/**
 * ⚠️ `failed` IS A STATE OF THE DOCUMENT, NOT AN ABSENCE OF ONE. A file
 * that would not parse is still stored, in full, with the reason. The
 * alternative — refusing the insert — throws away the only copy of the
 * thing that has to be looked at to fix the parser.
 */
export const gstr2bParseStatusEnum = pgEnum("gstr2b_parse_status", [
  "pending",
  "parsed",
  "failed",
]);

/**
 * Whether the portal says the credit on a 2B row is available to us.
 *
 * ⚠️ THIS IS THE PORTAL'S OPINION AND IT IS NOT THE SAME QUESTION AS
 * SECTION 17(5). The portal marks `itcavl = 'N'` for a handful of
 * mechanical reasons — the supplier filed after the Section 16(4)
 * deadline, the place of supply and the supplier's state are the same as
 * ours so the credit belongs to another state, the document is from a
 * period beyond the limit. It knows nothing about whether the cement
 * went into a building we are selling or one we are keeping.
 *
 * So a row can be `available` here and still be BLOCKED by Phase 33's
 * determination, and the reconciliation must show both. Collapsing them
 * into one flag is how a blocked credit gets claimed because "2B says
 * it's available".
 */
export const gstr2bItcAvailabilityEnum = pgEnum("gstr2b_itc_availability", [
  "available",
  "not_available",
]);

/* ------------------------------------------------------------------ */
/* ENUMS — ⭐ THE MATCH                                                */
/* ------------------------------------------------------------------ */

/**
 * ⭐⭐ THE SEVEN OUTCOMES, AND WHY THERE ARE SEVEN RATHER THAN TWO.
 *
 * "Matched / unmatched" is the design everybody reaches for and it is
 * useless in practice, because the four unmatched kinds need four
 * different people to do four different things:
 *
 *   exact              — GSTIN, invoice number, date, taxable value and
 *                        every tax head agree. ⭐ THE ONLY CATEGORY THAT
 *                        MAY EVER BE ACCEPTED WITHOUT A HUMAN.
 *
 *   probable           — GSTIN and invoice number agree; a value differs.
 *                        Usually line-level rounding: they footed the
 *                        invoice, we footed the lines. The delta is
 *                        recorded in paise and a person decides. ⚠️ A
 *                        large delta is ALSO this category, at low
 *                        confidence — it is still the same document, and
 *                        pretending otherwise would report the invoice
 *                        as both missing and unrecorded.
 *
 *   number_mismatch    — same supplier, same date, same value, and the
 *                        invoice number differs only in punctuation:
 *                        `INV-001` / `INV/001` / `INV 001` / `INV1`.
 *                        ⚠️ NORMALISED FOR COMPARISON ONLY. The
 *                        supplier's number is never overwritten with
 *                        ours — theirs is what the portal holds, and it
 *                        is what any future correspondence quotes.
 *
 *   in_2b_not_in_books — the supplier filed something we never recorded.
 *                        A bill lost in the post, or an invoice raised
 *                        against our GSTIN by somebody we do not deal
 *                        with. The second is fraud and looks exactly
 *                        like the first.
 *
 *   in_books_not_in_2b — ⭐ THE EXPENSIVE ONE. We have the bill, we paid
 *                        it, and the supplier has not filed. Section
 *                        16(2)(aa) means the credit is not available.
 *                        Every day it stays here is a day closer to the
 *                        Section 16(4) cliff, after which it is gone
 *                        permanently.
 *
 *   amended            — a `b2ba`/`cdnra` row superseding an earlier
 *                        declaration. The amended figures replace the
 *                        original; they do not add to it.
 *
 *   cancelled          — the supplier withdrew the document. We hold an
 *                        invoice for a supply the supplier now says did
 *                        not happen, and any credit taken on it must be
 *                        reversed.
 */
export const gstr2bMatchCategoryEnum = pgEnum("gstr2b_match_category", [
  "exact",
  "probable",
  "number_mismatch",
  "in_2b_not_in_books",
  "in_books_not_in_2b",
  "amended",
  "cancelled",
]);

/**
 * How much the engine believes its own answer.
 *
 * ⚠️ SEPARATE FROM THE CATEGORY BECAUSE THE CATEGORY IS *WHAT* AND THIS
 * IS *HOW SURE*. A `probable` match that differs by 2 paise and a
 * `probable` match that differs by ₹40,000 are the same category and
 * nowhere near the same claim, and a worklist that cannot sort by the
 * second is a worklist nobody finishes.
 */
export const gstr2bMatchConfidenceEnum = pgEnum("gstr2b_match_confidence", [
  "exact",
  "high",
  "medium",
  "low",
  "none",
]);

/**
 * What a human decided about a proposed match.
 *
 * ⚠️ `deferred` IS NOT `pending`, AND THE DIFFERENCE IS A PERSON. Pending
 * means nobody has looked. Deferred means somebody looked, could not
 * resolve it this month, and expects it to resolve next month when the
 * supplier files. An ageing report that cannot tell those apart reports
 * a growing backlog either as neglect or as a supplier problem, and they
 * need opposite responses.
 */
export const gstr2bMatchActionEnum = pgEnum("gstr2b_match_action", [
  "pending",
  "accepted",
  "rejected",
  "deferred",
]);

/**
 * Where a reconciliation is in its life.
 *
 * ⚠️ `filed` IS A ONE-WAY DOOR. It records that a GSTR-3B was submitted
 * on the strength of these figures. From that moment the reconciliation
 * is a working paper for a document the Government holds, and the
 * trigger in SQL 0024 §6 refuses every further change to it — including,
 * and especially, a re-import of the same period, which the portal
 * itself invites by REGENERATING 2B whenever a supplier files late.
 */
export const gstr2bReconciliationStatusEnum = pgEnum("gstr2b_reconciliation_status", [
  "draft",
  "in_progress",
  "reconciled",
  "filed",
]);

/* ------------------------------------------------------------------ */
/* ⭐ THE IMPORTED STATEMENT — THE EVIDENCE                            */
/* ------------------------------------------------------------------ */

/**
 * One downloaded GSTR-2B, stored whole.
 *
 * ⚠️ THE KEY IS (GSTIN, PERIOD, FILE HASH) AND ALL THREE PARTS EARN
 * THEIR PLACE.
 *
 *   • GSTIN, because 2B is generated per registration. A developer
 *     registered in Maharashtra and Karnataka has two entirely separate
 *     statements for July, and merging them would set credit against the
 *     wrong electronic credit ledger.
 *   • Period, obviously.
 *   • ⭐ FILE HASH, because 2B for one period is regenerated. When a
 *     supplier files their GSTR-1 late, the portal issues a NEW 2B for
 *     the period they filed against. The July statement downloaded in
 *     August and the July statement downloaded in November are different
 *     documents describing the same month, and both are evidence. Keying
 *     on (GSTIN, period) alone would overwrite the first with the second
 *     and destroy the record of what we knew when we filed.
 */
export const gstr2bDocuments = pgTable(
  "gstr2b_documents",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    tenantId: uuid("tenant_id")
      .notNull()
      .references(() => tenants.id, { onDelete: "cascade" }),

    /** ⭐ Whose statement. Composite FK → gst_registrations, SQL §4. */
    registrationId: uuid("registration_id"),

    /**
     * The GSTIN the statement was generated for.
     *
     * ⚠️ DENORMALISED AND NOT NULL EVEN THOUGH `registration_id` POINTS
     * AT IT. The freeze rule and the uniqueness key are both expressed in
     * terms of a GSTIN and a period, and a nullable pointer cannot carry
     * a uniqueness constraint. It is also what the file itself says,
     * which is the thing that must be checked against our registration
     * rather than assumed from it.
     */
    gstin: varchar("gstin", { length: 15 }).notNull(),

    /** `YYYY-MM`. The period the statement covers. */
    returnPeriod: varchar("return_period", { length: 7 }).notNull(),

    sourceFormat: gstr2bSourceFormatEnum("source_format").notNull(),
    fileName: varchar("file_name", { length: 255 }),

    /**
     * SHA-256 of the bytes as received, lowercase hex.
     *
     * ⚠️ OF THE BYTES, NOT OF THE PARSED CONTENT. The point is to be able
     * to say "this is the same file the portal gave us", and a hash taken
     * after our own normalisation cannot say that.
     */
    fileHash: varchar("file_hash", { length: 64 }).notNull(),
    fileByteSize: bigint("file_byte_size", { mode: "bigint" }),

    /** From the statement itself: when the portal generated it. */
    generatedOn: date("generated_on", { mode: "string" }),
    portalVersion: varchar("portal_version", { length: 16 }),

    /**
     * ⭐⭐ THE FILE. Immutable by trigger (SQL 0024 §5).
     *
     * For a portal JSON this is the parsed JSON document verbatim. For a
     * CSV or Excel export it is `{ format, text, sheet? }` with the
     * delimited text held whole — because a CSV that has been through a
     * column mapper is no longer the file the accountant sent.
     *
     * ⚠️ IT IS `jsonb` AND SO IT IS CAPPED AT 1 GB. A large developer's
     * monthly 2B runs to a few megabytes; nothing observed comes close.
     * If one ever did, the answer is object storage with the hash as the
     * key — NOT dropping the raw, which is the one thing that must not
     * be traded away for space.
     */
    rawDocument: jsonb("raw_document").$type<unknown>().notNull(),

    parseStatus: gstr2bParseStatusEnum("parse_status").default("pending").notNull(),
    /** The sentence a person reads when the parse failed. */
    parseError: text("parse_error"),
    /**
     * Every issue the parser raised, with a path into the document.
     *
     * ⚠️ WARNINGS ARE KEPT AS WELL AS ERRORS. "Row 412 had no place of
     * supply" does not stop an import and is exactly the note somebody
     * needs when that one invoice will not match three weeks later.
     */
    parseIssues: jsonb("parse_issues")
      .$type<{ path: string; message: string; severity: "error" | "warning" }[]>()
      .default(sql`'[]'::jsonb`)
      .notNull(),

    rowCount: integer("row_count").default(0).notNull(),
    parsedAt: timestamp("parsed_at", { withTimezone: true }),

    importedBy: uuid("imported_by"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => ({
    /** ⭐ The same bytes imported twice are one document, not two. */
    identity: uniqueIndex("gstr2b_documents_identity_unique").on(
      t.tenantId,
      t.gstin,
      t.returnPeriod,
      t.fileHash,
    ),
    periodIdx: index("gstr2b_documents_period_idx").on(
      t.tenantId,
      t.gstin,
      t.returnPeriod,
    ),
    statusIdx: index("gstr2b_documents_status_idx").on(t.tenantId, t.parseStatus),

    periodShape: check(
      "gstr2b_documents_period_shape",
      sql`${t.returnPeriod} ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'`,
    ),
    /**
     * ⚠️ A FAILED PARSE MUST SAY WHY, AND A SUCCESSFUL ONE MUST NOT
     * CARRY A STALE REASON. A row that says `parsed` while still holding
     * last attempt's error is how a fixed import gets re-investigated.
     */
    failureExplained: check(
      "gstr2b_documents_failure_explained",
      sql`(${t.parseStatus} = 'failed') = (${t.parseError} IS NOT NULL)`,
    ),
    /** ⭐ The evidence may not be blank. */
    rawPresent: check(
      "gstr2b_documents_raw_present",
      sql`jsonb_typeof(${t.rawDocument}) IS NOT NULL AND ${t.rawDocument} <> 'null'::jsonb`,
    ),
    hashShape: check(
      "gstr2b_documents_hash_shape",
      sql`${t.fileHash} ~ '^[0-9a-f]{64}$'`,
    ),
    countSane: check("gstr2b_documents_count_sane", sql`${t.rowCount} >= 0`),
  }),
);

/* ------------------------------------------------------------------ */
/* THE PARSED ROWS — DERIVED, REBUILDABLE                              */
/* ------------------------------------------------------------------ */

/**
 * One document from the statement: an invoice, a note, an ISD document
 * or a bill of entry.
 *
 * ⚠️ ONE ROW PER DOCUMENT, NOT PER RATE LINE. The portal's JSON nests
 * `items[]` under each invoice, one per tax rate. The reconciliation
 * happens at DOCUMENT level — the portal matches on invoice number, and
 * so does an officer — so the items are summed into the heads here and
 * the rate breakup is kept in `rate_breakup` for the working. Storing
 * one row per rate line would triple the table and make every count in
 * the summary wrong.
 */
export const gstr2bRows = pgTable(
  "gstr2b_rows",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    tenantId: uuid("tenant_id")
      .notNull()
      .references(() => tenants.id, { onDelete: "cascade" }),

    /** Composite FK → gstr2b_documents (id, tenant_id). CASCADE. */
    documentId: uuid("document_id").notNull(),

    section: gstr2bSectionEnum("section").notNull(),

    /**
     * The supplier's GSTIN as the statement gives it.
     *
     * ⚠️ NULLABLE, AND ONLY FOR `impg`. An import of goods has no
     * supplier GSTIN — the counterparty is Customs and the document is a
     * bill of entry. Making it NOT NULL would force a placeholder, and a
     * placeholder GSTIN in a tax table is a value that eventually gets
     * matched against.
     */
    supplierGstin: varchar("supplier_gstin", { length: 15 }),
    supplierLegalName: varchar("supplier_legal_name", { length: 255 }),
    supplierTradeName: varchar("supplier_trade_name", { length: 255 }),

    /** The supplier's own number, as printed. ⭐ NEVER REWRITTEN. */
    invoiceNumber: varchar("invoice_number", { length: 64 }).notNull(),

    /**
     * ⭐ The number with punctuation and leading zeros removed, for
     * candidate lookup only.
     *
     * ⚠️ WRITTEN BY THE APPLICATION, NOT A GENERATED COLUMN, AND THAT IS
     * DELIBERATE. The normalisation strips leading zeros PER NUMERIC RUN
     * (`INV-0001` → `INV1`), which PostgreSQL's regexp_replace cannot
     * express without a lookbehind. A hand-rolled SQL approximation that
     * differed from `normaliseInvoiceNumber` in one edge case would make
     * an indexed query and the matching engine disagree about which
     * invoices are candidates — and the disagreement would only ever show
     * up as a match the workbench could not reproduce.
     *
     * One implementation, in `lib/gstr2b/invoice-number.ts`, used by both.
     */
    normalisedNumber: varchar("normalised_number", { length: 64 }).notNull(),

    invoiceDate: date("invoice_date", { mode: "string" }).notNull(),

    /** "R" regular, "SEZWP"/"SEZWOP", "DE" deemed export, "C"/"D" note. */
    documentType: varchar("document_type", { length: 12 }),

    /** What the supplier declared the document is worth, inclusive. */
    documentValueMinor: bigint("document_value_minor", { mode: "bigint" })
      .default(sql`0`)
      .notNull(),
    taxableValueMinor: bigint("taxable_value_minor", { mode: "bigint" })
      .default(sql`0`)
      .notNull(),
    cgstMinor: bigint("cgst_minor", { mode: "bigint" }).default(sql`0`).notNull(),
    sgstMinor: bigint("sgst_minor", { mode: "bigint" }).default(sql`0`).notNull(),
    igstMinor: bigint("igst_minor", { mode: "bigint" }).default(sql`0`).notNull(),
    cessMinor: bigint("cess_minor", { mode: "bigint" }).default(sql`0`).notNull(),

    placeOfSupplyCode: varchar("place_of_supply_code", { length: 2 }),
    isReverseCharge: boolean("is_reverse_charge").default(false).notNull(),

    itcAvailable: gstr2bItcAvailabilityEnum("itc_available")
      .default("available")
      .notNull(),
    /** The portal's own words: "POS and supplier state are same", etc. */
    itcUnavailableReason: varchar("itc_unavailable_reason", { length: 120 }),

    /** ⭐ When the SUPPLIER filed. The whole point of the statement. */
    supplierFilingPeriod: varchar("supplier_filing_period", { length: 7 }),
    supplierFilingDate: date("supplier_filing_date", { mode: "string" }),

    /**
     * ⭐ An amendment supersedes; it does not add.
     *
     * The original document's number and date are kept so the amendment
     * can be tied to the invoice already in our books, which will still
     * carry the ORIGINAL number.
     */
    isAmendment: boolean("is_amendment").default(false).notNull(),
    originalInvoiceNumber: varchar("original_invoice_number", { length: 64 }),
    originalInvoiceDate: date("original_invoice_date", { mode: "string" }),

    isCancelled: boolean("is_cancelled").default(false).notNull(),

    /** Per-rate split, for the working papers. Not matched on. */
    rateBreakup: jsonb("rate_breakup")
      .$type<{ rateBps: number; taxableValueMinor: string }[]>()
      .default(sql`'[]'::jsonb`)
      .notNull(),

    /** Where in the source file this came from: `data.docdata.b2b[3].inv[1]`. */
    sourceRef: varchar("source_ref", { length: 160 }),

    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => ({
    documentIdx: index("gstr2b_rows_document_idx").on(t.tenantId, t.documentId),
    sectionIdx: index("gstr2b_rows_section_idx").on(t.tenantId, t.documentId, t.section),
    /** ⭐ The candidate lookup the workbench searches on. */
    matchIdx: index("gstr2b_rows_match_idx").on(
      t.tenantId,
      t.supplierGstin,
      t.normalisedNumber,
    ),
    supplierIdx: index("gstr2b_rows_supplier_idx").on(
      t.tenantId,
      t.supplierGstin,
      t.invoiceDate,
    ),

    nonNegative: check(
      "gstr2b_rows_non_negative",
      sql`${t.documentValueMinor} >= 0 AND ${t.taxableValueMinor} >= 0
          AND ${t.cgstMinor} >= 0 AND ${t.sgstMinor} >= 0
          AND ${t.igstMinor} >= 0 AND ${t.cessMinor} >= 0`,
    ),
    /**
     * ⚠️ IGST AND THE CGST/SGST PAIR CANNOT BOTH APPEAR ON ONE ROW. The
     * same rule as on a purchase invoice, and here it is a PARSER check:
     * a row carrying both means the columns were mapped wrongly out of a
     * spreadsheet, which is the single most common CSV import failure and
     * the one that silently doubles the credit for a whole month.
     */
    headsExclusive: check(
      "gstr2b_rows_heads_exclusive",
      sql`NOT (${t.igstMinor} > 0 AND (${t.cgstMinor} > 0 OR ${t.sgstMinor} > 0))`,
    ),
    /** An amendment must name what it amends, or it cannot be applied. */
    amendmentNamesOriginal: check(
      "gstr2b_rows_amendment_names_original",
      sql`NOT ${t.isAmendment} OR ${t.originalInvoiceNumber} IS NOT NULL`,
    ),
    /**
     * ⚠️ ONLY AN IMPORT OF GOODS MAY LACK A SUPPLIER GSTIN. Anything else
     * without one is a row whose columns were mapped wrongly, and it
     * would sit in the worklist forever as an unmatched supplier who does
     * not exist.
     */
    gstinPresence: check(
      "gstr2b_rows_gstin_presence",
      sql`${t.supplierGstin} IS NOT NULL OR ${t.section} = 'impg'`,
    ),
    filingPeriodShape: check(
      "gstr2b_rows_filing_period_shape",
      sql`${t.supplierFilingPeriod} IS NULL
          OR ${t.supplierFilingPeriod} ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'`,
    ),
  }),
);

/* ------------------------------------------------------------------ */
/* ⭐ THE RECONCILIATION — ONE PER GSTIN PER PERIOD                    */
/* ------------------------------------------------------------------ */

/**
 * The period's reconciliation, its totals, and its freeze.
 *
 * ⚠️ THE TOTALS ARE STORED, WHICH CONTRADICTS THE RULE THIS CODEBASE
 * USES EVERYWHERE ELSE (see `vendor_ledger_entries`, which deliberately
 * has no `balance_minor`). The contradiction is intentional and the
 * reason is narrow:
 *
 *     A vendor balance must always equal the sum of today's rows,
 *     because a backdated entry changes the truth and the report must
 *     follow it.
 *
 *     A FILED reconciliation must NEVER follow later rows. It is the
 *     working paper for a GSTR-3B already submitted, and the figures in
 *     it are what was submitted. When the supplier files late in
 *     November and the portal regenerates July's 2B, the correct
 *     behaviour is for July's filed totals to stay exactly as they were
 *     and the difference to appear in November — which is also what the
 *     Government's own ledger does.
 *
 * A derived total would silently restate a filed return. So it is stored,
 * and frozen.
 */
export const gstr2bReconciliations = pgTable(
  "gstr2b_reconciliations",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    tenantId: uuid("tenant_id")
      .notNull()
      .references(() => tenants.id, { onDelete: "cascade" }),

    registrationId: uuid("registration_id"),
    gstin: varchar("gstin", { length: 15 }).notNull(),
    taxPeriod: varchar("tax_period", { length: 7 }).notNull(),

    /** Which imported statement the current run was built from. */
    documentId: uuid("document_id"),

    status: gstr2bReconciliationStatusEnum("status").default("draft").notNull(),

    /* --- ⭐ THE THREE COLUMNS OF THE SUMMARY -------------------- */
    //
    // Books, 2B, and what we actually claimed. All three are needed
    // because the interesting number is a DIFFERENCE, and a difference
    // between two figures cannot say which of them moved.

    booksInvoiceCount: integer("books_invoice_count").default(0).notNull(),
    booksTaxableMinor: bigint("books_taxable_minor", { mode: "bigint" })
      .default(sql`0`)
      .notNull(),
    booksTaxMinor: bigint("books_tax_minor", { mode: "bigint" })
      .default(sql`0`)
      .notNull(),
    /** ⭐ Phase 33's determination: what we believe we may claim. */
    booksItcEligibleMinor: bigint("books_itc_eligible_minor", { mode: "bigint" })
      .default(sql`0`)
      .notNull(),

    twobRowCount: integer("twob_row_count").default(0).notNull(),
    twobTaxableMinor: bigint("twob_taxable_minor", { mode: "bigint" })
      .default(sql`0`)
      .notNull(),
    twobTaxMinor: bigint("twob_tax_minor", { mode: "bigint" })
      .default(sql`0`)
      .notNull(),
    /** ⭐ The Section 16(2)(aa) ceiling: what the portal says is ours. */
    twobItcAvailableMinor: bigint("twob_itc_available_minor", { mode: "bigint" })
      .default(sql`0`)
      .notNull(),

    matchedCount: integer("matched_count").default(0).notNull(),
    matchedBooksTaxMinor: bigint("matched_books_tax_minor", { mode: "bigint" })
      .default(sql`0`)
      .notNull(),
    matchedTwobTaxMinor: bigint("matched_twob_tax_minor", { mode: "bigint" })
      .default(sql`0`)
      .notNull(),

    inBooksNotIn2bCount: integer("in_books_not_in_2b_count").default(0).notNull(),
    inBooksNotIn2bTaxMinor: bigint("in_books_not_in_2b_tax_minor", { mode: "bigint" })
      .default(sql`0`)
      .notNull(),
    /** ⭐ The number the vendor-chase screen exists for. */
    itcAtRiskMinor: bigint("itc_at_risk_minor", { mode: "bigint" })
      .default(sql`0`)
      .notNull(),

    in2bNotInBooksCount: integer("in_2b_not_in_books_count").default(0).notNull(),
    in2bNotInBooksTaxMinor: bigint("in_2b_not_in_books_tax_minor", { mode: "bigint" })
      .default(sql`0`)
      .notNull(),

    /** What the ITC register actually put into the return, per Phase 33. */
    itcClaimedMinor: bigint("itc_claimed_minor", { mode: "bigint" })
      .default(sql`0`)
      .notNull(),

    /**
     * ⭐ WHICH VERSION OF THE MATCHING ENGINE PRODUCED THIS.
     *
     * ⚠️ NOT DECORATION. The engine is deterministic — the same inputs
     * give the same matches — but only for a FIXED engine. A tolerance
     * widened in a later release changes yesterday's answers, and the
     * only defence against "the system used to say these matched" is a
     * stamp saying which rules were in force.
     */
    engineVersion: varchar("engine_version", { length: 16 })
      .default("1")
      .notNull(),
    lastRunAt: timestamp("last_run_at", { withTimezone: true }),

    /** ⭐ The freeze. Set once, never cleared. */
    filedAt: timestamp("filed_at", { withTimezone: true }),
    filedBy: uuid("filed_by"),
    /** The GSTR-3B acknowledgement number, so the freeze names a return. */
    filedReference: varchar("filed_reference", { length: 64 }),

    notes: text("notes"),
    createdBy: uuid("created_by"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => ({
    /** ⭐ One reconciliation per GSTIN per period. The freeze key. */
    periodUnique: uniqueIndex("gstr2b_reconciliations_period_unique").on(
      t.tenantId,
      t.gstin,
      t.taxPeriod,
    ),
    statusIdx: index("gstr2b_reconciliations_status_idx").on(t.tenantId, t.status),
    registrationIdx: index("gstr2b_reconciliations_registration_idx").on(
      t.tenantId,
      t.registrationId,
      t.taxPeriod,
    ),

    periodShape: check(
      "gstr2b_reconciliations_period_shape",
      sql`${t.taxPeriod} ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'`,
    ),
    nonNegative: check(
      "gstr2b_reconciliations_non_negative",
      sql`${t.booksInvoiceCount} >= 0 AND ${t.booksTaxableMinor} >= 0
          AND ${t.booksTaxMinor} >= 0 AND ${t.booksItcEligibleMinor} >= 0
          AND ${t.twobRowCount} >= 0 AND ${t.twobTaxableMinor} >= 0
          AND ${t.twobTaxMinor} >= 0 AND ${t.twobItcAvailableMinor} >= 0
          AND ${t.matchedCount} >= 0 AND ${t.matchedBooksTaxMinor} >= 0
          AND ${t.matchedTwobTaxMinor} >= 0
          AND ${t.inBooksNotIn2bCount} >= 0 AND ${t.inBooksNotIn2bTaxMinor} >= 0
          AND ${t.in2bNotInBooksCount} >= 0 AND ${t.in2bNotInBooksTaxMinor} >= 0
          AND ${t.itcAtRiskMinor} >= 0 AND ${t.itcClaimedMinor} >= 0`,
    ),
    /**
     * ⭐⭐ THE IDENTITY THE WHOLE SUMMARY RESTS ON, ENFORCED BY THE
     * DATABASE RATHER THAN BY THE FUNCTION THAT COMPUTES IT.
     *
     *     books tax = matched (books side) + in books, not in 2B
     *     2B tax    = matched (2B side)    + in 2B, not in books
     *
     * ⚠️ IF EITHER FAILS, EVERY INVOICE IS NOT IN EXACTLY ONE BUCKET —
     * which means an invoice was either counted twice or dropped, and a
     * summary that drops an invoice reports a supplier as having filed
     * when they have not. That is a credit claimed under Section
     * 16(2)(aa) with nothing behind it, and it is invisible: the totals
     * still look like totals.
     */
    booksReconciles: check(
      "gstr2b_reconciliations_books_reconcile",
      sql`${t.booksTaxMinor} = ${t.matchedBooksTaxMinor} + ${t.inBooksNotIn2bTaxMinor}`,
    ),
    twobReconciles: check(
      "gstr2b_reconciliations_twob_reconcile",
      sql`${t.twobTaxMinor} = ${t.matchedTwobTaxMinor} + ${t.in2bNotInBooksTaxMinor}`,
    ),
    /** ⭐ A filed reconciliation names when it was filed, and vice versa. */
    filedConsistent: check(
      "gstr2b_reconciliations_filed_consistent",
      sql`(${t.status} = 'filed') = (${t.filedAt} IS NOT NULL)`,
    ),
  }),
);

/* ------------------------------------------------------------------ */
/* ⭐⭐ THE MATCH — WHAT MATCHED, WHY, AND WHO SAID SO                 */
/* ------------------------------------------------------------------ */

/**
 * ══════════════════════════════════════════════════════════════════════
 * ⭐ EVERY MATCH IS EXPLAINED, BECAUSE EVERY MATCH IS DEFENDED
 * ══════════════════════════════════════════════════════════════════════
 * The question an officer asks is never "did it match". It is:
 *
 *     "You have claimed credit on this invoice. The 2B shows a different
 *      number. On what basis did you treat them as the same document?"
 *
 * `matched_on` answers it field by field, with both values side by side.
 * `differences` records what did NOT agree, in paise. `explanation` is
 * the sentence a person wrote or the engine produced. `action_by` is who
 * accepted it.
 *
 * ⚠️ AND `action_by` IS ENFORCED, NOT ADVISORY. The CHECK below refuses
 * an ACCEPTED match below `exact` confidence with nobody named against
 * it. That is the rule the whole phase turns on: the engine may propose
 * anything; only `exact` may be taken without a human, because only
 * `exact` has nothing left to judge.
 */
export const gstr2bMatches = pgTable(
  "gstr2b_matches",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    tenantId: uuid("tenant_id")
      .notNull()
      .references(() => tenants.id, { onDelete: "cascade" }),

    /** Composite FK → gstr2b_reconciliations (id, tenant_id). CASCADE. */
    reconciliationId: uuid("reconciliation_id").notNull(),

    /**
     * ⚠️ BOTH SIDES ARE NULLABLE AND EXACTLY THE RIGHT ONES MAY BE NULL.
     * A row with only a 2B pointer is a supplier declaration we never
     * recorded; a row with only a purchase pointer is a bill the supplier
     * never filed. A row with neither is a match to nothing, and the
     * CHECK below refuses it.
     */
    gstr2bRowId: uuid("gstr2b_row_id"),
    purchaseInvoiceId: uuid("purchase_invoice_id"),

    /** Denormalised so the vendor-chase list is one table scan. */
    vendorId: uuid("vendor_id"),
    supplierGstin: varchar("supplier_gstin", { length: 15 }),

    matchCategory: gstr2bMatchCategoryEnum("match_category").notNull(),
    confidence: gstr2bMatchConfidenceEnum("confidence").notNull(),
    /** 0–100. Ordering for the worklist; never a decision on its own. */
    matchScore: integer("match_score").default(0).notNull(),

    /**
     * ⭐ WHICH FIELDS AGREED, WITH BOTH VALUES. The audit answer.
     */
    matchedOn: jsonb("matched_on")
      .$type<
        {
          field: string;
          twoB: string | null;
          books: string | null;
          agrees: boolean;
          deltaMinor?: string;
        }[]
      >()
      .default(sql`'[]'::jsonb`)
      .notNull(),

    /** ⭐ What did NOT agree. Empty on an exact match, by definition. */
    differences: jsonb("differences")
      .$type<
        {
          field: string;
          twoB: string | null;
          books: string | null;
          agrees: boolean;
          deltaMinor?: string;
        }[]
      >()
      .default(sql`'[]'::jsonb`)
      .notNull(),

    /** Signed. 2B minus books, so a positive delta means they declared more. */
    taxableDeltaMinor: bigint("taxable_delta_minor", { mode: "bigint" })
      .default(sql`0`)
      .notNull(),
    taxDeltaMinor: bigint("tax_delta_minor", { mode: "bigint" })
      .default(sql`0`)
      .notNull(),

    /**
     * ⭐ HOW MUCH CREDIT THIS EXCEPTION PUTS AT RISK.
     *
     * ⚠️ IT IS THE **ELIGIBLE** TAX FROM PHASE 33'S DETERMINATION, NOT
     * THE TAX ON THE DOCUMENT. A bill for a building we are constructing
     * on our own account carries tax that was never claimable — Section
     * 17(5)(d) blocked it — so a supplier who failed to file it has cost
     * us nothing. Reporting the gross tax would put the largest numbers
     * on the chase list against the vendors it is pointless to chase, and
     * a chase list nobody can act on is a chase list nobody opens.
     */
    itcAtRiskMinor: bigint("itc_at_risk_minor", { mode: "bigint" })
      .default(sql`0`)
      .notNull(),

    /**
     * How many book invoices were equally good candidates.
     *
     * ⚠️ RECORDED RATHER THAN RESOLVED. Two invoices from one supplier on
     * one day for one amount, with numbers that normalise the same, are
     * genuinely ambiguous — and a machine that silently picks one has
     * made a decision it cannot defend. The engine picks the first in a
     * documented sort order so the answer is reproducible, and says here
     * that it had a choice.
     */
    ambiguousCandidates: integer("ambiguous_candidates").default(0).notNull(),

    /** One sentence, written for the person who has to defend it. */
    explanation: text("explanation").notNull(),
    engineVersion: varchar("engine_version", { length: 16 }).default("1").notNull(),

    action: gstr2bMatchActionEnum("action").default("pending").notNull(),
    /** ⭐ WHY the human decided. Free text, and required for a refusal. */
    actionReason: text("action_reason"),
    actionBy: uuid("action_by"),
    actionAt: timestamp("action_at", { withTimezone: true }),

    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => ({
    /** The worklist: one period, worst first. */
    worklistIdx: index("gstr2b_matches_worklist_idx").on(
      t.tenantId,
      t.reconciliationId,
      t.matchCategory,
      t.action,
    ),
    /** ⭐ The vendor-chase roll-up. */
    supplierIdx: index("gstr2b_matches_supplier_idx").on(
      t.tenantId,
      t.supplierGstin,
      t.matchCategory,
    ),
    vendorIdx: index("gstr2b_matches_vendor_idx").on(t.tenantId, t.vendorId),
    invoiceIdx: index("gstr2b_matches_invoice_idx").on(t.tenantId, t.purchaseInvoiceId),

    /**
     * ⭐⭐ ONE-TO-ONE, AND IT IS WHAT MAKES THE SUMMARY ADD UP.
     *
     * ⚠️ Without these two indexes a re-run that appended instead of
     * replacing would match one 2B row to two purchase invoices, and the
     * "matched" total would exceed the books total while every individual
     * row still looked correct. The identity CHECKs on the
     * reconciliation would then fail — which is the right failure, but
     * these catch it at the row that caused it.
     */
    oneMatchPer2bRow: uniqueIndex("gstr2b_matches_one_per_2b_row")
      .on(t.tenantId, t.reconciliationId, t.gstr2bRowId)
      .where(sql`${t.gstr2bRowId} IS NOT NULL`),
    oneMatchPerInvoice: uniqueIndex("gstr2b_matches_one_per_invoice")
      .on(t.tenantId, t.reconciliationId, t.purchaseInvoiceId)
      .where(sql`${t.purchaseInvoiceId} IS NOT NULL`),

    /** A match to nothing is not a match. */
    hasASide: check(
      "gstr2b_matches_has_a_side",
      sql`${t.gstr2bRowId} IS NOT NULL OR ${t.purchaseInvoiceId} IS NOT NULL`,
    ),
    /**
     * ⚠️ THE CATEGORY AND THE POINTERS MUST AGREE. An `exact` match with
     * no purchase invoice is a contradiction, and it is the shape a
     * partially-written re-run leaves behind.
     */
    categoryMatchesSides: check(
      "gstr2b_matches_category_matches_sides",
      sql`CASE ${t.matchCategory}
            WHEN 'in_2b_not_in_books'
              THEN ${t.gstr2bRowId} IS NOT NULL AND ${t.purchaseInvoiceId} IS NULL
            WHEN 'in_books_not_in_2b'
              THEN ${t.purchaseInvoiceId} IS NOT NULL AND ${t.gstr2bRowId} IS NULL
            ELSE ${t.gstr2bRowId} IS NOT NULL AND ${t.purchaseInvoiceId} IS NOT NULL
          END`,
    ),
    /**
     * ⭐⭐ THE RULE THE PHASE EXISTS TO ENFORCE.
     *
     * Nothing below `exact` may be ACCEPTED without a named human.
     *
     * ⚠️ IN THE DATABASE BECAUSE THE ENGINE IS ONE WRITE PATH OF SEVERAL.
     * A bulk-accept button, an import script and a future API route are
     * the others, and "accept everything above 80%" is the single most
     * requested feature in every reconciliation product ever built. It is
     * also the feature that produces a year of matches nobody can defend,
     * discovered at the one assessment where it matters.
     */
    noSilentAutoAccept: check(
      "gstr2b_matches_no_silent_auto_accept",
      sql`NOT (${t.action} = 'accepted'
               AND ${t.matchCategory} <> 'exact'
               AND ${t.actionBy} IS NULL)`,
    ),
    /**
     * ⚠️ A REJECTION OR A DEFERRAL WITHOUT A REASON IS A DECISION NOBODY
     * CAN REVIEW. Three months later "why is this still open" has no
     * answer, and the exception is re-investigated from scratch every
     * month until somebody accepts it to make it go away.
     */
    refusalHasReason: check(
      "gstr2b_matches_refusal_has_reason",
      sql`${t.action} NOT IN ('rejected','deferred')
          OR (${t.actionBy} IS NOT NULL AND ${t.actionReason} IS NOT NULL)`,
    ),
    /** A decision has a time; an undecided match does not. */
    actionTimed: check(
      "gstr2b_matches_action_timed",
      sql`(${t.action} = 'pending') = (${t.actionAt} IS NULL)`,
    ),
    scoreRange: check(
      "gstr2b_matches_score_range",
      sql`${t.matchScore} >= 0 AND ${t.matchScore} <= 100`,
    ),
    nonNegative: check(
      "gstr2b_matches_non_negative",
      sql`${t.itcAtRiskMinor} >= 0 AND ${t.ambiguousCandidates} >= 0`,
    ),
    /**
     * ⚠️ AN `exact` MATCH WITH A DIFFERENCE IS NOT AN EXACT MATCH. If the
     * engine ever labels one, the label is what a reviewer trusts and the
     * delta is what an officer finds.
     */
    exactHasNoDelta: check(
      "gstr2b_matches_exact_has_no_delta",
      sql`${t.matchCategory} <> 'exact'
          OR (${t.taxableDeltaMinor} = 0 AND ${t.taxDeltaMinor} = 0
              AND ${t.confidence} = 'exact')`,
    ),
  }),
);

/* ------------------------------------------------------------------ */
/* RELATIONS                                                           */
/* ------------------------------------------------------------------ */

export const gstr2bDocumentsRelations = relations(gstr2bDocuments, ({ one, many }) => ({
  tenant: one(tenants, {
    fields: [gstr2bDocuments.tenantId],
    references: [tenants.id],
  }),
  registration: one(gstRegistrations, {
    fields: [gstr2bDocuments.registrationId],
    references: [gstRegistrations.id],
  }),
  importer: one(users, {
    fields: [gstr2bDocuments.importedBy],
    references: [users.id],
  }),
  rows: many(gstr2bRows),
}));

export const gstr2bRowsRelations = relations(gstr2bRows, ({ one }) => ({
  tenant: one(tenants, { fields: [gstr2bRows.tenantId], references: [tenants.id] }),
  document: one(gstr2bDocuments, {
    fields: [gstr2bRows.documentId],
    references: [gstr2bDocuments.id],
  }),
}));

export const gstr2bReconciliationsRelations = relations(
  gstr2bReconciliations,
  ({ one, many }) => ({
    tenant: one(tenants, {
      fields: [gstr2bReconciliations.tenantId],
      references: [tenants.id],
    }),
    registration: one(gstRegistrations, {
      fields: [gstr2bReconciliations.registrationId],
      references: [gstRegistrations.id],
    }),
    document: one(gstr2bDocuments, {
      fields: [gstr2bReconciliations.documentId],
      references: [gstr2bDocuments.id],
    }),
    matches: many(gstr2bMatches),
  }),
);

export const gstr2bMatchesRelations = relations(gstr2bMatches, ({ one }) => ({
  tenant: one(tenants, { fields: [gstr2bMatches.tenantId], references: [tenants.id] }),
  reconciliation: one(gstr2bReconciliations, {
    fields: [gstr2bMatches.reconciliationId],
    references: [gstr2bReconciliations.id],
  }),
  gstr2bRow: one(gstr2bRows, {
    fields: [gstr2bMatches.gstr2bRowId],
    references: [gstr2bRows.id],
  }),
  purchaseInvoice: one(purchaseInvoices, {
    fields: [gstr2bMatches.purchaseInvoiceId],
    references: [purchaseInvoices.id],
  }),
  vendor: one(vendors, {
    fields: [gstr2bMatches.vendorId],
    references: [vendors.id],
  }),
  decidedBy: one(users, {
    fields: [gstr2bMatches.actionBy],
    references: [users.id],
  }),
}));

/* ------------------------------------------------------------------ */
/* INFERRED TYPES                                                      */
/* ------------------------------------------------------------------ */

export type Gstr2bDocument = typeof gstr2bDocuments.$inferSelect;
export type NewGstr2bDocument = typeof gstr2bDocuments.$inferInsert;
export type Gstr2bRow = typeof gstr2bRows.$inferSelect;
export type NewGstr2bRow = typeof gstr2bRows.$inferInsert;
export type Gstr2bReconciliation = typeof gstr2bReconciliations.$inferSelect;
export type NewGstr2bReconciliation = typeof gstr2bReconciliations.$inferInsert;
export type Gstr2bMatch = typeof gstr2bMatches.$inferSelect;
export type NewGstr2bMatch = typeof gstr2bMatches.$inferInsert;

export type Gstr2bSection = (typeof gstr2bSectionEnum.enumValues)[number];
export type Gstr2bSourceFormat = (typeof gstr2bSourceFormatEnum.enumValues)[number];
export type Gstr2bParseStatus = (typeof gstr2bParseStatusEnum.enumValues)[number];
export type Gstr2bItcAvailability =
  (typeof gstr2bItcAvailabilityEnum.enumValues)[number];
export type Gstr2bMatchCategory = (typeof gstr2bMatchCategoryEnum.enumValues)[number];
export type Gstr2bMatchConfidence =
  (typeof gstr2bMatchConfidenceEnum.enumValues)[number];
export type Gstr2bMatchAction = (typeof gstr2bMatchActionEnum.enumValues)[number];
export type Gstr2bReconciliationStatus =
  (typeof gstr2bReconciliationStatusEnum.enumValues)[number];
