"use client";

/**
 * Ordence — ⭐⭐⭐ THE SCREEN THAT MAKES THE INTEGRATION FRAME REACHABLE
 * Version: v1.17.0-alpha
 *
 * ══════════════════════════════════════════════════════════════════════
 * 🔴🔴 FOUR SESSIONS OF ENGINE, AND NO WAY IN
 * ══════════════════════════════════════════════════════════════════════
 * `createConnection`, `saveCredential`, `setConnectionActive` and
 * `removeConnection` have existed since v1.12.0. Every one compiled,
 * every one was tested, and not one was called by anything in the
 * browser. The connections page read. It could not write.
 *
 * ⚠️ So the honest description of the product before this file was: an
 * integration platform that required a database client to use.
 *
 * ══════════════════════════════════════════════════════════════════════
 * ⭐⭐ AND THE AUDIENCE IS A STRANGER, WHICH CHANGES EVERY DECISION
 * ══════════════════════════════════════════════════════════════════════
 * This is not written for the person who built it. It is written for
 * somebody who has been handed an ERP, has their own IndiaMART account
 * and their own WhatsApp number, and has never spoken to us.
 *
 * 🔴 THE TEST OF EVERY LABEL ON THIS SCREEN IS: could they finish
 * without asking anyone? That rules out three things that would
 * otherwise be here.
 *
 * ① NO JARGON FROM OUR SIDE. "Connector key", "path token" and
 *    "transport" are our words. They appear nowhere.
 *
 * ② NO STEP THAT NEEDS A TERMINAL. The verify token is generated by a
 *    button, because `openssl rand -hex 32` is a perfectly good way to
 *    produce one and a completely unusable instruction to give a
 *    business owner. A platform whose onboarding has a shell command in
 *    step four onboards nobody without a phone call.
 *
 * ③ NO GREEN TICK WE CANNOT JUSTIFY. Where we genuinely cannot prove a
 *    connection works — JustDial, until something arrives — the screen
 *    says so in those words rather than showing a reassuring badge.
 */

import { useState, useTransition } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { toast } from "sonner";

type Result<T> = { ok: true; data: T } | { ok: false; error: string };

export interface AvailableConnector {
  key: string;
  label: string;
  transport: string;
  selfService: boolean;
  setupNote: string;
  secretNames: readonly string[];
  verifyMethod: string;
}

export interface ManagedConnection {
  id: string;
  connectorKey: string;
  label: string;
  name: string;
  state: string;
  isActive: boolean;
  missingSecrets: readonly string[];
  storedSecrets: readonly string[];
  webhookUrl: string | null;
  secretNames: readonly string[];
  verifyMethod: string;
}

export function ConnectionManager({
  available,
  connections,
  vaultReady,
  createAction,
  saveCredentialAction,
  setActiveAction,
  removeAction,
  generateVerifyTokenAction,
  probeAction,
}: {
  available: readonly AvailableConnector[];
  connections: readonly ManagedConnection[];
  vaultReady: boolean;
  createAction: (i: unknown) => Promise<Result<{ id: string; webhookPath: string | null }>>;
  saveCredentialAction: (i: unknown) => Promise<Result<{ rotated: boolean; unchanged: boolean }>>;
  setActiveAction: (i: unknown) => Promise<Result<{ state: string }>>;
  removeAction: (i: unknown) => Promise<Result<{ secretsErased: number }>>;
  generateVerifyTokenAction: (
    i: unknown,
  ) => Promise<Result<{ verifyToken: string; connectorLabel: string }>>;
  probeAction: (
    i: unknown,
  ) => Promise<Result<{ ok: boolean; headline: string; detail: string }>>;
}) {
  const [pending, startTransition] = useTransition();
  const [adding, setAdding] = useState<string | null>(null);
  const [newName, setNewName] = useState("");
  /** ⚠️ Keyed by connection id AND secret name; two fields are never one state. */
  const [values, setValues] = useState<Record<string, string>>({});
  /**
   * 🔴 SHOWN ONCE, HELD IN MEMORY, NEVER RE-READABLE.
   * The server will not return it a second time. See `generateVerifyToken`.
   */
  const [mintedToken, setMintedToken] = useState<Record<string, string>>({});
  const [probeResult, setProbeResult] = useState<
    Record<string, { ok: boolean; headline: string; detail: string }>
  >({});

  function create(connectorKey: string) {
    const name = newName.trim();
    if (name.length === 0) {
      toast.error("Give it a name you will recognise later.");
      return;
    }
    startTransition(async () => {
      const r = await createAction({ connectorKey, name, config: {} });
      if (!r.ok) {
        toast.error(r.error);
        return;
      }
      setAdding(null);
      setNewName("");
      toast.success("Added, and switched off until it has a credential.");
    });
  }

  function saveSecret(connectionId: string, secretName: string) {
    const key = `${connectionId}:${secretName}`;
    const value = (values[key] ?? "").trim();
    if (value.length < 8) {
      toast.error("That looks too short to be a real credential.");
      return;
    }
    startTransition(async () => {
      const r = await saveCredentialAction({ connectionId, secretName, value });
      if (!r.ok) {
        toast.error(r.error);
        return;
      }
      // 🔴 CLEARED FROM THE FORM IMMEDIATELY ON SUCCESS. A key left
      // sitting in an input is a key in an autofill store and a key in a
      // screenshot.
      setValues((p) => ({ ...p, [key]: "" }));
      toast.success(
        r.data.unchanged
          ? "That is the same value as before. Nothing changed."
          : r.data.rotated
            ? "Replaced. The previous value is gone."
            : "Saved.",
      );
    });
  }

  function mintVerifyToken(connectionId: string) {
    startTransition(async () => {
      const r = await generateVerifyTokenAction({ connectionId });
      if (!r.ok) {
        toast.error(r.error);
        return;
      }
      setMintedToken((p) => ({ ...p, [connectionId]: r.data.verifyToken }));
      toast.success("Copy it now. It cannot be shown again.");
    });
  }

  function probe(connectionId: string) {
    startTransition(async () => {
      const r = await probeAction({ connectionId });
      if (!r.ok) {
        toast.error(r.error);
        return;
      }
      setProbeResult((p) => ({ ...p, [connectionId]: r.data }));
      if (r.data.ok) toast.success(r.data.headline);
      else toast.error(r.data.headline);
    });
  }

  function toggle(connectionId: string, active: boolean) {
    startTransition(async () => {
      const r = await setActiveAction({ connectionId, active });
      if (!r.ok) toast.error(r.error);
      else toast.success(active ? "Switched on." : "Switched off.");
    });
  }

  function remove(connectionId: string, name: string) {
    // ⚠️ A typed reason, not a confirm dialog. People dismiss dialogs.
    // 0064 also refuses the erase without one, so asking here means the
    // failure is a sentence on screen rather than an exception.
    const reason = window.prompt(
      `Removing "${name}" erases its stored credentials. They cannot be recovered.\n\nWhy are you removing it?`,
    );
    if (!reason || reason.trim().length < 5) {
      if (reason !== null) toast.error("A reason of at least five characters is needed.");
      return;
    }
    startTransition(async () => {
      const r = await removeAction({ connectionId, reason: reason.trim() });
      if (!r.ok) toast.error(r.error);
      else
        toast.success(
          `Removed. ${r.data.secretsErased} credential${r.data.secretsErased === 1 ? "" : "s"} erased.`,
        );
    });
  }

  return (
    <div className="space-y-6">
      {/* ── ADD ────────────────────────────────────────────────── */}
      <Card>
        <CardHeader className="pb-3">
          <CardTitle className="text-base">Connect an account</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4 text-sm">
          {available.map((a) => (
            <div key={a.key} className="rounded-md border p-3">
              <div className="flex flex-wrap items-center gap-2">
                <span className="font-medium">{a.label}</span>
                {!a.selfService && (
                  <Badge variant="secondary">their account manager sets this up</Badge>
                )}
                {a.transport === "push" && <Badge variant="secondary">they send to us</Badge>}
              </div>
              <p className="mt-1 max-w-3xl text-muted-foreground">{a.setupNote}</p>

              {adding === a.key ? (
                <div className="mt-3 flex flex-wrap items-end gap-2">
                  <div className="grow">
                    <Label htmlFor={`name-${a.key}`}>Name it</Label>
                    <Input
                      id={`name-${a.key}`}
                      value={newName}
                      placeholder={`${a.label} — main account`}
                      onChange={(e) => setNewName(e.target.value)}
                    />
                  </div>
                  <Button disabled={pending} onClick={() => create(a.key)}>
                    Add
                  </Button>
                  <Button variant="ghost" disabled={pending} onClick={() => setAdding(null)}>
                    Cancel
                  </Button>
                </div>
              ) : (
                <Button
                  className="mt-3"
                  variant="secondary"
                  disabled={pending}
                  onClick={() => {
                    setAdding(a.key);
                    setNewName("");
                  }}
                >
                  Add {a.label}
                </Button>
              )}
            </div>
          ))}
        </CardContent>
      </Card>

      {/* ── CONFIGURE ──────────────────────────────────────────── */}
      {connections.map((c) => {
        const minted = mintedToken[c.id];
        const result = probeResult[c.id];
        return (
          <Card key={c.id}>
            <CardHeader className="pb-3">
              <div className="flex flex-wrap items-center gap-2">
                <CardTitle className="text-base">{c.name}</CardTitle>
                <Badge variant="secondary">{c.label}</Badge>
                <Badge variant={c.state === "connected" ? "default" : "secondary"}>
                  {c.state}
                </Badge>
              </div>
            </CardHeader>

            <CardContent className="space-y-5 text-sm">
              {/* THE ADDRESS THEY HAVE TO GIVE THE FAR END */}
              {c.webhookUrl && (
                <div>
                  <p className="text-xs uppercase text-muted-foreground">
                    Give this address to {c.label}
                  </p>
                  <code className="mt-1 block break-all rounded bg-muted p-2 text-xs">
                    {c.webhookUrl}
                  </code>
                  <Button
                    variant="ghost"
                    className="mt-1 h-7 px-2 text-xs"
                    onClick={() => {
                      void navigator.clipboard.writeText(c.webhookUrl ?? "");
                      toast.success("Copied.");
                    }}
                  >
                    Copy
                  </Button>
                </div>
              )}

              {/* THE CREDENTIALS, ONE FIELD PER SECRET THE POLICY NAMES */}
              {c.secretNames.length > 0 && (
                <div className="space-y-3">
                  <p className="text-xs uppercase text-muted-foreground">Credentials</p>
                  {!vaultReady && (
                    <p className="text-destructive">
                      These cannot be saved until the encryption key is set on the
                      server. Nothing is stored in the clear as a fallback.
                    </p>
                  )}
                  {c.secretNames.map((s) => {
                    const stored = c.storedSecrets.includes(s);
                    const key = `${c.id}:${s}`;

                    // ⭐ THE VERIFY TOKEN IS THE ONE WE GENERATE RATHER
                    // THAN ASK FOR. Asking a business owner to invent a
                    // random string gets you "password123" in a field
                    // whose whole job is to be unguessable.
                    if (s === "verify_token") {
                      return (
                        <div key={s} className="rounded-md border p-3">
                          <div className="flex flex-wrap items-center gap-2">
                            <span className="font-medium">Webhook verify token</span>
                            {stored && <Badge variant="secondary">set</Badge>}
                          </div>
                          <p className="mt-1 text-muted-foreground">
                            {c.label} asks for this when you add the webhook. Generate
                            it here and paste it there.
                          </p>
                          {minted ? (
                            <>
                              <code className="mt-2 block break-all rounded bg-muted p-2 text-xs">
                                {minted}
                              </code>
                              <p className="mt-1 text-xs text-destructive">
                                Copy it now. It will not be shown again, and there is
                                no way to look it up later. Losing it costs you one
                                click to generate another.
                              </p>
                              <Button
                                variant="ghost"
                                className="mt-1 h-7 px-2 text-xs"
                                onClick={() => {
                                  void navigator.clipboard.writeText(minted);
                                  toast.success("Copied.");
                                }}
                              >
                                Copy
                              </Button>
                            </>
                          ) : (
                            <Button
                              className="mt-2"
                              variant="secondary"
                              disabled={pending || !vaultReady}
                              onClick={() => mintVerifyToken(c.id)}
                            >
                              {stored ? "Generate a new one" : "Generate"}
                            </Button>
                          )}
                        </div>
                      );
                    }

                    return (
                      <div key={s} className="flex flex-wrap items-end gap-2">
                        <div className="grow">
                          <Label htmlFor={key}>
                            {labelFor(s)}{" "}
                            {stored && (
                              <span className="text-xs text-muted-foreground">
                                (already saved; typing here replaces it)
                              </span>
                            )}
                          </Label>
                          <Input
                            id={key}
                            type="password"
                            autoComplete="off"
                            spellCheck={false}
                            value={values[key] ?? ""}
                            placeholder={stored ? "•••••••• stored" : "paste it here"}
                            onChange={(e) =>
                              setValues((p) => ({ ...p, [key]: e.target.value }))
                            }
                          />
                        </div>
                        <Button
                          disabled={pending || !vaultReady}
                          onClick={() => saveSecret(c.id, s)}
                        >
                          Save
                        </Button>
                      </div>
                    );
                  })}
                </div>
              )}

              {/* THE PROOF */}
              <div>
                <div className="flex flex-wrap items-center gap-2">
                  <Button variant="secondary" disabled={pending} onClick={() => probe(c.id)}>
                    Test it
                  </Button>
                  <Button
                    variant={c.isActive ? "ghost" : "default"}
                    disabled={pending}
                    onClick={() => toggle(c.id, !c.isActive)}
                  >
                    {c.isActive ? "Switch off" : "Switch on"}
                  </Button>
                  <Button
                    variant="ghost"
                    className="text-destructive"
                    disabled={pending}
                    onClick={() => remove(c.id, c.name)}
                  >
                    Remove
                  </Button>
                </div>

                {c.verifyMethod === "inbound_only" && !result && (
                  <p className="mt-2 text-muted-foreground">
                    There is nothing for us to call here. {c.label} sends to us, so the
                    only thing a test can tell you is whether anything has arrived yet.
                  </p>
                )}

                {result && (
                  <div className="mt-3 rounded-md border p-3">
                    <p
                      className={
                        result.ok ? "font-medium" : "font-medium text-destructive"
                      }
                    >
                      {result.headline}
                    </p>
                    <p className="mt-1 text-muted-foreground">{result.detail}</p>
                  </div>
                )}
              </div>
            </CardContent>
          </Card>
        );
      })}
    </div>
  );
}

/**
 * ⚠️ OUR INTERNAL NAMES ARE NOT THE FAR END'S NAMES, AND THE FAR END'S
 * WIN. Somebody is looking at Meta's dashboard while they read this, and
 * a field called `app_secret` here had better be called App Secret
 * there, because they are matching strings by eye.
 */
function labelFor(secretName: string): string {
  switch (secretName) {
    case "api_key":
      return "CRM API key";
    case "access_token":
      return "Access token";
    case "app_secret":
      return "App secret";
    case "webhook_signing_secret":
      return "Webhook signing secret";
    default:
      return secretName;
  }
}
