-- ############################################################################
-- 0118 · THE DRAWING REGISTER — AND A MEASUREMENT THAT CITES ITS SOURCE
-- ############################################################################
--
-- Repo: app.ordence   ·   Base: v1.74.0-alpha   ·   Migration number: 0118
--
-- ⚠️ NO `BEGIN`/`COMMIT`. The Neon browser console sends every statement on its
--    own connection. Every statement below is independently idempotent.
--
-- ############################################################################
-- 🔴 WHAT IS WRONG TODAY
-- ############################################################################
--
-- This product has `boqs`, `boq_items`, `rate_analyses`, `measurement_books`
-- and `measurement_entries` — a complete construction billing chain — and
-- NOTHING ANYWHERE HOLDS A DRAWING. Every quantity in that chain was typed in
-- by somebody reading a printed sheet, and the answer to "where did this
-- 412 square metres come from" is a person's memory.
--
-- ⚠️ AND `documents` IS NOT AN ANSWER. It holds a file against an entity, which
--    is right for a signed contract and wrong for a drawing: a drawing has a
--    NUMBER, a REVISION, a SCALE, and a rule that revision C supersedes B.
--    A folder of PDFs named "final_final_2.dwg" is what every site office
--    already has and is the thing this table exists to replace.
--
-- ############################################################################
-- ⭐⭐⭐ THE THREE PROPERTIES THIS SCHEMA IS BUILT AROUND
-- ############################################################################
--
-- ① THE ORIGINAL FILE IS NEVER MODIFIED. Markups are rows in their own table,
--    positioned in DRAWING COORDINATES, and the file that goes back out is
--    byte-identical to the one that came in. A consultant who receives their
--    own drawing back with our annotations burned into it has been handed a
--    document they cannot use and did not agree to.
--
-- ② A REVISION IS IMMUTABLE ONCE SUPERSEDED. Rev B is what the slab was poured
--    against; editing it after Rev C arrives destroys the only evidence of
--    what was built to what.
--
-- ③ 🔴 A MEASUREMENT CITES THE REVISION AND THE UNIT DECISION IT CAME FROM.
--    `lib/cad/units.ts` refuses to measure a drawing that does not state its
--    units — about a third of DXFs in circulation — so somebody has to say.
--    That is a DECISION, it is recorded with their name on it, and every
--    quantity derived from it carries the reference. "412 m², from DRG-102 Rev
--    C, at 1 unit = 1 mm as set by R. Sharma on 14 August" is a number an
--    auditor can check. "412" is not.
--
-- ############################################################################

-- ============================================================================
-- ⓪ THE DOCUMENT CATEGORY — RUN THIS FIRST, ON ITS OWN
-- ============================================================================
--
-- ⚠️ A DRAWING'S FILE GOES THROUGH THE SAME UPLOAD AS EVERY OTHER FILE in the
--    product — one storage path, one set of magic-byte checks, one rate limit,
--    one retention story. `documents.entity_type` is an enum, deliberately, so
--    a typo cannot silently create a category no screen ever queries. Adding a
--    member is a migration, which is the correct amount of friction.
--
-- 🔴 `ALTER TYPE ... ADD VALUE` CANNOT BE USED IN THE SAME TRANSACTION THAT
--    ADDS IT. In the Neon console every statement gets its own transaction, so
--    this is safe there. If you ever run this file through a client that wraps
--    it in one, run this statement by itself first.

ALTER TYPE public.document_entity_type ADD VALUE IF NOT EXISTS 'drawing';


-- ============================================================================
-- ① THE DRAWING
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.drawings (
    id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id      uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,

    -- ⭐ THE DRAWING NUMBER, AS THE PROJECT WRITES IT. Not generated by us:
    --    every consultant on the job already has a numbering system and ours
    --    would be a second one nobody uses.
    drawing_number varchar(80)  NOT NULL,
    title          varchar(255) NOT NULL,

    -- ⚠️ NULLABLE. A tender drawing arrives before the project exists in the
    --    system, and refusing it would send it back to the shared drive.
    project_id     uuid,

    discipline     varchar(40) NOT NULL DEFAULT 'architectural',

    -- ⭐ THE CURRENT REVISION. Denormalised deliberately: "which sheet is
    --    current" is asked on every screen and a lateral join for it on a
    --    register of 4,000 drawings is the query that makes the page slow.
    current_revision_id uuid,

    status         varchar(20) NOT NULL DEFAULT 'for_information',

    created_at     timestamptz NOT NULL DEFAULT now(),
    created_by     uuid NOT NULL REFERENCES public.users(id) ON DELETE RESTRICT,
    updated_at     timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT drawings_discipline_known
        CHECK (discipline IN ('architectural', 'structural', 'mep', 'civil',
                              'survey', 'landscape', 'interior', 'other')),

    -- 🔴 THE STATUS IS THE ONE AN INDIAN SITE ACTUALLY USES, and the
    --    distinction between the first two is the one that matters: a drawing
    --    marked GOOD FOR CONSTRUCTION is the one somebody builds from.
    CONSTRAINT drawings_status_known
        CHECK (status IN ('for_information', 'for_approval', 'good_for_construction',
                          'as_built', 'superseded', 'void')),

    CONSTRAINT drawings_number_not_blank
        CHECK (length(btrim(drawing_number)) > 0)
);

-- 🔴 ONE DRAWING NUMBER PER WORKSPACE PER PROJECT. Two sheets sharing a number
--    is how a site pours a slab to the wrong one, and it is exactly what a
--    shared drive cannot prevent.
--
-- ⚠️ TWO INDEXES, BECAUSE NULL IS NOT EQUAL TO NULL IN SQL. A single unique
--    index on (tenant, project, number) does NOT stop two project-less
--    drawings sharing a number — every row with a NULL project is distinct
--    from every other. The partial pair below covers both cases.
CREATE UNIQUE INDEX IF NOT EXISTS drawings_number_in_project
    ON public.drawings (tenant_id, project_id, upper(btrim(drawing_number)))
 WHERE project_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS drawings_number_without_project
    ON public.drawings (tenant_id, upper(btrim(drawing_number)))
 WHERE project_id IS NULL;

CREATE INDEX IF NOT EXISTS drawings_tenant_idx
    ON public.drawings (tenant_id, discipline, drawing_number);

COMMENT ON TABLE public.drawings IS
    'One drawing, whatever its revision. The number is the project''s own. '
    'Unique per project, case-insensitively, because two sheets sharing a '
    'number is how a site builds to the wrong one.';

ALTER TABLE public.drawings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.drawings FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS drawings_tenant_isolation ON public.drawings;
CREATE POLICY drawings_tenant_isolation
    ON public.drawings
    USING      (tenant_id = app_current_tenant_id())
    WITH CHECK (tenant_id = app_current_tenant_id());


-- ============================================================================
-- ② THE REVISION — THE FILE, AND WHAT WE MADE OF IT
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.drawing_revisions (
    id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id      uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    drawing_id     uuid NOT NULL REFERENCES public.drawings(id) ON DELETE CASCADE,

    -- ⭐ "A", "B", "P1", "0". Free text because every consultant differs.
    revision       varchar(20) NOT NULL,
    -- ⚠️ AND AN ORDER, SEPARATELY. "P2" does not sort after "P10" as text, and
    --    "which is later" is the only question this column exists to answer.
    revision_order integer NOT NULL,

    -- ⭐ THE FILE ITSELF LIVES IN `documents`. One storage path in the product,
    --    with one set of magic-byte checks and one retention story.
    document_id    uuid NOT NULL REFERENCES public.documents(id) ON DELETE RESTRICT,

    source_format  varchar(12) NOT NULL,

    -- ⚠️ WHAT THE PARSE FOUND. Counts, not geometry: the geometry is in the
    --    file and re-parsed on demand, and a second copy of it here would go
    --    stale the first time the engine improves.
    entity_count   integer NOT NULL DEFAULT 0,
    layer_count    integer NOT NULL DEFAULT 0,
    -- 🔴 WHAT ORDENCE COULD NOT READ, BY NAME. `{"HATCH": 412}`. A viewer that
    --    drops what it cannot read and shows the rest LOOKS like it worked.
    unsupported    jsonb NOT NULL DEFAULT '{}'::jsonb,

    -- Extents in drawing units, so a later measurement can be sanity-checked.
    extent_min_x   double precision,
    extent_min_y   double precision,
    extent_max_x   double precision,
    extent_max_y   double precision,

    -- ⭐⭐ THE UNIT, AND WHO DECIDED IT.
    --
    -- 🔴 `declared_unit` IS WHAT THE FILE SAID. `assumed_unit` IS WHAT A PERSON
    --    SAID WHEN THE FILE DID NOT. They are separate columns on purpose: a
    --    single column would make "the drawing says millimetres" and "Ramesh
    --    thinks it is millimetres" indistinguishable six months later, and only
    --    one of those is evidence.
    declared_unit  varchar(20),
    assumed_unit   varchar(20),
    assumed_by     uuid REFERENCES public.users(id) ON DELETE RESTRICT,
    assumed_at     timestamptz,

    issued_on      date,
    received_at    timestamptz NOT NULL DEFAULT now(),
    uploaded_by    uuid NOT NULL REFERENCES public.users(id) ON DELETE RESTRICT,

    -- ⚠️ SET WHEN A LATER REVISION ARRIVES. From then on this row is frozen.
    superseded_at  timestamptz,

    notes          text,

    CONSTRAINT drawing_revisions_format_known
        CHECK (source_format IN ('dxf', 'pdf', 'svg', 'image')),

    CONSTRAINT drawing_revisions_unit_known
        CHECK ((declared_unit IS NULL OR declared_unit IN
                ('unitless','inches','feet','miles','millimetres','centimetres',
                 'metres','kilometres','microinches','mils','yards'))
           AND (assumed_unit IS NULL OR assumed_unit IN
                ('inches','feet','miles','millimetres','centimetres',
                 'metres','kilometres','microinches','mils','yards'))),

    -- 🔴 AN ASSUMPTION IS SOMEBODY'S ASSUMPTION. All three columns together or
    --    none of them: an assumed unit with nobody's name on it is exactly the
    --    number an auditor will ask about and nobody will be able to answer.
    CONSTRAINT drawing_revisions_assumption_is_attributed
        CHECK ((assumed_unit IS NULL) = (assumed_by IS NULL)
           AND (assumed_unit IS NULL) = (assumed_at IS NULL)),

    -- ⚠️ AND YOU DO NOT ASSUME WHAT THE FILE ALREADY TOLD YOU. Overriding a
    --    stated unit is a different act — it means the file is wrong — and it
    --    is not what this column is for.
    CONSTRAINT drawing_revisions_no_assumption_over_declaration
        CHECK (assumed_unit IS NULL
               OR declared_unit IS NULL
               OR declared_unit = 'unitless'),

    CONSTRAINT drawing_revisions_counts_sane
        CHECK (entity_count >= 0 AND layer_count >= 0)
);

-- 🔴 ONE REVISION LABEL PER DRAWING, and one ORDER per drawing. Two rows both
--    claiming to be Rev C, or two both claiming to be the third issue, is a
--    register that cannot answer the only question it exists for.
CREATE UNIQUE INDEX IF NOT EXISTS drawing_revisions_label_once
    ON public.drawing_revisions (drawing_id, upper(btrim(revision)));

CREATE UNIQUE INDEX IF NOT EXISTS drawing_revisions_order_once
    ON public.drawing_revisions (drawing_id, revision_order);

CREATE INDEX IF NOT EXISTS drawing_revisions_drawing_idx
    ON public.drawing_revisions (tenant_id, drawing_id, revision_order DESC);

ALTER TABLE public.drawing_revisions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.drawing_revisions FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS drawing_revisions_tenant_isolation ON public.drawing_revisions;
CREATE POLICY drawing_revisions_tenant_isolation
    ON public.drawing_revisions
    USING      (tenant_id = app_current_tenant_id())
    WITH CHECK (tenant_id = app_current_tenant_id());

ALTER TABLE public.drawings
    DROP CONSTRAINT IF EXISTS drawings_current_revision_fk;
ALTER TABLE public.drawings
    ADD CONSTRAINT drawings_current_revision_fk
    FOREIGN KEY (current_revision_id)
    REFERENCES public.drawing_revisions(id) ON DELETE SET NULL;


-- ============================================================================
-- ③ 🔴 THE MARKUP — AN OVERLAY, NEVER AN EDIT
-- ============================================================================
--
-- ⚠️ POSITIONED IN DRAWING COORDINATES, NOT IN SCREEN PIXELS. A markup stored
--    at "x = 412 pixels" is a markup that moves when somebody resizes their
--    window, and is meaningless on a print. Stored in the drawing's own
--    coordinate system it stays exactly where it was put, at every zoom, on
--    every screen and on paper.

CREATE TABLE IF NOT EXISTS public.drawing_markups (
    id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id      uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    revision_id    uuid NOT NULL REFERENCES public.drawing_revisions(id) ON DELETE CASCADE,

    kind           varchar(20) NOT NULL,

    -- ⭐ THE GEOMETRY, IN DRAWING UNITS. `[{"x":0,"y":0}, …]`.
    points         jsonb NOT NULL,
    body           text,
    colour         varchar(9) NOT NULL DEFAULT '#e11d48',

    -- ⚠️ A MARKUP BELONGS TO A REVISION, NOT TO A DRAWING. A comment about
    --    Rev B is not a comment about Rev C — the thing it points at may have
    --    moved — and carrying it forward silently is how a resolved comment
    --    reappears on a sheet that already fixed it.
    created_at     timestamptz NOT NULL DEFAULT now(),
    created_by     uuid NOT NULL REFERENCES public.users(id) ON DELETE RESTRICT,

    resolved_at    timestamptz,
    resolved_by    uuid REFERENCES public.users(id) ON DELETE RESTRICT,

    CONSTRAINT drawing_markups_kind_known
        CHECK (kind IN ('cloud', 'arrow', 'text', 'dimension', 'highlight', 'pin')),

    CONSTRAINT drawing_markups_resolution_pair
        CHECK ((resolved_at IS NULL) = (resolved_by IS NULL)),

    -- ⚠️ A TEXT MARKUP WITH NO TEXT IS A DOT NOBODY CAN ACT ON.
    CONSTRAINT drawing_markups_text_has_body
        CHECK (kind <> 'text' OR length(btrim(coalesce(body, ''))) > 0),

    CONSTRAINT drawing_markups_points_is_array
        CHECK (jsonb_typeof(points) = 'array' AND jsonb_array_length(points) > 0)
);

CREATE INDEX IF NOT EXISTS drawing_markups_revision_idx
    ON public.drawing_markups (tenant_id, revision_id, created_at);

-- ⭐ THE OPEN ONES, which is the list a design review actually works from.
CREATE INDEX IF NOT EXISTS drawing_markups_open_idx
    ON public.drawing_markups (tenant_id, revision_id)
 WHERE resolved_at IS NULL;

ALTER TABLE public.drawing_markups ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.drawing_markups FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS drawing_markups_tenant_isolation ON public.drawing_markups;
CREATE POLICY drawing_markups_tenant_isolation
    ON public.drawing_markups
    USING      (tenant_id = app_current_tenant_id())
    WITH CHECK (tenant_id = app_current_tenant_id());


-- ============================================================================
-- ④ ⭐⭐⭐ A MEASUREMENT THAT CITES ITS SOURCE
-- ============================================================================
--
-- 🔴 THIS IS THE TABLE THAT CONNECTS A DRAWING TO THE BILLING CHAIN. Without
--    it a quantity in a BOQ is a number somebody typed; with it, it is
--    "412.150 m², taken off DRG-102 Rev C on layer FLOOR-SLAB, at 1 unit =
--    1 mm as declared by the file, ±0.004 m² from curve flattening".
--
-- ⚠️ THE ERROR BOUND IS A COLUMN. `lib/cad/geometry.ts` returns one with every
--    area, because flattening a curve to measure the region it encloses is an
--    approximation. An area used to price concrete, given to three decimals
--    with no error bound, is a number somebody will treat as exact.

CREATE TABLE IF NOT EXISTS public.drawing_measurements (
    id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id      uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    revision_id    uuid NOT NULL REFERENCES public.drawing_revisions(id) ON DELETE RESTRICT,

    kind           varchar(12) NOT NULL,
    label          varchar(200) NOT NULL,
    layer          varchar(120),

    -- ⭐ IN SI, ALWAYS. Metres and square metres, whatever the drawing used.
    --    Storing the drawing's own number would mean every consumer has to
    --    know the drawing's unit to add two measurements together.
    value_si       double precision NOT NULL,
    -- 🔴 AND THE BOUND. See the header.
    max_error_si   double precision NOT NULL DEFAULT 0,
    is_exact       boolean NOT NULL DEFAULT false,

    -- ⚠️ THE UNIT BASIS, COPIED AT THE TIME. If somebody later changes the
    --    assumed unit on the revision, this measurement does not silently
    --    change with it — it becomes visibly inconsistent, which is the
    --    correct outcome and the one a re-measure exists to fix.
    unit_basis     varchar(20) NOT NULL,
    unit_was_assumed boolean NOT NULL,

    -- ⭐ THE GEOMETRY MEASURED, so it can be shown again on the drawing.
    points         jsonb NOT NULL,

    taken_at       timestamptz NOT NULL DEFAULT now(),
    taken_by       uuid NOT NULL REFERENCES public.users(id) ON DELETE RESTRICT,

    -- ⚠️ NULLABLE. A takeoff exists before it is attached to a BOQ line.
    boq_item_id    uuid,

    CONSTRAINT drawing_measurements_kind_known
        CHECK (kind IN ('length', 'area', 'count')),

    CONSTRAINT drawing_measurements_value_sane
        CHECK (value_si >= 0 AND max_error_si >= 0),

    -- 🔴 EXACT MEANS EXACT. A measurement flagged exact with an error bound on
    --    it is a contradiction, and the flag is what a BOQ would rely on.
    CONSTRAINT drawing_measurements_exact_has_no_error
        CHECK (is_exact = false OR max_error_si = 0),

    CONSTRAINT drawing_measurements_label_not_blank
        CHECK (length(btrim(label)) > 0),

    CONSTRAINT drawing_measurements_points_is_array
        CHECK (jsonb_typeof(points) = 'array')
);

CREATE INDEX IF NOT EXISTS drawing_measurements_revision_idx
    ON public.drawing_measurements (tenant_id, revision_id, taken_at DESC);

CREATE INDEX IF NOT EXISTS drawing_measurements_boq_idx
    ON public.drawing_measurements (tenant_id, boq_item_id)
 WHERE boq_item_id IS NOT NULL;

ALTER TABLE public.drawing_measurements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.drawing_measurements FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS drawing_measurements_tenant_isolation ON public.drawing_measurements;
CREATE POLICY drawing_measurements_tenant_isolation
    ON public.drawing_measurements
    USING      (tenant_id = app_current_tenant_id())
    WITH CHECK (tenant_id = app_current_tenant_id());


-- ============================================================================
-- ⑤ 🔴 THE GUARDS
-- ============================================================================
--
-- ⚠️ A SUPERSEDED REVISION IS FROZEN. Rev B is what the slab was poured
--    against; editing it after Rev C arrives destroys the only evidence of
--    what was built to what.

CREATE OR REPLACE FUNCTION public.ordence_guard_superseded_revision()
RETURNS trigger
LANGUAGE plpgsql
AS $guard$
BEGIN
    IF OLD.superseded_at IS NOT NULL THEN
        -- ⭐ ONE EXCEPTION, AND ONLY ONE: un-superseding it, which is how a
        --    revision issued in error is withdrawn. Everything else is frozen.
        IF NEW.superseded_at IS NULL
           AND NEW.document_id   = OLD.document_id
           AND NEW.revision      = OLD.revision
           AND NEW.revision_order = OLD.revision_order THEN
            RETURN NEW;
        END IF;
        RAISE EXCEPTION
            'Revision % of this drawing has been superseded and cannot be changed. It is the evidence of what was issued and built to at the time; a correction is a new revision, which leaves the old one readable. To withdraw a revision issued in error, un-supersede it first.', OLD.revision
            USING ERRCODE = 'raise_exception';
    END IF;
    RETURN NEW;
END
$guard$;

DROP TRIGGER IF EXISTS ordence_guard_superseded_revision ON public.drawing_revisions;
CREATE TRIGGER ordence_guard_superseded_revision
    BEFORE UPDATE ON public.drawing_revisions
    FOR EACH ROW EXECUTE FUNCTION public.ordence_guard_superseded_revision();

-- 🔴 AND A MEASUREMENT IS APPEND-ONLY. It is a quantity that may already be in
--    a bill. A wrong measurement is corrected by taking another one, which
--    leaves both readable and the difference visible — not by editing the
--    number somebody was paid against.

CREATE OR REPLACE FUNCTION public.ordence_guard_drawing_measurements()
RETURNS trigger
LANGUAGE plpgsql
AS $guard$
BEGIN
    -- ⚠️ ATTACHING A MEASUREMENT TO A BOQ LINE IS NOT A CHANGE TO THE
    --    MEASUREMENT, and it happens after the takeoff. Everything else is.
    IF TG_OP = 'UPDATE'
       AND NEW.value_si     = OLD.value_si
       AND NEW.max_error_si = OLD.max_error_si
       AND NEW.is_exact     = OLD.is_exact
       AND NEW.unit_basis   = OLD.unit_basis
       AND NEW.revision_id  = OLD.revision_id
       AND NEW.points       = OLD.points THEN
        RETURN NEW;
    END IF;
    RAISE EXCEPTION
        'A drawing measurement cannot be edited. It is a quantity that may already be in a bill, and the edit somebody wants to make is always the one that changes what was paid. Take the measurement again: both readings stay readable and the difference is visible.'
        USING ERRCODE = 'raise_exception';
END
$guard$;

DROP TRIGGER IF EXISTS ordence_guard_drawing_measurements ON public.drawing_measurements;
CREATE TRIGGER ordence_guard_drawing_measurements
    BEFORE UPDATE OR DELETE ON public.drawing_measurements
    FOR EACH ROW EXECUTE FUNCTION public.ordence_guard_drawing_measurements();


-- ============================================================================
-- ⑥ THE VERDICT
-- ============================================================================

SELECT
    'SQL 0118 · The drawing register'                                       AS migration,
    (SELECT count(*) FROM information_schema.tables
      WHERE table_schema = 'public'
        AND table_name IN ('drawings', 'drawing_revisions',
                           'drawing_markups', 'drawing_measurements'))      AS tables_expect_4,
    (SELECT count(*) FROM pg_policies
      WHERE schemaname = 'public'
        AND tablename IN ('drawings', 'drawing_revisions',
                          'drawing_markups', 'drawing_measurements'))       AS policies_expect_4,
    (SELECT count(*) FROM pg_trigger
      WHERE NOT tgisinternal
        AND tgname IN ('ordence_guard_superseded_revision',
                       'ordence_guard_drawing_measurements'))               AS guards_expect_2,
    (SELECT count(*) FROM pg_indexes
      WHERE schemaname = 'public'
        AND indexname IN ('drawings_number_in_project',
                          'drawings_number_without_project',
                          'drawing_revisions_label_once',
                          'drawing_revisions_order_once'))                  AS unique_indexes_expect_4;
