/**
 * Ordence — Security Event Vocabulary
 * Version: v0.12.0-alpha (Phase 20)
 *
 * ══════════════════════════════════════════════════════════════════════
 * WHAT BELONGS IN THIS STREAM, AND WHAT DOES NOT
 * ══════════════════════════════════════════════════════════════════════
 * This platform already has TWO evidence tables and they are not being
 * replaced:
 *
 *   `audit_logs`         — WHAT A PRINCIPAL DID. "Priya voided invoice
 *                          AH/2026-27/000144." Every row has an actor, a
 *                          resource and an intent. It answers "who changed
 *                          this?" and it is the record a customer, an
 *                          auditor or a court reads.
 *
 *   `permission_denials` — WHAT A KNOWN PRINCIPAL WAS REFUSED. Still a user
 *                          action; it simply did not happen. Written by
 *                          `checkPermission()` in `server/audit.ts`.
 *
 * `security_events` is the third, and the boundary is deliberately sharp:
 *
 *   IT RECORDS THINGS THAT ARE NOT USER ACTIONS.
 *
 * A rate-limit trip is not an action — it is the platform refusing to let a
 * request reach the code that would have produced an action. A webhook HMAC
 * failure has no principal at all; the caller is anonymous and possibly
 * hostile. A portal token tried from forty IP addresses is a PATTERN, not an
 * event any single request would describe. An anomaly detection is our own
 * inference, not a fact about a request.
 *
 * The test to apply at a call site, in order:
 *
 *   1. Is there an authenticated actor who INTENDED this?      → audit_logs
 *   2. Is it an authenticated actor being refused a permission? → permission_denials
 *   3. Everything else that a security reviewer would want      → security_events
 *
 * Why the split matters rather than merging everything into `audit_logs`:
 * volume and trust. A scraper can generate ten thousand rate-limit trips in a
 * minute. Putting those in `audit_logs` would bury the twelve rows that say a
 * human closed an accounting period, and it would make the table that has to
 * be defensible in a dispute mostly composed of noise generated by strangers.
 * The two streams also have different retention needs — audit is kept for
 * years, SecOps telemetry for weeks.
 *
 * ══════════════════════════════════════════════════════════════════════
 * WHY THIS MODULE IS PURE
 * ══════════════════════════════════════════════════════════════════════
 * No database, no `next/headers`, no `server-only`. The vocabulary has to be
 * importable from the limiter (which may run on the Edge runtime in
 * middleware), from the recorder (Node), from the SIEM serialiser (a script)
 * and from tests. A closed enum shared by all four is what stops the event
 * type from becoming a free-text field that nobody can query.
 */

/* ------------------------------------------------------------------ */
/* THE CLOSED ENUM                                                     */
/* ------------------------------------------------------------------ */

/**
 * Every security event type this platform can emit.
 *
 * ⚠️ CLOSED SET, ON PURPOSE. A free-text `type` column looks flexible and
 * then produces `rate_limit`, `rate-limit`, `rateLimit` and
 * `rate_limit_exceeded` in the same table, at which point no dashboard and
 * no SIEM correlation rule can be trusted. Adding a member here is a code
 * change, a schema change (`db/schema/secops.ts`) and a migration — which is
 * the correct amount of friction for extending a security vocabulary.
 *
 * Names are `subject.verb_in_past_tense`, lowercase, dot-separated. The
 * prefix is what SIEM rules group on.
 */
export const SECURITY_EVENT_TYPES = [
  /* --- Rate limiting (SEC-005, SEC-020, SEC-024) ------------------- */
  /** A request was refused because the caller exceeded a named policy. */
  "rate_limit.exceeded",
  /**
   * The limiter ran without Redis and fell back to per-instance memory.
   * Emitted at most once per process (see `lib/security/rate-limit.ts`) —
   * it is a CONFIGURATION alarm, not a per-request event.
   */
  "rate_limit.degraded",

  /* --- Authentication --------------------------------------------- */
  "auth.login_failed",
  "auth.brute_force_suspected",
  "auth.session_anomaly",

  /* --- Webhooks (public, unauthenticated surfaces) ----------------- */
  /** HMAC did not verify. The single most important row in this table. */
  "webhook.signature_invalid",
  /** Signature verified but the timestamp was outside the tolerance. */
  "webhook.replay_suspected",
  /** We are misconfigured — no signing secret. Ours to fix, not an attack. */
  "webhook.secret_missing",

  /* --- Client portal ---------------------------------------------- */
  "portal.token_invalid",
  "portal.token_expired",
  "portal.token_revoked_use",
  /** One token presented from many distinct IPs — a forwarded/leaked link. */
  "portal.token_shared_suspected",

  /* --- Data movement ---------------------------------------------- */
  "export.bulk",
  "export.off_hours",
  "upload.rejected",

  /* --- Authorization pattern (NOT the individual denial) ----------- */
  /**
   * A SPIKE in permission denials. The individual denials live in
   * `permission_denials`; this row says "the shape of them changed".
   */
  "authz.denial_spike",

  /* --- Tenancy ----------------------------------------------------- */
  /**
   * A request tried to reach a resource outside its tenant. If this ever
   * fires in production it is either an attack or a bug in our scoping, and
   * both are page-someone events.
   */
  "tenant.cross_access_attempt",

  /* --- Anomaly detector output ------------------------------------- */
  "anomaly.detected",
] as const;

export type SecurityEventType = (typeof SECURITY_EVENT_TYPES)[number];

/** Narrow an untrusted string to a known event type. */
export function isSecurityEventType(value: unknown): value is SecurityEventType {
  return (
    typeof value === "string" &&
    (SECURITY_EVENT_TYPES as readonly string[]).includes(value)
  );
}

/* ------------------------------------------------------------------ */
/* SEVERITY                                                            */
/* ------------------------------------------------------------------ */

/**
 * Four levels, matching `audit_logs.severity` exactly so a SIEM can put both
 * streams on one axis without a translation table.
 *
 *   info     — happened, expected, kept for correlation.
 *   notice   — worth a human glance in a weekly review.
 *   warning  — something is probably wrong; look today.
 *   critical — someone is being attacked or we are broken. Page.
 */
export const SECURITY_SEVERITIES = ["info", "notice", "warning", "critical"] as const;
export type SecuritySeverity = (typeof SECURITY_SEVERITIES)[number];

const SEVERITY_ORDER: Record<SecuritySeverity, number> = {
  info: 0,
  notice: 1,
  warning: 2,
  critical: 3,
};

/** True when `a` is at least as severe as `b`. Used for alert thresholds. */
export function atLeastSeverity(a: SecuritySeverity, b: SecuritySeverity): boolean {
  return SEVERITY_ORDER[a] >= SEVERITY_ORDER[b];
}

/**
 * The DEFAULT severity of each event type.
 *
 * A call site may raise it (a rate-limit trip on the login route during a
 * credential-stuffing run is not "notice") but may not silently lower it —
 * see `resolveSeverity()`. Downgrading an alarm has to be a deliberate,
 * reviewable act, not an argument someone passed by accident.
 *
 * ⚠️ Note `webhook.signature_invalid` is CRITICAL. On this platform the HMAC
 * is the only thing between the internet and subscription state, so a
 * verification failure is either an attacker probing or our own secret
 * rotated wrongly — and the second one loses payments silently.
 */
export const DEFAULT_SEVERITY: Record<SecurityEventType, SecuritySeverity> = {
  "rate_limit.exceeded": "notice",
  "rate_limit.degraded": "warning",

  "auth.login_failed": "info",
  "auth.brute_force_suspected": "critical",
  "auth.session_anomaly": "warning",

  "webhook.signature_invalid": "critical",
  "webhook.replay_suspected": "warning",
  "webhook.secret_missing": "critical",

  "portal.token_invalid": "info",
  "portal.token_expired": "info",
  "portal.token_revoked_use": "warning",
  "portal.token_shared_suspected": "warning",

  "export.bulk": "notice",
  "export.off_hours": "warning",
  "upload.rejected": "info",

  "authz.denial_spike": "warning",

  "tenant.cross_access_attempt": "critical",

  "anomaly.detected": "warning",
};

/**
 * Resolve the severity for an event.
 *
 * Takes the HIGHER of the default and any requested override. A caller can
 * escalate; a caller cannot demote. The concrete failure this prevents: a
 * handler that emits `webhook.signature_invalid` with `severity: "info"`
 * because the author was testing locally and got tired of the noise, and the
 * line ships. The alarm then never fires again and nobody notices, because
 * a missing alarm produces no output at all.
 */
export function resolveSeverity(
  type: SecurityEventType,
  requested?: SecuritySeverity,
): SecuritySeverity {
  const base = DEFAULT_SEVERITY[type];
  if (!requested) return base;
  return SEVERITY_ORDER[requested] > SEVERITY_ORDER[base] ? requested : base;
}

/* ------------------------------------------------------------------ */
/* THE EVENT SHAPE                                                     */
/* ------------------------------------------------------------------ */

/**
 * A security event as the application constructs it.
 *
 * `tenantId` is OPTIONAL and that is the whole design problem of this table
 * — see the long note in `db/schema/secops.ts`. Most of the events worth
 * having arrive on surfaces where no tenant is known yet: a bad HMAC, a
 * garbage portal token, a login attempt for an address that does not exist.
 */
export type SecurityEventInput = {
  type: SecurityEventType;
  severity?: SecuritySeverity;

  /** Null for pre-authentication and unmapped-webhook surfaces. */
  tenantId?: string | null;

  /** Where it happened — "api/webhooks/razorpay", "portal", "middleware". */
  source: string;

  /**
   * What the event is ABOUT, in a form safe to store.
   * ⚠️ Never a raw portal token, never a session cookie, never a password.
   * `subjectId` for a portal event is the token PREFIX or a hash, never the
   * credential — this table is queried by more people than can be trusted
   * with a live credential, and it is exported to a SIEM.
   */
  subjectType?: string | null;
  subjectId?: string | null;

  /** Present only when the actor was actually authenticated. */
  actorUserId?: string | null;

  ipAddress?: string | null;
  userAgent?: string | null;
  requestId?: string | null;
  route?: string | null;

  /** Free-form circumstance. Redacted through `sanitiseDetail()` on write. */
  detail?: Record<string, unknown>;

  /** Human sentence for the alert body. No secrets. */
  reason?: string | null;
};

/* ------------------------------------------------------------------ */
/* REDACTION                                                           */
/* ------------------------------------------------------------------ */

/**
 * Keys whose VALUES are never written to `security_events`, at any depth.
 *
 * THE FAILURE THIS PREVENTS: an engineer debugging a webhook rejection adds
 * `detail: { headers: Object.fromEntries(request.headers) }`. That header bag
 * contains `x-razorpay-signature` and, on some surfaces, a `cookie` with a
 * live session. Those values then sit in a table that is deliberately
 * append-only — meaning once written they cannot be deleted — and are shipped
 * to a third-party SIEM by design. There is no cleanup path. So the redaction
 * runs on every write rather than at the call sites that remember.
 */
const REDACTED_KEY_PATTERN =
  /(token|secret|password|passwd|signature|authorization|cookie|api[_-]?key|bearer|private[_-]?key|otp|pin)/i;

const REDACTION_PLACEHOLDER = "[REDACTED]";

/** Values longer than this are truncated — a log line is not a payload store. */
const MAX_STRING_LENGTH = 500;
const MAX_DEPTH = 4;

/**
 * Recursively strip secret-shaped values from a detail object.
 *
 * Depth-limited because a self-referencing object would otherwise hang the
 * request that is trying to report an attack — the worst possible moment to
 * introduce an infinite loop.
 */
export function sanitiseDetail(
  input: Record<string, unknown> | undefined,
  depth = 0,
): Record<string, unknown> {
  if (!input) return {};
  if (depth >= MAX_DEPTH) return { truncated: "max_depth" };

  const out: Record<string, unknown> = {};

  for (const [key, value] of Object.entries(input)) {
    if (REDACTED_KEY_PATTERN.test(key)) {
      out[key] = REDACTION_PLACEHOLDER;
      continue;
    }

    if (value === null || value === undefined) {
      out[key] = null;
    } else if (typeof value === "string") {
      out[key] =
        value.length > MAX_STRING_LENGTH
          ? `${value.slice(0, MAX_STRING_LENGTH)}…[truncated]`
          : value;
    } else if (typeof value === "number" || typeof value === "boolean") {
      out[key] = value;
    } else if (Array.isArray(value)) {
      out[key] = value
        .slice(0, 20)
        .map((v) =>
          v && typeof v === "object"
            ? sanitiseDetail(v as Record<string, unknown>, depth + 1)
            : typeof v === "string" && v.length > MAX_STRING_LENGTH
              ? `${v.slice(0, MAX_STRING_LENGTH)}…[truncated]`
              : (v as unknown),
        );
    } else if (typeof value === "object") {
      out[key] = sanitiseDetail(value as Record<string, unknown>, depth + 1);
    } else {
      // functions, symbols, bigint — nothing legitimate, dropped by name.
      out[key] = REDACTION_PLACEHOLDER;
    }
  }

  return out;
}

/* ------------------------------------------------------------------ */
/* PRESENTATION                                                        */
/* ------------------------------------------------------------------ */

/** Short human label per type, for a console list or an alert subject. */
export const SECURITY_EVENT_LABELS: Record<SecurityEventType, string> = {
  "rate_limit.exceeded": "Rate limit exceeded",
  "rate_limit.degraded": "Rate limiter running without Redis",
  "auth.login_failed": "Failed sign-in",
  "auth.brute_force_suspected": "Possible brute-force attempt",
  "auth.session_anomaly": "Unusual session behaviour",
  "webhook.signature_invalid": "Webhook signature verification failed",
  "webhook.replay_suspected": "Possible webhook replay",
  "webhook.secret_missing": "Webhook signing secret not configured",
  "portal.token_invalid": "Invalid portal token presented",
  "portal.token_expired": "Expired portal token presented",
  "portal.token_revoked_use": "Revoked portal token presented",
  "portal.token_shared_suspected": "Portal link appears to be shared",
  "export.bulk": "Bulk data export",
  "export.off_hours": "Out-of-hours data export",
  "upload.rejected": "Upload rejected",
  "authz.denial_spike": "Spike in permission denials",
  "tenant.cross_access_attempt": "Cross-tenant access attempt",
  "anomaly.detected": "Anomaly detected",
};

export function describeSecurityEvent(type: SecurityEventType): string {
  return SECURITY_EVENT_LABELS[type];
}
