"use server";

/**
 * Ordence — Options the lead screens need
 * Version: v1.43.0-alpha (Mega-wave 1, Batch 35)
 *
 * ══════════════════════════════════════════════════════════════════════
 * ⚠️ SEPARATE FROM `sales-leads.ts` ON PURPOSE
 * ══════════════════════════════════════════════════════════════════════
 * The reason `orders-form.ts` gives about `orders.ts` applies here
 * unchanged: every export of a `"use server"` file is a browser-reachable
 * RPC endpoint, so `sales-leads.ts` is read as a guard audit — eight
 * exports, eight gates, nothing else in the file. A read helper for three
 * dropdowns wedged between `transitionLead` and `logLeadActivity` makes
 * that audit harder to do, and the audit is the only thing between a
 * tenant's pipeline and the internet.
 *
 * ══════════════════════════════════════════════════════════════════════
 * 🔴 AND IT IS NOT `listProjectOptions` FROM `orders-form.ts`
 * ══════════════════════════════════════════════════════════════════════
 * That function returns exactly the shape this one needs, and reusing it
 * would still have been wrong: it is gated on `sales.orders.read`, which
 * the `member` role does not hold. `member` IS the sales executive — the
 * person who fills this form in — and they have `leads:create`,
 * `projects:read` and `partners:read` but no orders keys at all.
 *
 * Reusing that helper would therefore hand the primary user of the screen
 * an empty project dropdown and no explanation of why, which costs more
 * than a second twelve-line query.
 */

import { and, asc, eq, isNull } from "drizzle-orm";
import { withTenant } from "@/db";
import { users } from "@/db/schema";
import { projects, channelPartners } from "@/db/schema/sales";
import { requirePermission } from "@/server/audit";
import { toSalesActionError } from "@/server/sales/guards";
import { can } from "@/lib/permissions";
import type { ActionResult } from "@/lib/validators/crm";

export type LeadFormOption = { id: string; label: string; hint?: string };

/**
 * Everything the create and edit forms put in a `<select>`.
 *
 * ⚠️ ONE ROUND TRIP, NOT THREE. Three actions means three tenant
 * transactions and three permission evaluations for one form, and a
 * screen whose dropdowns arrive at three different moments.
 */
export async function listLeadFormOptions(): Promise<
  ActionResult<{
    projects: LeadFormOption[];
    partners: LeadFormOption[];
    owners: LeadFormOption[];
    /**
     * Lists the caller was not allowed to see, named so the form can say
     * "you cannot pick an owner" rather than rendering an empty select.
     */
    withheld: string[];
  }>
> {
  try {
    /**
     * ⚠️ THE GATE IS `leads:read`, AND EACH LIST CARRIES ITS OWN KEY.
     *
     * `leads:read` is the weakest key any visitor to these two screens
     * holds, so it is the right gate on the endpoint itself. But a
     * project list, a partner list and a staff list are disclosures from
     * three OTHER modules, and a single gate would leak all three to
     * anyone who can open the pipeline.
     *
     * 🔴 SO EACH LIST IS CHECKED SEPARATELY — with `can()`, which is
     * pure, and NOT with `checkPermission()`, which writes a row to
     * `permission_denials`. This is not somebody attempting something
     * they should not; it is a form deciding what to render. Logging it
     * as a denial would fill the security review with noise generated by
     * page loads, which is how a real denial stops being noticed.
     */
    const ctx = await requirePermission("leads:read");
    const subject = { role: ctx.role, overrides: ctx.user.permissionOverrides };

    const mayReadProjects = can(subject, "projects:read");
    const mayReadPartners = can(subject, "partners:read");
    const mayReadUsers = can(subject, "users:read");

    const data = await withTenant(ctx.tenant.id, async (tx) => {
      const projectRows = mayReadProjects
        ? await tx
            .select({ id: projects.id, code: projects.code, name: projects.name })
            .from(projects)
            .where(and(eq(projects.tenantId, ctx.tenant.id), isNull(projects.deletedAt)))
            .orderBy(asc(projects.name))
            .limit(500)
        : [];

      const partnerRows = mayReadPartners
        ? await tx
            .select({
              id: channelPartners.id,
              code: channelPartners.code,
              firmName: channelPartners.firmName,
              reraNumber: channelPartners.reraNumber,
            })
            .from(channelPartners)
            .where(
              and(
                eq(channelPartners.tenantId, ctx.tenant.id),
                isNull(channelPartners.deletedAt),
                /**
                 * ⚠️ ACTIVE PARTNERS ONLY, and this is a commission
                 * decision rather than tidiness. Attributing a lead to a
                 * terminated or suspended firm starts a protection window
                 * against a payout that `payoutBlockerFor()` already
                 * refuses — so the argument happens at the booking, months
                 * later, with the window as evidence for the wrong side.
                 */
                eq(channelPartners.status, "active"),
              ),
            )
            .orderBy(asc(channelPartners.firmName))
            .limit(500)
        : [];

      const ownerRows = mayReadUsers
        ? await tx
            .select({
              id: users.id,
              email: users.email,
              firstName: users.firstName,
              lastName: users.lastName,
            })
            .from(users)
            .where(
              and(
                eq(users.tenantId, ctx.tenant.id),
                isNull(users.deletedAt),
                /**
                 * ⚠️ Not `invited` and not `suspended`. A lead assigned to
                 * somebody who has never signed in is a lead nobody is
                 * working, and it looks assigned on every report.
                 */
                eq(users.status, "active"),
              ),
            )
            .orderBy(asc(users.email))
            .limit(500)
        : [];

      return { projectRows, partnerRows, ownerRows };
    });

    const withheld: string[] = [];
    if (!mayReadProjects) withheld.push("projects");
    if (!mayReadPartners) withheld.push("partners");
    if (!mayReadUsers) withheld.push("owners");

    return {
      ok: true,
      data: {
        projects: data.projectRows.map((p) => ({
          id: p.id,
          label: `${p.code} · ${p.name}`,
        })),
        partners: data.partnerRows.map((p) => ({
          id: p.id,
          label: p.firmName,
          /**
           * ⭐ THE RERA NUMBER IS THE HINT, AND ITS ABSENCE IS THE POINT.
           * A broker without a RERA registration cannot lawfully act on a
           * project sale. Showing which firms can answer that, and which
           * cannot, puts the question in front of the rep while they are
           * choosing rather than in front of a compliance officer a
           * quarter later.
           */
          hint: p.reraNumber ? `RERA ${p.reraNumber}` : `${p.code} · no RERA on file`,
        })),
        owners: data.ownerRows.map((u) => ({
          id: u.id,
          label: [u.firstName, u.lastName].filter(Boolean).join(" ") || u.email,
          hint: u.email,
        })),
        withheld,
      },
    };
  } catch (err) {
    return toSalesActionError(err, "listLeadFormOptions");
  }
}
